/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\simon\rationalnes_\rnes\src\nimcache\mem.o c:\users\simon\rationalnes_\rnes\src\nimcache\mem.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct cpumemoryobj223007 cpumemoryobj223007;
typedef struct TY136033 TY136033;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY221030 TY221030;
typedef struct NimStringDesc NimStringDesc;
typedef struct tcell44933 tcell44933;
typedef struct tcellseq44949 tcellseq44949;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellset44945 tcellset44945;
typedef struct tpagedesc44941 tpagedesc44941;
typedef struct tmemregion27210 tmemregion27210;
typedef struct tsmallchunk26440 tsmallchunk26440;
typedef struct tllchunk27204 tllchunk27204;
typedef struct tbigchunk26442 tbigchunk26442;
typedef struct tintset26417 tintset26417;
typedef struct ttrunk26413 ttrunk26413;
typedef struct tavlnode27208 tavlnode27208;
typedef struct tgcstat47014 tgcstat47014;
typedef struct romobj136027 romobj136027;
typedef struct tbasechunk26438 tbasechunk26438;
typedef struct tfreecell26430 tfreecell26430;
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  cpumemoryobj223007  {
  TNimObject Sup;
TY221030* Bank;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell44933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq44949  {
NI Len;
NI Cap;
tcell44933** D;
};
struct  tcellset44945  {
NI Counter;
NI Max;
tpagedesc44941* Head;
tpagedesc44941** Data;
};
typedef tsmallchunk26440* TY27222[512];
typedef ttrunk26413* ttrunkbuckets26415[256];
struct  tintset26417  {
ttrunkbuckets26415 Data;
};
struct  tmemregion27210  {
NI Minlargeobj;
NI Maxlargeobj;
TY27222 Freesmallchunks;
tllchunk27204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26442* Freechunkslist;
tintset26417 Chunkstarts;
tavlnode27208* Root;
tavlnode27208* Deleted;
tavlnode27208* Last;
tavlnode27208* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44949 Zct;
tcellseq44949 Decstack;
tcellset44945 Cycleroots;
tcellseq44949 Tempstack;
NI Recgclock;
tmemregion27210 Region;
tgcstat47014 Stat;
};
typedef NIM_CHAR TY136030[16];
struct  romobj136027  {
  TNimObject Sup;
TY136030 Header;
TY136033* Prgbytes;
TY136033* Chrbytes;
};
typedef NI TY26420[8];
struct  tpagedesc44941  {
tpagedesc44941* Next;
NI Key;
TY26420 Bits;
};
struct  tbasechunk26438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26440  {
  tbasechunk26438 Sup;
tsmallchunk26440* Next;
tsmallchunk26440* Prev;
tfreecell26430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27204  {
NI Size;
NI Acc;
tllchunk27204* Next;
};
struct  tbigchunk26442  {
  tbasechunk26438 Sup;
tbigchunk26442* Next;
tbigchunk26442* Prev;
NI Align;
NF Data;
};
struct  ttrunk26413  {
ttrunk26413* Next;
NI Key;
TY26420 Bits;
};
typedef tavlnode27208* TY27214[2];
struct  tavlnode27208  {
TY27214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26430  {
tfreecell26430* Next;
NI Zerofield;
};
struct TY136033 {
  TGenericSeq Sup;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY221030 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, setprogram_223018)(void* program);
N_NIMCALL(TY136033*, newseq_136510)(NI len_136514);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, reflectvalue_223096)(NI address, NI value);
N_NIMCALL(void, updateregisters_222554)(NI address, NI value);
N_NIMCALL(void, reflectbitwise_223106)(NI address, NI bitid);
N_NIMCALL(void, transmittoregister_222533)(NI address, NI value);
N_NIMCALL(void, mmiowrite_223117)(NI address, NI value);
N_NIMCALL(NI, mmioread_223136)(NI address);
N_NIMCALL(NI, readstatus_222429)(void);
N_NIMCALL(NI, getmemoryshortat_223154)(NI address);
N_NIMCALL(void*, getmemoryaddressat_223166)(NI address);
N_NIMCALL(NI, checkfromdebug_223177)(NI address);
N_NIMCALL(void, initmem_223187)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP441)(void* p, NI op);
static N_INLINE(void, nimGCunref)(void* p);
static N_INLINE(void, decref_50604)(tcell44933* c);
static N_INLINE(void, rtladdzct_50204)(tcell44933* c);
N_NOINLINE(void, addzct_48617)(tcellseq44949* s, tcell44933* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48667)(tcell44933* c);
static N_INLINE(void, rtladdcycleroot_49429)(tcell44933* c);
N_NOINLINE(void, incl_45671)(tcellset44945* s, tcell44933* cell);
static N_INLINE(tcell44933*, usrtocell_48646)(void* usr);
N_NIMCALL(void*, newObjRC1)(TNimType* typ, NI size);
N_NIMCALL(TY221030*, newseq_222747)(NI len_222751);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
STRING_LITERAL(TMP439, "Invalid address", 15);
cpumemoryobj223007* cpumemory_223013;
extern TFrame* frameptr_16242;
extern TNimType NTI3211; /* RootObj */
TNimType NTI223007; /* CPUMemoryObj */
extern TNimType NTI221030; /* seq[int] */
TNimType NTI223005; /* CPUMemoryRef */
extern tgcheap47016 gch_47044;
extern romobj136027 nesrom_136046;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(void, setprogram_223018)(void* program) {
	TY136033* temporarybank;
	nimfr("setProgram", "mem.nim")
	nimln(14, "mem.nim");
	temporarybank = newseq_136510(65536);
	nimln(15, "mem.nim");
	if ((NU)(32768) >= (NU)(temporarybank->Sup.len)) raiseIndexError();
	memcpy(((void*) ((&temporarybank->data[32768]))), program, 32768);
	{
		NI i_223074;
		NIM_CHAR value_223075;
		NI i_223080;
		i_223074 = 0;
		value_223075 = 0;
		nimln(1704, "system.nim");
		i_223080 = 0;
		{
			nimln(1705, "system.nim");
			while (1) {
				nimln(1705, "system.nim");
				nimln(1705, "system.nim");
				if (!(i_223080 < temporarybank->Sup.len)) goto LA3;
				nimln(1704, "system.nim");
				i_223074 = i_223080;
				nimln(1706, "system.nim");
				if ((NU)(i_223080) >= (NU)(temporarybank->Sup.len)) raiseIndexError();
				value_223075 = temporarybank->data[i_223080];
				nimln(17, "mem.nim");
				if ((NU)(i_223074) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
				(*cpumemory_223013).Bank->data[i_223074] = ((NI) (((NU8)(value_223075))));
				nimln(1707, "system.nim");
				i_223080 = addInt(i_223080, 1);
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, reflectvalue_223096)(NI address, NI value) {
	nimfr("reflectValue", "mem.nim")
	nimln(21, "mem.nim");
	if ((NU)(address) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
	(*cpumemory_223013).Bank->data[address] = value;
	nimln(22, "mem.nim");
	if ((NU)(address) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
	updateregisters_222554(address, (*cpumemory_223013).Bank->data[address]);
	popFrame();
}

N_NIMCALL(void, reflectbitwise_223106)(NI address, NI bitid) {
	NI bit;
	nimfr("reflectBitwise", "mem.nim")
	nimln(28, "mem.nim");
	nimln(28, "mem.nim");
	if ((NU)(address) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
	nimln(28, "mem.nim");
	bit = (NI)((*cpumemory_223013).Bank->data[address] & (NI)((NU64)(1) << (NU64)(bitid)));
	nimln(29, "mem.nim");
	{
		nimln(29, "mem.nim");
		if (!(bit == 0)) goto LA3;
		nimln(30, "mem.nim");
		if ((NU)(address) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
		nimln(30, "mem.nim");
		nimln(30, "mem.nim");
		if ((NU)(address) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
		(*cpumemory_223013).Bank->data[address] = (NI)((NU64)((NI)((*cpumemory_223013).Bank->data[address] | 1)) << (NU64)(bitid));
	}
	goto LA1;
	LA3: ;
	{
		nimln(32, "mem.nim");
		if ((NU)(address) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
		nimln(32, "mem.nim");
		if ((NU)(address) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
		nimln(32, "mem.nim");
		nimln(32, "mem.nim");
		(*cpumemory_223013).Bank->data[address] = (NI)((*cpumemory_223013).Bank->data[address] & (NI)((NU64) ~((NI)((NU64)(1) << (NU64)(bitid)))));
	}
	LA1: ;
	nimln(33, "mem.nim");
	if ((NU)(address) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
	transmittoregister_222533(address, (*cpumemory_223013).Bank->data[address]);
	popFrame();
}

N_NIMCALL(void, mmiowrite_223117)(NI address, NI value) {
	nimfr("mmioWrite", "mem.nim")
	nimln(39, "mem.nim");
	switch (address) {
	case 0 ... 6553:
	case 8200 ... 65536:
	{
		nimln(41, "mem.nim");
		if ((NU)(address) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
		(*cpumemory_223013).Bank->data[address] = value;
	}
	break;
	case 8192:
	case 8199:
	{
		nimln(43, "mem.nim");
		reflectvalue_223096(address, value);
	}
	break;
	default:
	{
		nimln(45, "mem.nim");
		nimln(45, "mem.nim");
		printf("%s\015\012", (((NimStringDesc*) &TMP439))->data);
	}
	break;
	}
	popFrame();
}

N_NIMCALL(NI, mmioread_223136)(NI address) {
	NI result;
	nimfr("mmioRead", "mem.nim")
	result = 0;
	nimln(50, "mem.nim");
	switch (address) {
	case 0 ... 8193:
	case 8195 ... 65536:
	{
		nimln(52, "mem.nim");
		if ((NU)(address) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
		result = (*cpumemory_223013).Bank->data[address];
	}
	break;
	case 8194:
	{
		nimln(54, "mem.nim");
		result = readstatus_222429();
	}
	break;
	default:
	{
		nimln(56, "mem.nim");
		nimln(56, "mem.nim");
		printf("%s\015\012", (((NimStringDesc*) &TMP439))->data);
		nimln(57, "mem.nim");
		nimln(57, "mem.nim");
		result = 0;
		goto BeforeRet;
	}
	break;
	}
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, getmemoryshortat_223154)(NI address) {
	NI result;
	NI lowbyte;
	NI highbyte;
	NI TMP440;
	nimfr("getMemoryShortAt", "mem.nim")
	result = 0;
	nimln(60, "mem.nim");
	if ((NU)(address) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
	lowbyte = (*cpumemory_223013).Bank->data[address];
	nimln(61, "mem.nim");
	nimln(61, "mem.nim");
	nimln(61, "mem.nim");
	TMP440 = addInt(address, 1);
	if ((NU)((NI64)(TMP440)) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
	highbyte = (NI)((NU64)((*cpumemory_223013).Bank->data[(NI64)(TMP440)]) << (NU64)(8));
	nimln(62, "mem.nim");
	nimln(62, "mem.nim");
	nimln(62, "mem.nim");
	result = (NI)(highbyte | lowbyte);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void*, getmemoryaddressat_223166)(NI address) {
	void* result;
	nimfr("getMemoryAddressAt", "mem.nim")
	result = 0;
	nimln(65, "mem.nim");
	nimln(65, "mem.nim");
	if ((NU)(address) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
	result = ((void*) ((&(*cpumemory_223013).Bank->data[address])));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, checkfromdebug_223177)(NI address) {
	NI result;
	nimfr("checkFromDebug", "mem.nim")
	result = 0;
	nimln(68, "mem.nim");
	nimln(68, "mem.nim");
	if ((NU)(address) >= (NU)((*cpumemory_223013).Bank->Sup.len)) raiseIndexError();
	result = (*cpumemory_223013).Bank->data[address];
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP441)(void* p, NI op) {
	cpumemoryobj223007* a;
	a = (cpumemoryobj223007*)p;
	nimGCvisit((void*)(*a).Bank, op);
}

static N_INLINE(void, rtladdzct_50204)(tcell44933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_48667)(tcell44933* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49429)(tcell44933* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_45671((&gch_47044.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, decref_50604)(tcell44933* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50204(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_48667(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49429(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(tcell44933*, usrtocell_48646)(void* usr) {
	tcell44933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell44933*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell44933))))));
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunref)(void* p) {
	tcell44933* LOC1;
	nimfr("nimGCunref", "gc.nim")
	nimln(223, "gc.nim");
	nimln(223, "gc.nim");
	LOC1 = 0;
	LOC1 = usrtocell_48646(p);
	decref_50604(LOC1);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell44933* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48646(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell44933* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48646((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50204(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, initmem_223187)(void) {
	nimfr("initMem", "mem.nim")
	nimln(71, "mem.nim");
	if (cpumemory_223013) nimGCunref(cpumemory_223013);
	cpumemory_223013 = (cpumemoryobj223007*) newObjRC1((&NTI223005), sizeof(cpumemoryobj223007));
	(*cpumemory_223013).Sup.m_type = (&NTI223007);
	nimln(73, "mem.nim");
	asgnRefNoCycle((void**) (&(*cpumemory_223013).Bank), newseq_222747(65536));
	nimln(75, "mem.nim");
	if ((NU)(0) >= (NU)(nesrom_136046.Prgbytes->Sup.len)) raiseIndexError();
	setprogram_223018(((void*) ((&nesrom_136046.Prgbytes->data[0]))));
	nimln(77, "mem.nim");
	reflectbitwise_223106(8194, 7);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, HEX00_memInit)(void) {
	nimfr("mem", "mem.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_memDatInit)(void) {
static TNimNode TMP328[1];
NTI223007.size = sizeof(cpumemoryobj223007);
NTI223007.kind = 17;
NTI223007.base = (&NTI3211);
TMP328[0].kind = 1;
TMP328[0].offset = offsetof(cpumemoryobj223007, Bank);
TMP328[0].typ = (&NTI221030);
TMP328[0].name = "bank";
NTI223007.node = &TMP328[0];
NTI223005.size = sizeof(cpumemoryobj223007*);
NTI223005.kind = 22;
NTI223005.base = (&NTI223007);
NTI223005.marker = TMP441;
}

