/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\simon\rationalnes_\rnes\src\nimcache\stdlib_colors.o c:\users\simon\rationalnes_\rnes\src\nimcache\stdlib_colors.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct TY240184 TY240184;
typedef struct TY240556 TY240556;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct valueerror3249 valueerror3249;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell44933 tcell44933;
typedef struct tcellseq44949 tcellseq44949;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellset44945 tcellset44945;
typedef struct tpagedesc44941 tpagedesc44941;
typedef struct tmemregion27210 tmemregion27210;
typedef struct tsmallchunk26440 tsmallchunk26440;
typedef struct tllchunk27204 tllchunk27204;
typedef struct tbigchunk26442 tbigchunk26442;
typedef struct tintset26417 tintset26417;
typedef struct ttrunk26413 ttrunk26413;
typedef struct tavlnode27208 tavlnode27208;
typedef struct tgcstat47014 tgcstat47014;
typedef struct tbasechunk26438 tbasechunk26438;
typedef struct tfreecell26430 tfreecell26430;
struct TY240184 {
NI Field0;
NI Field1;
NI Field2;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY240556 {
NimStringDesc* Field0;
NI Field1;
};
typedef TY240556 TY240555[140];
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  valueerror3249  {
  Exception Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell44933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq44949  {
NI Len;
NI Cap;
tcell44933** D;
};
struct  tcellset44945  {
NI Counter;
NI Max;
tpagedesc44941* Head;
tpagedesc44941** Data;
};
typedef tsmallchunk26440* TY27222[512];
typedef ttrunk26413* ttrunkbuckets26415[256];
struct  tintset26417  {
ttrunkbuckets26415 Data;
};
struct  tmemregion27210  {
NI Minlargeobj;
NI Maxlargeobj;
TY27222 Freesmallchunks;
tllchunk27204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26442* Freechunkslist;
tintset26417 Chunkstarts;
tavlnode27208* Root;
tavlnode27208* Deleted;
tavlnode27208* Last;
tavlnode27208* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44949 Zct;
tcellseq44949 Decstack;
tcellset44945 Cycleroots;
tcellseq44949 Tempstack;
NI Recgclock;
tmemregion27210 Region;
tgcstat47014 Stat;
};
typedef NI TY26420[8];
struct  tpagedesc44941  {
tpagedesc44941* Next;
NI Key;
TY26420 Bits;
};
struct  tbasechunk26438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26440  {
  tbasechunk26438 Sup;
tsmallchunk26440* Next;
tsmallchunk26440* Prev;
tfreecell26430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27204  {
NI Size;
NI Acc;
tllchunk27204* Next;
};
struct  tbigchunk26442  {
  tbasechunk26438 Sup;
tbigchunk26442* Next;
tbigchunk26442* Prev;
NI Align;
NF Data;
};
struct  ttrunk26413  {
ttrunk26413* Next;
NI Key;
TY26420 Bits;
};
typedef tavlnode27208* TY27214[2];
struct  tavlnode27208  {
TY27214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26430  {
tfreecell26430* Next;
NI Zerofield;
};
static N_INLINE(NI, satplus_240065)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, satminus_240088)(NI a, NI b);
N_NIMCALL(NI, HEX2B_240109)(NI a, NI b);
N_NIMCALL(NI, HEX2D_240145)(NI a, NI b);
N_NIMCALL(TY240184, extractrgb_240181)(NI a);
N_NIMCALL(NI, intensity_240206)(NI a, NF f);
N_NIMCALL(NimStringDesc*, HEX24_240700)(NI c);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NI, binarystrsearch_240712)(TY240556* x, NI xLen0, NimStringDesc* y);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NI, cmp_4517)(NimStringDesc* x, NimStringDesc* y);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, parsecolor_240747)(NimStringDesc* name);
N_NIMCALL(NI, nsuParseHexInt)(NimStringDesc* s);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell44933*, usrtocell_48646)(void* usr);
static N_INLINE(void, rtladdzct_50204)(tcell44933* c);
N_NOINLINE(void, addzct_48617)(tcellseq44949* s, tcell44933* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_BOOL, iscolor_240781)(NimStringDesc* name);
N_NIMCALL(NI, rgb_240831)(NI r, NI g, NI b);
STRING_LITERAL(TMP607, "aliceblue", 9);
STRING_LITERAL(TMP608, "antiquewhite", 12);
STRING_LITERAL(TMP609, "aqua", 4);
STRING_LITERAL(TMP610, "aquamarine", 10);
STRING_LITERAL(TMP611, "azure", 5);
STRING_LITERAL(TMP612, "beige", 5);
STRING_LITERAL(TMP613, "bisque", 6);
STRING_LITERAL(TMP614, "black", 5);
STRING_LITERAL(TMP615, "blanchedalmond", 14);
STRING_LITERAL(TMP616, "blue", 4);
STRING_LITERAL(TMP617, "blueviolet", 10);
STRING_LITERAL(TMP618, "brown", 5);
STRING_LITERAL(TMP619, "burlywood", 9);
STRING_LITERAL(TMP620, "cadetblue", 9);
STRING_LITERAL(TMP621, "chartreuse", 10);
STRING_LITERAL(TMP622, "chocolate", 9);
STRING_LITERAL(TMP623, "coral", 5);
STRING_LITERAL(TMP624, "cornflowerblue", 14);
STRING_LITERAL(TMP625, "cornsilk", 8);
STRING_LITERAL(TMP626, "crimson", 7);
STRING_LITERAL(TMP627, "cyan", 4);
STRING_LITERAL(TMP628, "darkblue", 8);
STRING_LITERAL(TMP629, "darkcyan", 8);
STRING_LITERAL(TMP630, "darkgoldenrod", 13);
STRING_LITERAL(TMP631, "darkgray", 8);
STRING_LITERAL(TMP632, "darkgreen", 9);
STRING_LITERAL(TMP633, "darkkhaki", 9);
STRING_LITERAL(TMP634, "darkmagenta", 11);
STRING_LITERAL(TMP635, "darkolivegreen", 14);
STRING_LITERAL(TMP636, "darkorange", 10);
STRING_LITERAL(TMP637, "darkorchid", 10);
STRING_LITERAL(TMP638, "darkred", 7);
STRING_LITERAL(TMP639, "darksalmon", 10);
STRING_LITERAL(TMP640, "darkseagreen", 12);
STRING_LITERAL(TMP641, "darkslateblue", 13);
STRING_LITERAL(TMP642, "darkslategray", 13);
STRING_LITERAL(TMP643, "darkturquoise", 13);
STRING_LITERAL(TMP644, "darkviolet", 10);
STRING_LITERAL(TMP645, "deeppink", 8);
STRING_LITERAL(TMP646, "deepskyblue", 11);
STRING_LITERAL(TMP647, "dimgray", 7);
STRING_LITERAL(TMP648, "dodgerblue", 10);
STRING_LITERAL(TMP649, "firebrick", 9);
STRING_LITERAL(TMP650, "floralwhite", 11);
STRING_LITERAL(TMP651, "forestgreen", 11);
STRING_LITERAL(TMP652, "fuchsia", 7);
STRING_LITERAL(TMP653, "gainsboro", 9);
STRING_LITERAL(TMP654, "ghostwhite", 10);
STRING_LITERAL(TMP655, "gold", 4);
STRING_LITERAL(TMP656, "goldenrod", 9);
STRING_LITERAL(TMP657, "gray", 4);
STRING_LITERAL(TMP658, "green", 5);
STRING_LITERAL(TMP659, "greenyellow", 11);
STRING_LITERAL(TMP660, "honeydew", 8);
STRING_LITERAL(TMP661, "hotpink", 7);
STRING_LITERAL(TMP662, "indianred", 9);
STRING_LITERAL(TMP663, "indigo", 6);
STRING_LITERAL(TMP664, "ivory", 5);
STRING_LITERAL(TMP665, "khaki", 5);
STRING_LITERAL(TMP666, "lavender", 8);
STRING_LITERAL(TMP667, "lavenderblush", 13);
STRING_LITERAL(TMP668, "lawngreen", 9);
STRING_LITERAL(TMP669, "lemonchiffon", 12);
STRING_LITERAL(TMP670, "lightblue", 9);
STRING_LITERAL(TMP671, "lightcoral", 10);
STRING_LITERAL(TMP672, "lightcyan", 9);
STRING_LITERAL(TMP673, "lightgoldenrodyellow", 20);
STRING_LITERAL(TMP674, "lightgrey", 9);
STRING_LITERAL(TMP675, "lightgreen", 10);
STRING_LITERAL(TMP676, "lightpink", 9);
STRING_LITERAL(TMP677, "lightsalmon", 11);
STRING_LITERAL(TMP678, "lightseagreen", 13);
STRING_LITERAL(TMP679, "lightskyblue", 12);
STRING_LITERAL(TMP680, "lightslategray", 14);
STRING_LITERAL(TMP681, "lightsteelblue", 14);
STRING_LITERAL(TMP682, "lightyellow", 11);
STRING_LITERAL(TMP683, "lime", 4);
STRING_LITERAL(TMP684, "limegreen", 9);
STRING_LITERAL(TMP685, "linen", 5);
STRING_LITERAL(TMP686, "magenta", 7);
STRING_LITERAL(TMP687, "maroon", 6);
STRING_LITERAL(TMP688, "mediumaquamarine", 16);
STRING_LITERAL(TMP689, "mediumblue", 10);
STRING_LITERAL(TMP690, "mediumorchid", 12);
STRING_LITERAL(TMP691, "mediumpurple", 12);
STRING_LITERAL(TMP692, "mediumseagreen", 14);
STRING_LITERAL(TMP693, "mediumslateblue", 15);
STRING_LITERAL(TMP694, "mediumspringgreen", 17);
STRING_LITERAL(TMP695, "mediumturquoise", 15);
STRING_LITERAL(TMP696, "mediumvioletred", 15);
STRING_LITERAL(TMP697, "midnightblue", 12);
STRING_LITERAL(TMP698, "mintcream", 9);
STRING_LITERAL(TMP699, "mistyrose", 9);
STRING_LITERAL(TMP700, "moccasin", 8);
STRING_LITERAL(TMP701, "navajowhite", 11);
STRING_LITERAL(TMP702, "navy", 4);
STRING_LITERAL(TMP703, "oldlace", 7);
STRING_LITERAL(TMP704, "olive", 5);
STRING_LITERAL(TMP705, "olivedrab", 9);
STRING_LITERAL(TMP706, "orange", 6);
STRING_LITERAL(TMP707, "orangered", 9);
STRING_LITERAL(TMP708, "orchid", 6);
STRING_LITERAL(TMP709, "palegoldenrod", 13);
STRING_LITERAL(TMP710, "palegreen", 9);
STRING_LITERAL(TMP711, "paleturquoise", 13);
STRING_LITERAL(TMP712, "palevioletred", 13);
STRING_LITERAL(TMP713, "papayawhip", 10);
STRING_LITERAL(TMP714, "peachpuff", 9);
STRING_LITERAL(TMP715, "peru", 4);
STRING_LITERAL(TMP716, "pink", 4);
STRING_LITERAL(TMP717, "plum", 4);
STRING_LITERAL(TMP718, "powderblue", 10);
STRING_LITERAL(TMP719, "purple", 6);
STRING_LITERAL(TMP720, "red", 3);
STRING_LITERAL(TMP721, "rosybrown", 9);
STRING_LITERAL(TMP722, "royalblue", 9);
STRING_LITERAL(TMP723, "saddlebrown", 11);
STRING_LITERAL(TMP724, "salmon", 6);
STRING_LITERAL(TMP725, "sandybrown", 10);
STRING_LITERAL(TMP726, "seagreen", 8);
STRING_LITERAL(TMP727, "seashell", 8);
STRING_LITERAL(TMP728, "sienna", 6);
STRING_LITERAL(TMP729, "silver", 6);
STRING_LITERAL(TMP730, "skyblue", 7);
STRING_LITERAL(TMP731, "slateblue", 9);
STRING_LITERAL(TMP732, "slategray", 9);
STRING_LITERAL(TMP733, "snow", 4);
STRING_LITERAL(TMP734, "springgreen", 11);
STRING_LITERAL(TMP735, "steelblue", 9);
STRING_LITERAL(TMP736, "tan", 3);
STRING_LITERAL(TMP737, "teal", 4);
STRING_LITERAL(TMP738, "thistle", 7);
STRING_LITERAL(TMP739, "tomato", 6);
STRING_LITERAL(TMP740, "turquoise", 9);
STRING_LITERAL(TMP741, "violet", 6);
STRING_LITERAL(TMP742, "wheat", 5);
STRING_LITERAL(TMP743, "white", 5);
STRING_LITERAL(TMP744, "whitesmoke", 10);
STRING_LITERAL(TMP745, "yellow", 6);
STRING_LITERAL(TMP746, "yellowgreen", 11);
NIM_CONST TY240555 colornames_240554 = {{((NimStringDesc*) &TMP607),
15792383}
,
{((NimStringDesc*) &TMP608),
16444375}
,
{((NimStringDesc*) &TMP609),
65535}
,
{((NimStringDesc*) &TMP610),
8388564}
,
{((NimStringDesc*) &TMP611),
15794175}
,
{((NimStringDesc*) &TMP612),
16119260}
,
{((NimStringDesc*) &TMP613),
16770244}
,
{((NimStringDesc*) &TMP614),
0}
,
{((NimStringDesc*) &TMP615),
16772045}
,
{((NimStringDesc*) &TMP616),
255}
,
{((NimStringDesc*) &TMP617),
9055202}
,
{((NimStringDesc*) &TMP618),
10824234}
,
{((NimStringDesc*) &TMP619),
14596231}
,
{((NimStringDesc*) &TMP620),
6266528}
,
{((NimStringDesc*) &TMP621),
8388352}
,
{((NimStringDesc*) &TMP622),
13789470}
,
{((NimStringDesc*) &TMP623),
16744272}
,
{((NimStringDesc*) &TMP624),
6591981}
,
{((NimStringDesc*) &TMP625),
16775388}
,
{((NimStringDesc*) &TMP626),
14423100}
,
{((NimStringDesc*) &TMP627),
65535}
,
{((NimStringDesc*) &TMP628),
139}
,
{((NimStringDesc*) &TMP629),
35723}
,
{((NimStringDesc*) &TMP630),
12092939}
,
{((NimStringDesc*) &TMP631),
11119017}
,
{((NimStringDesc*) &TMP632),
25600}
,
{((NimStringDesc*) &TMP633),
12433259}
,
{((NimStringDesc*) &TMP634),
9109643}
,
{((NimStringDesc*) &TMP635),
5597999}
,
{((NimStringDesc*) &TMP636),
16747520}
,
{((NimStringDesc*) &TMP637),
10040012}
,
{((NimStringDesc*) &TMP638),
9109504}
,
{((NimStringDesc*) &TMP639),
15308410}
,
{((NimStringDesc*) &TMP640),
9419919}
,
{((NimStringDesc*) &TMP641),
4734347}
,
{((NimStringDesc*) &TMP642),
3100495}
,
{((NimStringDesc*) &TMP643),
52945}
,
{((NimStringDesc*) &TMP644),
9699539}
,
{((NimStringDesc*) &TMP645),
16716947}
,
{((NimStringDesc*) &TMP646),
49151}
,
{((NimStringDesc*) &TMP647),
6908265}
,
{((NimStringDesc*) &TMP648),
2003199}
,
{((NimStringDesc*) &TMP649),
11674146}
,
{((NimStringDesc*) &TMP650),
16775920}
,
{((NimStringDesc*) &TMP651),
2263842}
,
{((NimStringDesc*) &TMP652),
16711935}
,
{((NimStringDesc*) &TMP653),
14474460}
,
{((NimStringDesc*) &TMP654),
16316671}
,
{((NimStringDesc*) &TMP655),
16766720}
,
{((NimStringDesc*) &TMP656),
14329120}
,
{((NimStringDesc*) &TMP657),
8421504}
,
{((NimStringDesc*) &TMP658),
32768}
,
{((NimStringDesc*) &TMP659),
11403055}
,
{((NimStringDesc*) &TMP660),
15794160}
,
{((NimStringDesc*) &TMP661),
16738740}
,
{((NimStringDesc*) &TMP662),
13458524}
,
{((NimStringDesc*) &TMP663),
4915330}
,
{((NimStringDesc*) &TMP664),
16777200}
,
{((NimStringDesc*) &TMP665),
15787660}
,
{((NimStringDesc*) &TMP666),
15132410}
,
{((NimStringDesc*) &TMP667),
16773365}
,
{((NimStringDesc*) &TMP668),
8190976}
,
{((NimStringDesc*) &TMP669),
16775885}
,
{((NimStringDesc*) &TMP670),
11393254}
,
{((NimStringDesc*) &TMP671),
15761536}
,
{((NimStringDesc*) &TMP672),
14745599}
,
{((NimStringDesc*) &TMP673),
16448210}
,
{((NimStringDesc*) &TMP674),
13882323}
,
{((NimStringDesc*) &TMP675),
9498256}
,
{((NimStringDesc*) &TMP676),
16758465}
,
{((NimStringDesc*) &TMP677),
16752762}
,
{((NimStringDesc*) &TMP678),
2142890}
,
{((NimStringDesc*) &TMP679),
8900346}
,
{((NimStringDesc*) &TMP680),
7833753}
,
{((NimStringDesc*) &TMP681),
11584734}
,
{((NimStringDesc*) &TMP682),
16777184}
,
{((NimStringDesc*) &TMP683),
65280}
,
{((NimStringDesc*) &TMP684),
3329330}
,
{((NimStringDesc*) &TMP685),
16445670}
,
{((NimStringDesc*) &TMP686),
16711935}
,
{((NimStringDesc*) &TMP687),
8388608}
,
{((NimStringDesc*) &TMP688),
6737322}
,
{((NimStringDesc*) &TMP689),
205}
,
{((NimStringDesc*) &TMP690),
12211667}
,
{((NimStringDesc*) &TMP691),
9662680}
,
{((NimStringDesc*) &TMP692),
3978097}
,
{((NimStringDesc*) &TMP693),
8087790}
,
{((NimStringDesc*) &TMP694),
64154}
,
{((NimStringDesc*) &TMP695),
4772300}
,
{((NimStringDesc*) &TMP696),
13047173}
,
{((NimStringDesc*) &TMP697),
1644912}
,
{((NimStringDesc*) &TMP698),
16121850}
,
{((NimStringDesc*) &TMP699),
16770273}
,
{((NimStringDesc*) &TMP700),
16770229}
,
{((NimStringDesc*) &TMP701),
16768685}
,
{((NimStringDesc*) &TMP702),
128}
,
{((NimStringDesc*) &TMP703),
16643558}
,
{((NimStringDesc*) &TMP704),
8421376}
,
{((NimStringDesc*) &TMP705),
7048739}
,
{((NimStringDesc*) &TMP706),
16753920}
,
{((NimStringDesc*) &TMP707),
16729344}
,
{((NimStringDesc*) &TMP708),
14315734}
,
{((NimStringDesc*) &TMP709),
15657130}
,
{((NimStringDesc*) &TMP710),
10025880}
,
{((NimStringDesc*) &TMP711),
11529966}
,
{((NimStringDesc*) &TMP712),
14184595}
,
{((NimStringDesc*) &TMP713),
16773077}
,
{((NimStringDesc*) &TMP714),
16767673}
,
{((NimStringDesc*) &TMP715),
13468991}
,
{((NimStringDesc*) &TMP716),
16761035}
,
{((NimStringDesc*) &TMP717),
14524637}
,
{((NimStringDesc*) &TMP718),
11591910}
,
{((NimStringDesc*) &TMP719),
8388736}
,
{((NimStringDesc*) &TMP720),
16711680}
,
{((NimStringDesc*) &TMP721),
12357519}
,
{((NimStringDesc*) &TMP722),
4286945}
,
{((NimStringDesc*) &TMP723),
9127187}
,
{((NimStringDesc*) &TMP724),
16416882}
,
{((NimStringDesc*) &TMP725),
16032864}
,
{((NimStringDesc*) &TMP726),
3050327}
,
{((NimStringDesc*) &TMP727),
16774638}
,
{((NimStringDesc*) &TMP728),
10506797}
,
{((NimStringDesc*) &TMP729),
12632256}
,
{((NimStringDesc*) &TMP730),
8900331}
,
{((NimStringDesc*) &TMP731),
6970061}
,
{((NimStringDesc*) &TMP732),
7372944}
,
{((NimStringDesc*) &TMP733),
16775930}
,
{((NimStringDesc*) &TMP734),
65407}
,
{((NimStringDesc*) &TMP735),
4620980}
,
{((NimStringDesc*) &TMP736),
13808780}
,
{((NimStringDesc*) &TMP737),
32896}
,
{((NimStringDesc*) &TMP738),
14204888}
,
{((NimStringDesc*) &TMP739),
16737095}
,
{((NimStringDesc*) &TMP740),
4251856}
,
{((NimStringDesc*) &TMP741),
15631086}
,
{((NimStringDesc*) &TMP742),
16113331}
,
{((NimStringDesc*) &TMP743),
16777215}
,
{((NimStringDesc*) &TMP744),
16119285}
,
{((NimStringDesc*) &TMP745),
16776960}
,
{((NimStringDesc*) &TMP746),
10145074}
}
;
NIM_CONST TY240555 TMP762 = {{((NimStringDesc*) &TMP607),
15792383}
,
{((NimStringDesc*) &TMP608),
16444375}
,
{((NimStringDesc*) &TMP609),
65535}
,
{((NimStringDesc*) &TMP610),
8388564}
,
{((NimStringDesc*) &TMP611),
15794175}
,
{((NimStringDesc*) &TMP612),
16119260}
,
{((NimStringDesc*) &TMP613),
16770244}
,
{((NimStringDesc*) &TMP614),
0}
,
{((NimStringDesc*) &TMP615),
16772045}
,
{((NimStringDesc*) &TMP616),
255}
,
{((NimStringDesc*) &TMP617),
9055202}
,
{((NimStringDesc*) &TMP618),
10824234}
,
{((NimStringDesc*) &TMP619),
14596231}
,
{((NimStringDesc*) &TMP620),
6266528}
,
{((NimStringDesc*) &TMP621),
8388352}
,
{((NimStringDesc*) &TMP622),
13789470}
,
{((NimStringDesc*) &TMP623),
16744272}
,
{((NimStringDesc*) &TMP624),
6591981}
,
{((NimStringDesc*) &TMP625),
16775388}
,
{((NimStringDesc*) &TMP626),
14423100}
,
{((NimStringDesc*) &TMP627),
65535}
,
{((NimStringDesc*) &TMP628),
139}
,
{((NimStringDesc*) &TMP629),
35723}
,
{((NimStringDesc*) &TMP630),
12092939}
,
{((NimStringDesc*) &TMP631),
11119017}
,
{((NimStringDesc*) &TMP632),
25600}
,
{((NimStringDesc*) &TMP633),
12433259}
,
{((NimStringDesc*) &TMP634),
9109643}
,
{((NimStringDesc*) &TMP635),
5597999}
,
{((NimStringDesc*) &TMP636),
16747520}
,
{((NimStringDesc*) &TMP637),
10040012}
,
{((NimStringDesc*) &TMP638),
9109504}
,
{((NimStringDesc*) &TMP639),
15308410}
,
{((NimStringDesc*) &TMP640),
9419919}
,
{((NimStringDesc*) &TMP641),
4734347}
,
{((NimStringDesc*) &TMP642),
3100495}
,
{((NimStringDesc*) &TMP643),
52945}
,
{((NimStringDesc*) &TMP644),
9699539}
,
{((NimStringDesc*) &TMP645),
16716947}
,
{((NimStringDesc*) &TMP646),
49151}
,
{((NimStringDesc*) &TMP647),
6908265}
,
{((NimStringDesc*) &TMP648),
2003199}
,
{((NimStringDesc*) &TMP649),
11674146}
,
{((NimStringDesc*) &TMP650),
16775920}
,
{((NimStringDesc*) &TMP651),
2263842}
,
{((NimStringDesc*) &TMP652),
16711935}
,
{((NimStringDesc*) &TMP653),
14474460}
,
{((NimStringDesc*) &TMP654),
16316671}
,
{((NimStringDesc*) &TMP655),
16766720}
,
{((NimStringDesc*) &TMP656),
14329120}
,
{((NimStringDesc*) &TMP657),
8421504}
,
{((NimStringDesc*) &TMP658),
32768}
,
{((NimStringDesc*) &TMP659),
11403055}
,
{((NimStringDesc*) &TMP660),
15794160}
,
{((NimStringDesc*) &TMP661),
16738740}
,
{((NimStringDesc*) &TMP662),
13458524}
,
{((NimStringDesc*) &TMP663),
4915330}
,
{((NimStringDesc*) &TMP664),
16777200}
,
{((NimStringDesc*) &TMP665),
15787660}
,
{((NimStringDesc*) &TMP666),
15132410}
,
{((NimStringDesc*) &TMP667),
16773365}
,
{((NimStringDesc*) &TMP668),
8190976}
,
{((NimStringDesc*) &TMP669),
16775885}
,
{((NimStringDesc*) &TMP670),
11393254}
,
{((NimStringDesc*) &TMP671),
15761536}
,
{((NimStringDesc*) &TMP672),
14745599}
,
{((NimStringDesc*) &TMP673),
16448210}
,
{((NimStringDesc*) &TMP674),
13882323}
,
{((NimStringDesc*) &TMP675),
9498256}
,
{((NimStringDesc*) &TMP676),
16758465}
,
{((NimStringDesc*) &TMP677),
16752762}
,
{((NimStringDesc*) &TMP678),
2142890}
,
{((NimStringDesc*) &TMP679),
8900346}
,
{((NimStringDesc*) &TMP680),
7833753}
,
{((NimStringDesc*) &TMP681),
11584734}
,
{((NimStringDesc*) &TMP682),
16777184}
,
{((NimStringDesc*) &TMP683),
65280}
,
{((NimStringDesc*) &TMP684),
3329330}
,
{((NimStringDesc*) &TMP685),
16445670}
,
{((NimStringDesc*) &TMP686),
16711935}
,
{((NimStringDesc*) &TMP687),
8388608}
,
{((NimStringDesc*) &TMP688),
6737322}
,
{((NimStringDesc*) &TMP689),
205}
,
{((NimStringDesc*) &TMP690),
12211667}
,
{((NimStringDesc*) &TMP691),
9662680}
,
{((NimStringDesc*) &TMP692),
3978097}
,
{((NimStringDesc*) &TMP693),
8087790}
,
{((NimStringDesc*) &TMP694),
64154}
,
{((NimStringDesc*) &TMP695),
4772300}
,
{((NimStringDesc*) &TMP696),
13047173}
,
{((NimStringDesc*) &TMP697),
1644912}
,
{((NimStringDesc*) &TMP698),
16121850}
,
{((NimStringDesc*) &TMP699),
16770273}
,
{((NimStringDesc*) &TMP700),
16770229}
,
{((NimStringDesc*) &TMP701),
16768685}
,
{((NimStringDesc*) &TMP702),
128}
,
{((NimStringDesc*) &TMP703),
16643558}
,
{((NimStringDesc*) &TMP704),
8421376}
,
{((NimStringDesc*) &TMP705),
7048739}
,
{((NimStringDesc*) &TMP706),
16753920}
,
{((NimStringDesc*) &TMP707),
16729344}
,
{((NimStringDesc*) &TMP708),
14315734}
,
{((NimStringDesc*) &TMP709),
15657130}
,
{((NimStringDesc*) &TMP710),
10025880}
,
{((NimStringDesc*) &TMP711),
11529966}
,
{((NimStringDesc*) &TMP712),
14184595}
,
{((NimStringDesc*) &TMP713),
16773077}
,
{((NimStringDesc*) &TMP714),
16767673}
,
{((NimStringDesc*) &TMP715),
13468991}
,
{((NimStringDesc*) &TMP716),
16761035}
,
{((NimStringDesc*) &TMP717),
14524637}
,
{((NimStringDesc*) &TMP718),
11591910}
,
{((NimStringDesc*) &TMP719),
8388736}
,
{((NimStringDesc*) &TMP720),
16711680}
,
{((NimStringDesc*) &TMP721),
12357519}
,
{((NimStringDesc*) &TMP722),
4286945}
,
{((NimStringDesc*) &TMP723),
9127187}
,
{((NimStringDesc*) &TMP724),
16416882}
,
{((NimStringDesc*) &TMP725),
16032864}
,
{((NimStringDesc*) &TMP726),
3050327}
,
{((NimStringDesc*) &TMP727),
16774638}
,
{((NimStringDesc*) &TMP728),
10506797}
,
{((NimStringDesc*) &TMP729),
12632256}
,
{((NimStringDesc*) &TMP730),
8900331}
,
{((NimStringDesc*) &TMP731),
6970061}
,
{((NimStringDesc*) &TMP732),
7372944}
,
{((NimStringDesc*) &TMP733),
16775930}
,
{((NimStringDesc*) &TMP734),
65407}
,
{((NimStringDesc*) &TMP735),
4620980}
,
{((NimStringDesc*) &TMP736),
13808780}
,
{((NimStringDesc*) &TMP737),
32896}
,
{((NimStringDesc*) &TMP738),
14204888}
,
{((NimStringDesc*) &TMP739),
16737095}
,
{((NimStringDesc*) &TMP740),
4251856}
,
{((NimStringDesc*) &TMP741),
15631086}
,
{((NimStringDesc*) &TMP742),
16113331}
,
{((NimStringDesc*) &TMP743),
16777215}
,
{((NimStringDesc*) &TMP744),
16119285}
,
{((NimStringDesc*) &TMP745),
16776960}
,
{((NimStringDesc*) &TMP746),
10145074}
}
;
STRING_LITERAL(TMP763, "unkown color: ", 14);
extern TFrame* frameptr_16242;
extern TNimType NTI21601; /* ref ValueError */
extern TNimType NTI3249; /* ValueError */
extern tgcheap47016 gch_47044;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(NI, satplus_240065)(NI a, NI b) {
	NI result;
	nimfr("satPlus", "colors.nim")
	result = 0;
	nimln(36, "colors.nim");
	nimln(36, "colors.nim");
	result = (NI)((NU64)(a) + (NU64)(b));
	nimln(37, "colors.nim");
	{
		nimln(37, "colors.nim");
		if (!(255 < result)) goto LA3;
		nimln(37, "colors.nim");
		result = 255;
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(NI, satminus_240088)(NI a, NI b) {
	NI result;
	nimfr("satMinus", "colors.nim")
	result = 0;
	nimln(40, "colors.nim");
	nimln(40, "colors.nim");
	result = (NI)((NU64)(a) - (NU64)(b));
	nimln(41, "colors.nim");
	{
		nimln(41, "colors.nim");
		if (!(result < 0)) goto LA3;
		nimln(41, "colors.nim");
		result = 0;
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, HEX2B_240109)(NI a, NI b) {
	NI result;
	NI ar;
	NI ag;
	NI ab;
	NI br;
	NI bg;
	NI bb;
	NI LOC1;
	NI LOC2;
	NI LOC3;
	nimfr("+", "colors.nim")
	result = 0;
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	ar = (NI)((NI)((NU64)(a) >> (NU64)(16)) & 255);
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	ag = (NI)((NI)((NU64)(a) >> (NU64)(8)) & 255);
	nimln(25, "colors.nim");
	nimln(25, "colors.nim");
	ab = (NI)(a & 255);
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	br = (NI)((NI)((NU64)(b) >> (NU64)(16)) & 255);
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	bg = (NI)((NI)((NU64)(b) >> (NU64)(8)) & 255);
	nimln(25, "colors.nim");
	nimln(25, "colors.nim");
	bb = (NI)(b & 255);
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	LOC1 = 0;
	LOC1 = satplus_240065(((NI) (ar)), ((NI) (br)));
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	LOC2 = 0;
	LOC2 = satplus_240065(((NI) (ag)), ((NI) (bg)));
	nimln(33, "colors.nim");
	LOC3 = 0;
	LOC3 = satplus_240065(((NI) (ab)), ((NI) (bb)));
	result = (NI)((NI)((NI)((NU64)(LOC1) << (NU64)(16)) | (NI)((NU64)(LOC2) << (NU64)(8))) | LOC3);
	popFrame();
	return result;
}

N_NIMCALL(NI, HEX2D_240145)(NI a, NI b) {
	NI result;
	NI ar;
	NI ag;
	NI ab;
	NI br;
	NI bg;
	NI bb;
	NI LOC1;
	NI LOC2;
	NI LOC3;
	nimfr("-", "colors.nim")
	result = 0;
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	ar = (NI)((NI)((NU64)(a) >> (NU64)(16)) & 255);
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	ag = (NI)((NI)((NU64)(a) >> (NU64)(8)) & 255);
	nimln(25, "colors.nim");
	nimln(25, "colors.nim");
	ab = (NI)(a & 255);
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	br = (NI)((NI)((NU64)(b) >> (NU64)(16)) & 255);
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	bg = (NI)((NI)((NU64)(b) >> (NU64)(8)) & 255);
	nimln(25, "colors.nim");
	nimln(25, "colors.nim");
	bb = (NI)(b & 255);
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	LOC1 = 0;
	LOC1 = satminus_240088(((NI) (ar)), ((NI) (br)));
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	LOC2 = 0;
	LOC2 = satminus_240088(((NI) (ag)), ((NI) (bg)));
	nimln(33, "colors.nim");
	LOC3 = 0;
	LOC3 = satminus_240088(((NI) (ab)), ((NI) (bb)));
	result = (NI)((NI)((NI)((NU64)(LOC1) << (NU64)(16)) | (NI)((NU64)(LOC2) << (NU64)(8))) | LOC3);
	popFrame();
	return result;
}

N_NIMCALL(TY240184, extractrgb_240181)(NI a) {
	TY240184 result;
	nimfr("extractRGB", "colors.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(55, "colors.nim");
	nimln(55, "colors.nim");
	nimln(55, "colors.nim");
	result.Field0 = (NI)((NI)((NU64)(a) >> (NU64)(16)) & 255);
	nimln(56, "colors.nim");
	nimln(56, "colors.nim");
	nimln(56, "colors.nim");
	result.Field1 = (NI)((NI)((NU64)(a) >> (NU64)(8)) & 255);
	nimln(57, "colors.nim");
	nimln(57, "colors.nim");
	result.Field2 = (NI)(a & 255);
	popFrame();
	return result;
}

N_NIMCALL(NI, intensity_240206)(NI a, NF f) {
	NI result;
	NI r;
	NI g;
	NI b;
	nimfr("intensity", "colors.nim")
	result = 0;
	nimln(62, "colors.nim");
	nimln(62, "colors.nim");
	nimln(62, "colors.nim");
	nimln(62, "colors.nim");
	nimln(62, "colors.nim");
	nimln(62, "colors.nim");
	r = float64ToInt32(((NF)(((double) (((NI) ((NI)((NI)((NU64)(a) >> (NU64)(16)) & 255)))))) * (NF)(f)));
	nimln(63, "colors.nim");
	nimln(63, "colors.nim");
	nimln(63, "colors.nim");
	nimln(63, "colors.nim");
	nimln(63, "colors.nim");
	nimln(63, "colors.nim");
	g = float64ToInt32(((NF)(((double) (((NI) ((NI)((NI)((NU64)(a) >> (NU64)(8)) & 255)))))) * (NF)(f)));
	nimln(64, "colors.nim");
	nimln(64, "colors.nim");
	nimln(64, "colors.nim");
	nimln(64, "colors.nim");
	nimln(64, "colors.nim");
	b = float64ToInt32(((NF)(((double) (((NI) ((NI)(a & 255)))))) * (NF)(f)));
	nimln(65, "colors.nim");
	{
		nimln(65, "colors.nim");
		if (!((NU64)(255) < (NU64)(r))) goto LA3;
		nimln(65, "colors.nim");
		r = 255;
	}
	LA3: ;
	nimln(66, "colors.nim");
	{
		nimln(66, "colors.nim");
		if (!((NU64)(255) < (NU64)(g))) goto LA7;
		nimln(66, "colors.nim");
		g = 255;
	}
	LA7: ;
	nimln(67, "colors.nim");
	{
		nimln(67, "colors.nim");
		if (!((NU64)(255) < (NU64)(b))) goto LA11;
		nimln(67, "colors.nim");
		b = 255;
	}
	LA11: ;
	nimln(68, "colors.nim");
	nimln(68, "colors.nim");
	nimln(68, "colors.nim");
	nimln(68, "colors.nim");
	nimln(68, "colors.nim");
	result = (NI)((NI)((NI)((NU64)(r) << (NU64)(16)) | (NI)((NU64)(g) << (NU64)(8))) | b);
	popFrame();
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, HEX24_240700)(NI c) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	nimfr("$", "colors.nim")
	result = 0;
	nimln(374, "colors.nim");
	nimln(374, "colors.nim");
	LOC1 = 0;
	nimln(374, "colors.nim");
	LOC2 = 0;
	LOC2 = nsuToHex(((NI64) (c)), 6);
	LOC1 = rawNewString(LOC2->Sup.len + 1);
appendChar(LOC1, 35);
appendString(LOC1, LOC2);
	result = LOC1;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI64)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, binarystrsearch_240712)(TY240556* x, NI xLen0, NimStringDesc* y) {
	NI result;
	NI a;
	NI b;
	NI TMP750;
	nimfr("binaryStrSearch", "colors.nim")
	result = 0;
	nimln(378, "colors.nim");
	a = 0;
	nimln(379, "colors.nim");
	nimln(379, "colors.nim");
	nimln(379, "colors.nim");
	TMP750 = subInt(xLen0, 1);
	b = (NI64)(TMP750);
	{
		nimln(380, "colors.nim");
		while (1) {
			NI mid;
			NI TMP751;
			NI TMP752;
			NI c;
			nimln(380, "colors.nim");
			if (!(a <= b)) goto LA2;
			nimln(381, "colors.nim");
			nimln(381, "colors.nim");
			nimln(381, "colors.nim");
			TMP751 = addInt(a, b);
			TMP752 = divInt((NI64)(TMP751), 2);
			mid = (NI64)(TMP752);
			nimln(382, "colors.nim");
			if ((NU)(mid) >= (NU)(xLen0)) raiseIndexError();
			c = cmp_4517(x[mid].Field0, y);
			nimln(383, "colors.nim");
			{
				NI TMP753;
				nimln(383, "colors.nim");
				if (!(c < 0)) goto LA5;
				nimln(383, "colors.nim");
				nimln(383, "colors.nim");
				TMP753 = addInt(mid, 1);
				a = (NI64)(TMP753);
			}
			goto LA3;
			LA5: ;
			{
				NI TMP754;
				nimln(384, "colors.nim");
				if (!(0 < c)) goto LA8;
				nimln(384, "colors.nim");
				nimln(384, "colors.nim");
				TMP754 = subInt(mid, 1);
				b = (NI64)(TMP754);
			}
			goto LA3;
			LA8: ;
			{
				nimln(385, "colors.nim");
				nimln(385, "colors.nim");
				result = mid;
				goto BeforeRet;
			}
			LA3: ;
		} LA2: ;
	}
	nimln(386, "colors.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(tcell44933*, usrtocell_48646)(void* usr) {
	tcell44933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell44933*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell44933))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50204)(tcell44933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell44933* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48646(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell44933* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48646((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50204(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, parsecolor_240747)(NimStringDesc* name) {
	NI result;
	nimfr("parseColor", "colors.nim")
	result = 0;
	nimln(391, "colors.nim");
	{
		nimln(391, "colors.nim");
		if ((NU)(0) > (NU)(name->Sup.len)) raiseIndexError();
		if (!((NU8)(name->data[0]) == (NU8)(35))) goto LA3;
		nimln(392, "colors.nim");
		nimln(392, "colors.nim");
		result = nsuParseHexInt(name);
	}
	goto LA1;
	LA3: ;
	{
		NI idx;
		nimln(394, "colors.nim");
		idx = binarystrsearch_240712(TMP762, 140, name);
		nimln(395, "colors.nim");
		{
			valueerror3249* e_240755;
			NimStringDesc* LOC10;
			nimln(395, "colors.nim");
			if (!(idx < 0)) goto LA8;
			e_240755 = 0;
			nimln(2149, "system.nim");
			e_240755 = (valueerror3249*) newObj((&NTI21601), sizeof(valueerror3249));
			(*e_240755).Sup.Sup.m_type = (&NTI3249);
			nimln(2150, "system.nim");
			nimln(395, "colors.nim");
			LOC10 = 0;
			LOC10 = rawNewString(name->Sup.len + 14);
appendString(LOC10, ((NimStringDesc*) &TMP763));
appendString(LOC10, name);
			asgnRefNoCycle((void**) (&(*e_240755).Sup.message), LOC10);
			nimln(395, "colors.nim");
			raiseException((Exception*)e_240755, "ValueError");
		}
		LA8: ;
		nimln(396, "colors.nim");
		if ((NU)(idx) > (NU)(139)) raiseIndexError();
		result = colornames_240554[(idx)- 0].Field1;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, iscolor_240781)(NimStringDesc* name) {
	NIM_BOOL result;
	nimfr("isColor", "colors.nim")
	result = 0;
	nimln(401, "colors.nim");
	{
		nimln(401, "colors.nim");
		if ((NU)(0) > (NU)(name->Sup.len)) raiseIndexError();
		if (!((NU8)(name->data[0]) == (NU8)(35))) goto LA3;
		{
			NI i_240795;
			NI HEX3Atmp_240811;
			NI TMP764;
			NI res_240814;
			i_240795 = 0;
			HEX3Atmp_240811 = 0;
			nimln(402, "colors.nim");
			nimln(402, "colors.nim");
			nimln(402, "colors.nim");
			TMP764 = subInt(name->Sup.len, 1);
			HEX3Atmp_240811 = (NI64)(TMP764);
			nimln(1576, "system.nim");
			res_240814 = 1;
			{
				nimln(1577, "system.nim");
				while (1) {
					nimln(1577, "system.nim");
					if (!(res_240814 <= HEX3Atmp_240811)) goto LA7;
					nimln(1576, "system.nim");
					i_240795 = res_240814;
					nimln(403, "colors.nim");
					{
						nimln(403, "colors.nim");
						nimln(403, "colors.nim");
						if ((NU)(i_240795) > (NU)(name->Sup.len)) raiseIndexError();
						if (!!((((NU8)(name->data[i_240795])) >= ((NU8)(48)) && ((NU8)(name->data[i_240795])) <= ((NU8)(57)) || ((NU8)(name->data[i_240795])) >= ((NU8)(97)) && ((NU8)(name->data[i_240795])) <= ((NU8)(102)) || ((NU8)(name->data[i_240795])) >= ((NU8)(65)) && ((NU8)(name->data[i_240795])) <= ((NU8)(70))))) goto LA10;
						nimln(403, "colors.nim");
						nimln(403, "colors.nim");
						result = NIM_FALSE;
						goto BeforeRet;
					}
					LA10: ;
					nimln(1579, "system.nim");
					res_240814 = addInt(res_240814, 1);
				} LA7: ;
			}
		}
		nimln(404, "colors.nim");
		result = NIM_TRUE;
	}
	goto LA1;
	LA3: ;
	{
		NI LOC13;
		nimln(406, "colors.nim");
		nimln(406, "colors.nim");
		nimln(406, "colors.nim");
		LOC13 = 0;
		LOC13 = binarystrsearch_240712(TMP762, 140, name);
		result = (0 <= LOC13);
	}
	LA1: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, rgb_240831)(NI r, NI g, NI b) {
	NI result;
	nimfr("rgb", "colors.nim")
	result = 0;
	nimln(410, "colors.nim");
	nimln(410, "colors.nim");
	nimln(410, "colors.nim");
	nimln(410, "colors.nim");
	nimln(410, "colors.nim");
	result = (NI)((NI)((NI)((NU64)(((NI) (r))) << (NU64)(16)) | (NI)((NU64)(((NI) (g))) << (NU64)(8))) | ((NI) (b)));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_colorsInit)(void) {
	nimfr("colors", "colors.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_colorsDatInit)(void) {
}

