/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\simon\rationalnes_\rnes\src\nimcache\stdlib_times.o c:\users\simon\rationalnes_\rnes\src\nimcache\stdlib_times.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <time.h>

#include <string.h>
typedef struct timeinterval105407 timeinterval105407;
typedef struct timeinfo105405 timeinfo105405;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY105550 TY105550;
typedef struct tfiletime102076 tfiletime102076;
typedef struct slice86066 slice86066;
typedef struct valueerror3249 valueerror3249;
typedef struct Exception Exception;
typedef struct tcell44933 tcell44933;
typedef struct tcellseq44949 tcellseq44949;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellset44945 tcellset44945;
typedef struct tpagedesc44941 tpagedesc44941;
typedef struct tmemregion27210 tmemregion27210;
typedef struct tsmallchunk26440 tsmallchunk26440;
typedef struct tllchunk27204 tllchunk27204;
typedef struct tbigchunk26442 tbigchunk26442;
typedef struct tintset26417 tintset26417;
typedef struct ttrunk26413 ttrunk26413;
typedef struct tavlnode27208 tavlnode27208;
typedef struct tgcstat47014 tgcstat47014;
typedef struct tbasechunk26438 tbasechunk26438;
typedef struct tfreecell26430 tfreecell26430;
struct  timeinterval105407  {
NI Miliseconds;
NI Seconds;
NI Minutes;
NI Hours;
NI Days;
NI Months;
NI Years;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  timeinfo105405  {
  TNimObject Sup;
NI Second;
NI Minute;
NI Hour;
NI Monthday;
NU8 Month;
NI Year;
NU8 Weekday;
NI Yearday;
NIM_BOOL Isdst;
NimStringDesc* Tzname;
NI Timezone;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY106054[7];
struct TY105550 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NI8 TY106075[7];
struct  tfiletime102076  {
NI32 Dwlowdatetime;
NI32 Dwhighdatetime;
};
typedef N_STDCALL_PTR(void, TY103425) (tfiletime102076* lpsystemtimeasfiletime);
typedef NimStringDesc* TY107239[7];
typedef NimStringDesc* TY107255[12];
struct  slice86066  {
NI A;
NI B;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  valueerror3249  {
  Exception Sup;
};
struct  tcell44933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq44949  {
NI Len;
NI Cap;
tcell44933** D;
};
struct  tcellset44945  {
NI Counter;
NI Max;
tpagedesc44941* Head;
tpagedesc44941** Data;
};
typedef tsmallchunk26440* TY27222[512];
typedef ttrunk26413* ttrunkbuckets26415[256];
struct  tintset26417  {
ttrunkbuckets26415 Data;
};
struct  tmemregion27210  {
NI Minlargeobj;
NI Maxlargeobj;
TY27222 Freesmallchunks;
tllchunk27204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26442* Freechunkslist;
tintset26417 Chunkstarts;
tavlnode27208* Root;
tavlnode27208* Deleted;
tavlnode27208* Last;
tavlnode27208* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44949 Zct;
tcellseq44949 Decstack;
tcellset44945 Cycleroots;
tcellseq44949 Tempstack;
NI Recgclock;
tmemregion27210 Region;
tgcstat47014 Stat;
};
typedef NI TY26420[8];
struct  tpagedesc44941  {
tpagedesc44941* Next;
NI Key;
TY26420 Bits;
};
struct  tbasechunk26438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26440  {
  tbasechunk26438 Sup;
tsmallchunk26440* Next;
tsmallchunk26440* Prev;
tfreecell26430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27204  {
NI Size;
NI Acc;
tllchunk27204* Next;
};
struct  tbigchunk26442  {
  tbasechunk26438 Sup;
tbigchunk26442* Next;
tbigchunk26442* Prev;
NI Align;
NF Data;
};
struct  ttrunk26413  {
ttrunk26413* Next;
NI Key;
TY26420 Bits;
};
typedef tavlnode27208* TY27214[2];
struct  tavlnode27208  {
TY27214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26430  {
tfreecell26430* Next;
NI Zerofield;
};
N_NIMCALL(time_t, fromseconds_105477)(NI64 since1970);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b);
N_NIMCALL(timeinterval105407, initinterval_105614)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years);
N_NIMCALL(NIM_BOOL, isleapyear_105630)(NI year);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NI, getdaysinmonth_105645)(NU8 month, NI year);
static N_INLINE(void, HEX2BHEX3D_105693)(NF* x_105699, NF y_105702);
N_NIMCALL(NF, toseconds_105658)(timeinfo105405* a, timeinterval105407* interval);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NF, HEX2F_86004)(NI x, NI y);
N_NIMCALL(void, HEX2B_105833)(timeinfo105405* a, timeinterval105407* interval, timeinfo105405* Result);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, HEX2D_105846)(timeinfo105405* a, timeinterval105407* interval, timeinfo105405* Result);
N_NIMCALL(void, tmtotimeinfo_106048)(struct tm* tm, NIM_BOOL local, timeinfo105405* Result);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, gettzname_105548)(TY105550* Result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, gettimezone_105604)(void);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(struct tm, timeinfototm_106070)(timeinfo105405* t);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b);
N_NIMCALL(NI, getstartmilsecs_105609)(void);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NIMCALL(time_t, gettime_105448)(void);
N_NIMCALL(void, getlocaltime_105453)(time_t t, timeinfo105405* Result);
N_NIMCALL(void, getgmtime_105459)(time_t t, timeinfo105405* Result);
N_NIMCALL(time_t, timeinfototime_105465)(timeinfo105405* timeinfo);
N_NIMCALL(NimStringDesc*, tostringtillnl_106637)(NCSTRING p);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, HEX24_105494)(timeinfo105405* timeinfo);
N_NIMCALL(NimStringDesc*, HEX24_105500)(time_t time);
N_NIMCALL(NI64, unixtimetowintime_106683)(time_t t);
N_NIMCALL(NI64, mulInt64)(NI64 a, NI64 b);
static N_INLINE(NI64, addInt64)(NI64 a, NI64 b);
N_NIMCALL(time_t, wintimetounixtime_106691)(NI64 t);
static N_INLINE(NI64, subInt64)(NI64 a, NI64 b);
static N_INLINE(NI64, divInt64)(NI64 a, NI64 b);
N_NIMCALL(NI64, chckRange64)(NI64 i, NI64 a, NI64 b);
N_NIMCALL(time_t, fromseconds_105471)(NF since1970);
N_NIMCALL(NF, toseconds_105488)(time_t time);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NI64, rdfiletime_103404)(tfiletime102076 f);
static N_INLINE(NI64, modInt64)(NI64 a, NI64 b);
N_NIMCALL(NF, ntcpuTime)(void);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_NIMCALL(NimStringDesc*, HEX24_107234)(NU8 day);
N_NIMCALL(NimStringDesc*, HEX24_107250)(NU8 m);
N_NIMCALL(void, formattoken_107266)(timeinfo105405* info, NimStringDesc* token, NimStringDesc** buf);
N_NIMCALL(NI, hashString)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_86059)(NimStringDesc* s, slice86066 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_74828, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(slice86066, HEX2EHEX2E_93099)(NI a_93103, NI b_93105);
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NI count, NIM_CHAR c);
N_NIMCALL(void, insert_87801)(NimStringDesc** x, NimStringDesc* item, NI i);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell44933*, usrtocell_48646)(void* usr);
static N_INLINE(void, rtladdzct_50204)(tcell44933* c);
N_NOINLINE(void, addzct_48617)(tcellseq44949* s, tcell44933* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, format_107421)(timeinfo105405* info, NimStringDesc* f);
STRING_LITERAL(TMP172, "UTC", 3);
NIM_CONST TY106054 weekdays_106053 = {((NU8) 6),
((NU8) 0),
((NU8) 1),
((NU8) 2),
((NU8) 3),
((NU8) 4),
((NU8) 5)}
;
NIM_CONST TY106075 weekdays_106074 = {((NI8) 1),
((NI8) 2),
((NI8) 3),
((NI8) 4),
((NI8) 5),
((NI8) 6),
((NI8) 0)}
;
STRING_LITERAL(TMP177, "", 0);
STRING_LITERAL(TMP187, "Monday", 6);
STRING_LITERAL(TMP188, "Tuesday", 7);
STRING_LITERAL(TMP189, "Wednesday", 9);
STRING_LITERAL(TMP190, "Thursday", 8);
STRING_LITERAL(TMP191, "Friday", 6);
STRING_LITERAL(TMP192, "Saturday", 8);
STRING_LITERAL(TMP193, "Sunday", 6);
NIM_CONST TY107239 lookup_107238 = {((NimStringDesc*) &TMP187),
((NimStringDesc*) &TMP188),
((NimStringDesc*) &TMP189),
((NimStringDesc*) &TMP190),
((NimStringDesc*) &TMP191),
((NimStringDesc*) &TMP192),
((NimStringDesc*) &TMP193)}
;
STRING_LITERAL(TMP194, "January", 7);
STRING_LITERAL(TMP195, "February", 8);
STRING_LITERAL(TMP196, "March", 5);
STRING_LITERAL(TMP197, "April", 5);
STRING_LITERAL(TMP198, "May", 3);
STRING_LITERAL(TMP199, "June", 4);
STRING_LITERAL(TMP200, "July", 4);
STRING_LITERAL(TMP201, "August", 6);
STRING_LITERAL(TMP202, "September", 9);
STRING_LITERAL(TMP203, "October", 7);
STRING_LITERAL(TMP204, "November", 8);
STRING_LITERAL(TMP205, "December", 8);
NIM_CONST TY107255 lookup_107254 = {((NimStringDesc*) &TMP194),
((NimStringDesc*) &TMP195),
((NimStringDesc*) &TMP196),
((NimStringDesc*) &TMP197),
((NimStringDesc*) &TMP198),
((NimStringDesc*) &TMP199),
((NimStringDesc*) &TMP200),
((NimStringDesc*) &TMP201),
((NimStringDesc*) &TMP202),
((NimStringDesc*) &TMP203),
((NimStringDesc*) &TMP204),
((NimStringDesc*) &TMP205)}
;
STRING_LITERAL(TMP206, "d", 1);
STRING_LITERAL(TMP207, "dd", 2);
STRING_LITERAL(TMP208, "ddd", 3);
STRING_LITERAL(TMP209, "dddd", 4);
STRING_LITERAL(TMP210, "h", 1);
STRING_LITERAL(TMP211, "hh", 2);
STRING_LITERAL(TMP212, "H", 1);
STRING_LITERAL(TMP213, "HH", 2);
STRING_LITERAL(TMP214, "m", 1);
STRING_LITERAL(TMP215, "mm", 2);
STRING_LITERAL(TMP216, "M", 1);
STRING_LITERAL(TMP217, "MM", 2);
STRING_LITERAL(TMP218, "MMM", 3);
STRING_LITERAL(TMP219, "MMMM", 4);
STRING_LITERAL(TMP220, "s", 1);
STRING_LITERAL(TMP221, "ss", 2);
STRING_LITERAL(TMP222, "t", 1);
STRING_LITERAL(TMP223, "tt", 2);
STRING_LITERAL(TMP224, "y", 1);
STRING_LITERAL(TMP225, "yy", 2);
STRING_LITERAL(TMP226, "yyy", 3);
STRING_LITERAL(TMP227, "yyyy", 4);
STRING_LITERAL(TMP228, "yyyyy", 5);
STRING_LITERAL(TMP229, "z", 1);
STRING_LITERAL(TMP230, "zz", 2);
STRING_LITERAL(TMP231, "zzz", 3);
STRING_LITERAL(TMP232, "ZZZ", 3);
STRING_LITERAL(TMP233, "0", 1);
STRING_LITERAL(TMP240, "PM", 2);
STRING_LITERAL(TMP241, "AM", 2);
STRING_LITERAL(TMP265, ":00", 3);
STRING_LITERAL(TMP268, "Invalid format string: ", 23);
extern TFrame* frameptr_16242;
extern TNimType NTI3211; /* RootObj */
TNimType NTI105405; /* TimeInfo */
extern TNimType NTI108; /* int */
TNimType NTI105408; /* range 0..61(int) */
TNimType NTI105410; /* range 0..59(int) */
TNimType NTI105412; /* range 0..23(int) */
TNimType NTI105415; /* range 1..31(int) */
TNimType NTI102006; /* Month */
TNimType NTI105418; /* range -10000..10000(int) */
TNimType NTI102008; /* WeekDay */
TNimType NTI105424; /* range 0..365(int) */
extern TNimType NTI138; /* bool */
extern TNimType NTI149; /* string */
extern TY103425 Dl_103424;
extern TNimType NTI21601; /* ref ValueError */
extern TNimType NTI3249; /* ValueError */
extern tgcheap47016 gch_47044;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(time_t, fromseconds_105477)(NI64 since1970) {
	time_t result;
	nimfr("fromSeconds", "times.nim")
	result = 0;
	nimln(164, "times.nim");
	nimln(166, "times.nim");
	result = fromseconds_105471(((NF) (since1970)));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	nimfr("<", "times.nim")
	result = 0;
	nimln(183, "times.nim");
	nimln(183, "times.nim");
	nimln(183, "times.nim");
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 < IL64(0));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	nimfr("<=", "times.nim")
	result = 0;
	nimln(188, "times.nim");
	nimln(188, "times.nim");
	nimln(188, "times.nim");
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 <= IL64(0));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	nimfr("==", "times.nim")
	result = 0;
	nimln(193, "times.nim");
	nimln(193, "times.nim");
	nimln(193, "times.nim");
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 == IL64(0));
	popFrame();
	return result;
}

N_NIMCALL(timeinterval105407, initinterval_105614)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years) {
	timeinterval105407 result;
	nimfr("initInterval", "times.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(211, "times.nim");
	result.Miliseconds = miliseconds;
	nimln(212, "times.nim");
	result.Seconds = seconds;
	nimln(213, "times.nim");
	result.Minutes = minutes;
	nimln(214, "times.nim");
	result.Hours = hours;
	nimln(215, "times.nim");
	result.Days = days;
	nimln(216, "times.nim");
	result.Months = months;
	nimln(217, "times.nim");
	result.Years = years;
	popFrame();
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	result = (NI64)(a % b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, isleapyear_105630)(NI year) {
	NIM_BOOL result;
	nimfr("isLeapYear", "times.nim")
	result = 0;
	nimln(222, "times.nim");
	{
		NI TMP152;
		nimln(222, "times.nim");
		nimln(222, "times.nim");
		TMP152 = modInt(year, 400);
		if (!(((NI) ((NI64)(TMP152))) == 0)) goto LA3;
		nimln(223, "times.nim");
		nimln(223, "times.nim");
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		NI TMP153;
		nimln(224, "times.nim");
		nimln(224, "times.nim");
		TMP153 = modInt(year, 100);
		if (!(((NI) ((NI64)(TMP153))) == 0)) goto LA6;
		nimln(225, "times.nim");
		nimln(225, "times.nim");
		result = NIM_FALSE;
		goto BeforeRet;
	}
	goto LA1;
	LA6: ;
	{
		NI TMP154;
		nimln(226, "times.nim");
		nimln(226, "times.nim");
		TMP154 = modInt(year, 4);
		if (!(((NI) ((NI64)(TMP154))) == 0)) goto LA9;
		nimln(227, "times.nim");
		nimln(227, "times.nim");
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA9: ;
	{
		nimln(229, "times.nim");
		nimln(229, "times.nim");
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA1: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, getdaysinmonth_105645)(NU8 month, NI year) {
	NI result;
	nimfr("getDaysInMonth", "times.nim")
	result = 0;
	nimln(235, "times.nim");
	switch (month) {
	case ((NU8) 1):
	{
		nimln(236, "times.nim");
		nimln(236, "times.nim");
		{
			NIM_BOOL LOC4;
			nimln(236, "times.nim");
			LOC4 = 0;
			LOC4 = isleapyear_105630(year);
			if (!LOC4) goto LA5;
			result = 29;
		}
		goto LA2;
		LA5: ;
		{
			result = 28;
		}
		LA2: ;
	}
	break;
	case ((NU8) 3):
	case ((NU8) 5):
	case ((NU8) 8):
	case ((NU8) 10):
	{
		nimln(237, "times.nim");
		result = 30;
	}
	break;
	default:
	{
		nimln(238, "times.nim");
		result = 31;
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(void, HEX2BHEX3D_105693)(NF* x_105699, NF y_105702) {
	nimfr("+=", "system.nim")
	nimln(2893, "system.nim");
	nimln(2893, "system.nim");
	(*x_105699) = ((NF)((*x_105699)) + (NF)(y_105702));
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NF, HEX2F_86004)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(NF, toseconds_105658)(timeinfo105405* a, timeinterval105407* interval) {
	NF result;
	timeinfo105405 anew;
	timeinterval105407 newinterv;
	NI TMP162;
	NU8 curmonth;
	NI TMP166;
	NI TMP167;
	NI TMP168;
	NI TMP169;
	NI TMP170;
	NI TMP171;
	NF LOC10;
	nimfr("toSeconds", "times.nim")
	result = 0;
	memset((void*)(&anew), 0, sizeof(anew));
	anew.Sup.m_type = (&NTI105405);
	nimln(244, "times.nim");
	genericAssign((void*)(&anew), (void*)a, (&NTI105405));
	nimln(245, "times.nim");
	newinterv = (*interval);
	nimln(246, "times.nim");
	result = 0.0;
	nimln(248, "times.nim");
	nimln(248, "times.nim");
	TMP162 = mulInt((*interval).Years, 12);
	newinterv.Months = addInt(newinterv.Months, (NI64)(TMP162));
	nimln(249, "times.nim");
	curmonth = anew.Month;
	{
		NI mth_105688;
		NI HEX3Atmp_105809;
		NI res_105812;
		mth_105688 = 0;
		HEX3Atmp_105809 = 0;
		nimln(250, "times.nim");
		HEX3Atmp_105809 = newinterv.Months;
		nimln(1576, "system.nim");
		res_105812 = 1;
		{
			nimln(1577, "system.nim");
			while (1) {
				NI LOC4;
				NI TMP163;
				NI TMP164;
				NI TMP165;
				nimln(1577, "system.nim");
				if (!(res_105812 <= HEX3Atmp_105809)) goto LA3;
				nimln(1576, "system.nim");
				mth_105688 = res_105812;
				nimln(251, "times.nim");
				nimln(251, "times.nim");
				nimln(251, "times.nim");
				nimln(251, "times.nim");
				nimln(251, "times.nim");
				LOC4 = 0;
				LOC4 = getdaysinmonth_105645(curmonth, ((NI) (anew.Year)));
				TMP163 = mulInt(LOC4, 24);
				TMP164 = mulInt((NI64)(TMP163), 60);
				TMP165 = mulInt((NI64)(TMP164), 60);
				HEX2BHEX3D_105693((&result), ((NF) ((NI64)(TMP165))));
				nimln(252, "times.nim");
				{
					nimln(252, "times.nim");
					if (!(curmonth == ((NU8) 11))) goto LA7;
					nimln(253, "times.nim");
					curmonth = ((NU8) 0);
					nimln(254, "times.nim");
					anew.Year = addInt(anew.Year, 1);
				}
				goto LA5;
				LA7: ;
				{
					nimln(256, "times.nim");
					curmonth = addInt(curmonth, 1);
				}
				LA5: ;
				nimln(1579, "system.nim");
				res_105812 = addInt(res_105812, 1);
			} LA3: ;
		}
	}
	nimln(257, "times.nim");
	nimln(257, "times.nim");
	nimln(257, "times.nim");
	nimln(257, "times.nim");
	TMP166 = mulInt(newinterv.Days, 24);
	TMP167 = mulInt((NI64)(TMP166), 60);
	TMP168 = mulInt((NI64)(TMP167), 60);
	HEX2BHEX3D_105693((&result), ((NF) ((NI64)(TMP168))));
	nimln(258, "times.nim");
	nimln(258, "times.nim");
	nimln(258, "times.nim");
	TMP169 = mulInt(newinterv.Hours, 60);
	TMP170 = mulInt((NI64)(TMP169), 60);
	HEX2BHEX3D_105693((&result), ((NF) ((NI64)(TMP170))));
	nimln(259, "times.nim");
	nimln(259, "times.nim");
	TMP171 = mulInt(newinterv.Minutes, 60);
	HEX2BHEX3D_105693((&result), ((NF) ((NI64)(TMP171))));
	nimln(260, "times.nim");
	HEX2BHEX3D_105693((&result), ((NF) (newinterv.Seconds)));
	nimln(261, "times.nim");
	nimln(261, "times.nim");
	LOC10 = 0;
	LOC10 = HEX2F_86004(newinterv.Miliseconds, 1000);
	HEX2BHEX3D_105693((&result), LOC10);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, HEX2B_105833)(timeinfo105405* a, timeinterval105407* interval, timeinfo105405* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	nimfr("+", "times.nim")
	nimln(268, "times.nim");
	nimln(268, "times.nim");
	LOC1 = 0;
	LOC1 = timeinfototime_105465(a);
	t = toseconds_105488(LOC1);
	nimln(269, "times.nim");
	secs = toseconds_105658(a, interval);
	nimln(270, "times.nim");
	{
		time_t LOC6;
		nimln(270, "times.nim");
		if (!eqStrings((*a).Tzname, ((NimStringDesc*) &TMP172))) goto LA4;
		nimln(271, "times.nim");
		nimln(271, "times.nim");
		nimln(271, "times.nim");
		LOC6 = 0;
		LOC6 = fromseconds_105471(((NF)(t) + (NF)(secs)));
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI105405));
		(*Result).Sup.m_type = (&NTI105405);
		getgmtime_105459(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		nimln(273, "times.nim");
		nimln(273, "times.nim");
		nimln(273, "times.nim");
		LOC8 = 0;
		LOC8 = fromseconds_105471(((NF)(t) + (NF)(secs)));
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI105405));
		(*Result).Sup.m_type = (&NTI105405);
		getlocaltime_105453(LOC8, Result);
	}
	LA2: ;
	popFrame();
}

N_NIMCALL(void, HEX2D_105846)(timeinfo105405* a, timeinterval105407* interval, timeinfo105405* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	nimfr("-", "times.nim")
	nimln(280, "times.nim");
	nimln(280, "times.nim");
	LOC1 = 0;
	LOC1 = timeinfototime_105465(a);
	t = toseconds_105488(LOC1);
	nimln(281, "times.nim");
	secs = toseconds_105658(a, interval);
	nimln(282, "times.nim");
	{
		time_t LOC6;
		nimln(282, "times.nim");
		if (!eqStrings((*a).Tzname, ((NimStringDesc*) &TMP172))) goto LA4;
		nimln(283, "times.nim");
		nimln(283, "times.nim");
		nimln(283, "times.nim");
		LOC6 = 0;
		LOC6 = fromseconds_105471(((NF)(t) - (NF)(secs)));
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI105405));
		(*Result).Sup.m_type = (&NTI105405);
		getgmtime_105459(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		nimln(285, "times.nim");
		nimln(285, "times.nim");
		nimln(285, "times.nim");
		LOC8 = 0;
		LOC8 = fromseconds_105471(((NF)(t) - (NF)(secs)));
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI105405));
		(*Result).Sup.m_type = (&NTI105405);
		getlocaltime_105453(LOC8, Result);
	}
	LA2: ;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, gettzname_105548)(TY105550* Result) {
	nimfr("getTzname", "times.nim")
	nimln(446, "times.nim");
	nimln(446, "times.nim");
	nimln(446, "times.nim");
	unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(tzname[(0)- 0]));
	nimln(446, "times.nim");
	unsureAsgnRef((void**) (&(*Result).Field1), cstrToNimstr(tzname[(1)- 0]));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
}

N_NIMCALL(NI, gettimezone_105604)(void) {
	NI result;
	nimfr("getTimezone", "times.nim")
	result = 0;
	nimln(449, "times.nim");
	nimln(449, "times.nim");
	result = timezone;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, tmtotimeinfo_106048)(struct tm* tm, NIM_BOOL local, timeinfo105405* Result) {
	timeinfo105405 LOC1;
	NI TMP173;
	nimfr("tmToTimeInfo", "times.nim")
	nimln(346, "times.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI105405);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI105405);
	LOC1.Second = ((NI)chckRange(((NI) ((*tm).tm_sec)), 0, 61));
	LOC1.Minute = ((NI)chckRange(((NI) ((*tm).tm_min)), 0, 59));
	LOC1.Hour = ((NI)chckRange(((NI) ((*tm).tm_hour)), 0, 23));
	LOC1.Monthday = ((NI)chckRange(((NI) ((*tm).tm_mday)), 1, 31));
	LOC1.Month = ((NU8)chckRange((*tm).tm_mon, ((NU8) 0), ((NU8) 11)));
	nimln(354, "times.nim");
	TMP173 = addInt((*tm).tm_year, ((NI32) 1900));
	if (TMP173 < (-2147483647 -1) || TMP173 > 2147483647) raiseOverflow();
	LOC1.Year = ((NI)chckRange((NI32)(TMP173), -10000, 10000));
	if ((NU)(((NI) ((*tm).tm_wday))) > (NU)(6)) raiseIndexError();
	LOC1.Weekday = weekdays_106053[(((NI) ((*tm).tm_wday)))- 0];
	LOC1.Yearday = ((NI)chckRange(((NI) ((*tm).tm_yday)), 0, 365));
	nimln(357, "times.nim");
	LOC1.Isdst = (((NI32) 0) < (*tm).tm_isdst);
	nimln(358, "times.nim");
	{
		if (!local) goto LA4;
		nimln(359, "times.nim");
		{
			TY105550 LOC10;
			nimln(359, "times.nim");
			if (!(((NI32) 0) < (*tm).tm_isdst)) goto LA8;
			nimln(360, "times.nim");
			memset((void*)(&LOC10), 0, sizeof(LOC10));
			gettzname_105548((&LOC10));
			LOC1.Tzname = copyString(LOC10.Field1);
		}
		goto LA6;
		LA8: ;
		{
			TY105550 LOC12;
			nimln(362, "times.nim");
			memset((void*)(&LOC12), 0, sizeof(LOC12));
			gettzname_105548((&LOC12));
			LOC1.Tzname = copyString(LOC12.Field0);
		}
		LA6: ;
	}
	goto LA2;
	LA4: ;
	{
		LOC1.Tzname = copyString(((NimStringDesc*) &TMP172));
	}
	LA2: ;
	nimln(365, "times.nim");
	{
		if (!local) goto LA16;
		nimln(365, "times.nim");
		LOC1.Timezone = gettimezone_105604();
	}
	goto LA14;
	LA16: ;
	{
		LOC1.Timezone = 0;
	}
	LA14: ;
	genericShallowAssign((void*)Result, (void*)(&LOC1), (&NTI105405));
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(struct tm, timeinfototm_106070)(timeinfo105405* t) {
	struct tm result;
	NI TMP174;
	NI LOC1;
	nimfr("timeInfoToTM", "times.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(371, "times.nim");
	result.tm_sec = ((int) ((*t).Second));
	nimln(372, "times.nim");
	result.tm_min = ((int) ((*t).Minute));
	nimln(373, "times.nim");
	result.tm_hour = ((int) ((*t).Hour));
	nimln(374, "times.nim");
	result.tm_mday = ((int) ((*t).Monthday));
	nimln(375, "times.nim");
	nimln(375, "times.nim");
	result.tm_mon = ((int) ((*t).Month));
	nimln(376, "times.nim");
	nimln(376, "times.nim");
	TMP174 = subInt(((NI) ((*t).Year)), 1900);
	result.tm_year = ((int) ((NI64)(TMP174)));
	nimln(377, "times.nim");
	result.tm_wday = ((int) (weekdays_106074[((*t).Weekday)- 0]));
	nimln(378, "times.nim");
	result.tm_yday = ((int) ((*t).Yearday));
	nimln(379, "times.nim");
	LOC1 = 0;
	nimln(379, "times.nim");
	{
		if (!(*t).Isdst) goto LA4;
		LOC1 = 1;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = 0;
	}
	LA2: ;
	result.tm_isdst = ((int)chckRange(LOC1, ((int) (-2147483647 -1)), ((int) 2147483647)));
	popFrame();
	return result;
}

N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b) {
	NI64 result;
	NF LOC1;
	nimfr("-", "times.nim")
	result = 0;
	nimln(383, "times.nim");
	nimln(383, "times.nim");
	nimln(383, "times.nim");
	nimln(383, "times.nim");
	LOC1 = 0;
	LOC1 = difftime(a, b);
	result = float64ToInt64(LOC1);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI64)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getstartmilsecs_105609)(void) {
	NI result;
	NI LOC1;
	NI TMP175;
	NI TMP176;
	nimfr("getStartMilsecs", "times.nim")
	result = 0;
	nimln(391, "times.nim");
	nimln(391, "times.nim");
	nimln(391, "times.nim");
	LOC1 = 0;
	LOC1 = clock();
	nimln(391, "times.nim");
	TMP175 = divInt(CLOCKS_PER_SEC, 1000);
	TMP176 = divInt(LOC1, (NI64)(TMP175));
	result = (NI64)(TMP176);
	popFrame();
	return result;
}

N_NIMCALL(time_t, gettime_105448)(void) {
	time_t result;
	nimfr("getTime", "times.nim")
	result = 0;
	nimln(398, "times.nim");
	nimln(398, "times.nim");
	result = time(NIM_NIL);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, getlocaltime_105453)(time_t t, timeinfo105405* Result) {
	time_t a;
	struct tm* LOC1;
	nimfr("getLocalTime", "times.nim")
	nimln(400, "times.nim");
	a = t;
	nimln(401, "times.nim");
	nimln(401, "times.nim");
	LOC1 = 0;
	LOC1 = localtime((&a));
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI105405));
	(*Result).Sup.m_type = (&NTI105405);
	tmtotimeinfo_106048((&(*LOC1)), NIM_TRUE, Result);
	popFrame();
}

N_NIMCALL(void, getgmtime_105459)(time_t t, timeinfo105405* Result) {
	time_t a;
	struct tm* LOC1;
	nimfr("getGMTime", "times.nim")
	nimln(406, "times.nim");
	a = t;
	nimln(407, "times.nim");
	nimln(407, "times.nim");
	LOC1 = 0;
	LOC1 = gmtime((&a));
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI105405));
	(*Result).Sup.m_type = (&NTI105405);
	tmtotimeinfo_106048((&(*LOC1)), NIM_FALSE, Result);
	popFrame();
}

N_NIMCALL(time_t, timeinfototime_105465)(timeinfo105405* timeinfo) {
	time_t result;
	timeinfo105405 ctimeinfo;
	struct tm LOC1;
	nimfr("timeInfoToTime", "times.nim")
	result = 0;
	memset((void*)(&ctimeinfo), 0, sizeof(ctimeinfo));
	ctimeinfo.Sup.m_type = (&NTI105405);
	nimln(412, "times.nim");
	genericAssign((void*)(&ctimeinfo), (void*)timeinfo, (&NTI105405));
	nimln(414, "times.nim");
	nimln(414, "times.nim");
	nimln(414, "times.nim");
	LOC1 = timeinfototm_106070((&ctimeinfo));
	result = mktime((&LOC1));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, tostringtillnl_106637)(NCSTRING p) {
	NimStringDesc* result;
	NI i;
	nimfr("toStringTillNL", "times.nim")
	result = 0;
	nimln(417, "times.nim");
	result = copyString(((NimStringDesc*) &TMP177));
	nimln(418, "times.nim");
	i = 0;
	{
		nimln(419, "times.nim");
		while (1) {
			NIM_BOOL LOC3;
			NIM_BOOL LOC4;
			nimln(419, "times.nim");
			LOC3 = 0;
			nimln(419, "times.nim");
			LOC4 = 0;
			nimln(419, "times.nim");
			nimln(419, "times.nim");
			LOC4 = !(((NU8)(p[i]) == (NU8)(0)));
			if (!(LOC4)) goto LA5;
			nimln(419, "times.nim");
			nimln(419, "times.nim");
			LOC4 = !(((NU8)(p[i]) == (NU8)(10)));
			LA5: ;
			LOC3 = LOC4;
			if (!(LOC3)) goto LA6;
			nimln(419, "times.nim");
			nimln(419, "times.nim");
			LOC3 = !(((NU8)(p[i]) == (NU8)(13)));
			LA6: ;
			if (!LOC3) goto LA2;
			nimln(420, "times.nim");
			result = addChar(result, p[i]);
			nimln(421, "times.nim");
			i = addInt(i, 1);
		} LA2: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_105494)(timeinfo105405* timeinfo) {
	NimStringDesc* result;
	NCSTRING p;
	struct tm LOC1;
	nimfr("$", "times.nim")
	result = 0;
	nimln(425, "times.nim");
	nimln(425, "times.nim");
	LOC1 = timeinfototm_106070(timeinfo);
	p = asctime((&LOC1));
	nimln(426, "times.nim");
	result = tostringtillnl_106637(p);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_105500)(time_t time) {
	NimStringDesc* result;
	time_t a;
	NCSTRING LOC1;
	nimfr("$", "times.nim")
	result = 0;
	nimln(430, "times.nim");
	a = time;
	nimln(431, "times.nim");
	nimln(431, "times.nim");
	nimln(431, "times.nim");
	LOC1 = 0;
	LOC1 = ctime((&a));
	result = tostringtillnl_106637(LOC1);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI64, addInt64)(NI64 a, NI64 b) {
	NI64 result;
	result = 0;
	result = (NI64)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (IL64(0) <= (NI64)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (IL64(0) <= (NI64)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI64, unixtimetowintime_106683)(time_t t) {
	NI64 result;
	NI64 TMP178;
	NI64 TMP179;
	nimfr("unixTimeToWinTime", "times.nim")
	result = 0;
	nimln(439, "times.nim");
	nimln(439, "times.nim");
	nimln(439, "times.nim");
	TMP178 = mulInt64(((NI64) (t)), IL64(10000000));
	TMP179 = addInt64((NI64)(TMP178), IL64(116444736000000000));
	result = (NI64)(TMP179);
	popFrame();
	return result;
}

static N_INLINE(NI64, subInt64)(NI64 a, NI64 b) {
	NI64 result;
	result = 0;
	result = (NI64)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (IL64(0) <= (NI64)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (IL64(0) <= (NI64)(result ^ (NI64)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI64, divInt64)(NI64 a, NI64 b) {
	NI64 result;
	result = 0;
	{
		if (!(b == IL64(0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == IL64(-1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI64)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(time_t, wintimetounixtime_106691)(NI64 t) {
	time_t result;
	NI64 TMP180;
	NI64 TMP181;
	nimfr("winTimeToUnixTime", "times.nim")
	result = 0;
	nimln(443, "times.nim");
	nimln(443, "times.nim");
	nimln(443, "times.nim");
	TMP180 = subInt64(t, IL64(116444736000000000));
	TMP181 = divInt64((NI64)(TMP180), IL64(10000000));
	result = ((time_t)chckRange64((NI64)(TMP181), ((time_t) (-2147483647 -1)), ((time_t) 2147483647)));
	popFrame();
	return result;
}

N_NIMCALL(time_t, fromseconds_105471)(NF since1970) {
	time_t result;
	nimfr("fromSeconds", "times.nim")
	result = 0;
	nimln(451, "times.nim");
	result = ((time_t) (since1970));
	popFrame();
	return result;
}

N_NIMCALL(NF, toseconds_105488)(time_t time) {
	NF result;
	nimfr("toSeconds", "times.nim")
	result = 0;
	nimln(453, "times.nim");
	result = ((NF) (time));
	popFrame();
	return result;
}

static N_INLINE(NI64, modInt64)(NI64 a, NI64 b) {
	NI64 result;
	result = 0;
	{
		if (!(b == IL64(0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	result = (NI64)(a % b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NF, ntepochTime)(void) {
	NF result;
	tfiletime102076 f;
	NI64 i64;
	NI64 LOC1;
	NI64 TMP182;
	NI64 secs;
	NI64 TMP183;
	NI64 subsecs;
	NI64 TMP184;
	nimfr("epochTime", "times.nim")
	result = 0;
	memset((void*)(&f), 0, sizeof(f));
	nimln(463, "times.nim");
	Dl_103424((&f));
	nimln(464, "times.nim");
	nimln(464, "times.nim");
	nimln(464, "times.nim");
	LOC1 = 0;
	LOC1 = rdfiletime_103404(f);
	TMP182 = subInt64(LOC1, IL64(116444736000000000));
	i64 = (NI64)(TMP182);
	nimln(465, "times.nim");
	nimln(465, "times.nim");
	TMP183 = divInt64(i64, IL64(10000000));
	secs = (NI64)(TMP183);
	nimln(466, "times.nim");
	nimln(466, "times.nim");
	TMP184 = modInt64(i64, IL64(10000000));
	subsecs = (NI64)(TMP184);
	nimln(467, "times.nim");
	nimln(467, "times.nim");
	nimln(467, "times.nim");
	nimln(467, "times.nim");
	nimln(467, "times.nim");
	result = ((NF)(((double) (((NI) (secs))))) + (NF)(((NF)(((double) (((NI) (subsecs))))) * (NF)(9.9999999999999995e-008))));
	popFrame();
	return result;
}

N_NIMCALL(NF, ntcpuTime)(void) {
	NF result;
	NI LOC1;
	nimfr("cpuTime", "times.nim")
	result = 0;
	nimln(472, "times.nim");
	nimln(472, "times.nim");
	nimln(472, "times.nim");
	nimln(472, "times.nim");
	LOC1 = 0;
	LOC1 = clock();
	nimln(472, "times.nim");
	result = ((NF)(((double) (LOC1))) / (NF)(((double) (CLOCKS_PER_SEC))));
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

N_NIMCALL(NimStringDesc*, ntgetDateStr)(void) {
	NimStringDesc* result;
	timeinfo105405 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NI TMP186;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	nimfr("getDateStr", "times.nim")
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI105405);
	nimln(540, "times.nim");
	nimln(540, "times.nim");
	LOC1 = 0;
	LOC1 = gettime_105448();
	chckNil((void*)(&ti));
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI105405);
	getlocaltime_105453(LOC1, (&ti));
	nimln(541, "times.nim");
	nimln(542, "times.nim");
	LOC2 = 0;
	nimln(541, "times.nim");
	LOC3 = 0;
	LOC3 = nimIntToStr(((NI) (ti.Year)));
	nimln(541, "times.nim");
	nimln(541, "times.nim");
	nimln(541, "times.nim");
	TMP186 = addInt(((NI) (ti.Month)), 1);
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) ((NI64)(TMP186))), 2);
	nimln(542, "times.nim");
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.Monthday)), 2);
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 45);
appendString(LOC2, LOC4);
appendChar(LOC2, 45);
appendString(LOC2, LOC5);
	result = LOC2;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, ntgetClockStr)(void) {
	NimStringDesc* result;
	timeinfo105405 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	nimfr("getClockStr", "times.nim")
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI105405);
	nimln(546, "times.nim");
	nimln(546, "times.nim");
	LOC1 = 0;
	LOC1 = gettime_105448();
	chckNil((void*)(&ti));
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI105405);
	getlocaltime_105453(LOC1, (&ti));
	nimln(547, "times.nim");
	nimln(548, "times.nim");
	LOC2 = 0;
	nimln(547, "times.nim");
	LOC3 = 0;
	LOC3 = nsuIntToStr(((NI) (ti.Hour)), 2);
	nimln(547, "times.nim");
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) (ti.Minute)), 2);
	nimln(548, "times.nim");
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.Second)), 2);
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 58);
appendString(LOC2, LOC4);
appendChar(LOC2, 58);
appendString(LOC2, LOC5);
	result = LOC2;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_107234)(NU8 day) {
	NimStringDesc* result;
	nimfr("$", "times.nim")
	result = 0;
	nimln(554, "times.nim");
	nimln(554, "times.nim");
	result = copyString(lookup_107238[(day)- 0]);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_107250)(NU8 m) {
	NimStringDesc* result;
	nimfr("$", "times.nim")
	result = 0;
	nimln(561, "times.nim");
	nimln(561, "times.nim");
	result = copyString(lookup_107254[(m)- 0]);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_86059)(NimStringDesc* s, slice86066 x) {
	NimStringDesc* result;
	NI LOC1;
	NI LOC7;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(2773, "system.nim");
	nimln(2773, "system.nim");
	LOC1 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.A)) goto LA4;
		LOC1 = x.A;
	}
	goto LA2;
	LA4: ;
	{
		NI TMP234;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP234 = addInt(s->Sup.len, x.A);
		LOC1 = (NI64)(TMP234);
	}
	LA2: ;
	LOC7 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.B)) goto LA10;
		LOC7 = x.B;
	}
	goto LA8;
	LA10: ;
	{
		NI TMP235;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP235 = addInt(s->Sup.len, x.B);
		LOC7 = (NI64)(TMP235);
	}
	LA8: ;
	result = copyStrLast(s, LOC1, LOC7);
	popFrame();
	return result;
}

static N_INLINE(slice86066, HEX2EHEX2E_93099)(NI a_93103, NI b_93105) {
	slice86066 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(226, "system.nim");
	result.A = a_93103;
	nimln(227, "system.nim");
	result.B = b_93105;
	popFrame();
	return result;
}

static N_INLINE(tcell44933*, usrtocell_48646)(void* usr) {
	tcell44933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell44933*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell44933))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50204)(tcell44933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell44933* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48646(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell44933* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48646((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50204(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, formattoken_107266)(timeinfo105405* info, NimStringDesc* token, NimStringDesc** buf) {
	nimfr("formatToken", "times.nim")
	nimln(569, "times.nim");
	switch (hashString(token) & 31) {
	case 0: 
if (eqStrings(token, ((NimStringDesc*) &TMP177))) goto LA28;
break;
	case 1: 
if (eqStrings(token, ((NimStringDesc*) &TMP215))) goto LA10;
break;
	case 5: 
if (eqStrings(token, ((NimStringDesc*) &TMP206))) goto LA1;
break;
	case 6: 
if (eqStrings(token, ((NimStringDesc*) &TMP223))) goto LA18;
break;
	case 7: 
if (eqStrings(token, ((NimStringDesc*) &TMP232))) goto LA27;
break;
	case 8: 
if (eqStrings(token, ((NimStringDesc*) &TMP224))) goto LA19;
break;
	case 10: 
if (eqStrings(token, ((NimStringDesc*) &TMP210))) goto LA5;
if (eqStrings(token, ((NimStringDesc*) &TMP216))) goto LA11;
if (eqStrings(token, ((NimStringDesc*) &TMP217))) goto LA12;
if (eqStrings(token, ((NimStringDesc*) &TMP221))) goto LA16;
if (eqStrings(token, ((NimStringDesc*) &TMP225))) goto LA20;
break;
	case 12: 
if (eqStrings(token, ((NimStringDesc*) &TMP218))) goto LA13;
break;
	case 14: 
if (eqStrings(token, ((NimStringDesc*) &TMP231))) goto LA26;
break;
	case 15: 
if (eqStrings(token, ((NimStringDesc*) &TMP209))) goto LA4;
if (eqStrings(token, ((NimStringDesc*) &TMP222))) goto LA17;
break;
	case 20: 
if (eqStrings(token, ((NimStringDesc*) &TMP228))) goto LA23;
break;
	case 21: 
if (eqStrings(token, ((NimStringDesc*) &TMP207))) goto LA2;
if (eqStrings(token, ((NimStringDesc*) &TMP214))) goto LA9;
break;
	case 22: 
if (eqStrings(token, ((NimStringDesc*) &TMP220))) goto LA15;
if (eqStrings(token, ((NimStringDesc*) &TMP230))) goto LA25;
break;
	case 24: 
if (eqStrings(token, ((NimStringDesc*) &TMP212))) goto LA7;
break;
	case 25: 
if (eqStrings(token, ((NimStringDesc*) &TMP213))) goto LA8;
break;
	case 28: 
if (eqStrings(token, ((NimStringDesc*) &TMP219))) goto LA14;
break;
	case 29: 
if (eqStrings(token, ((NimStringDesc*) &TMP226))) goto LA21;
break;
	case 30: 
if (eqStrings(token, ((NimStringDesc*) &TMP229))) goto LA24;
break;
	case 31: 
if (eqStrings(token, ((NimStringDesc*) &TMP208))) goto LA3;
if (eqStrings(token, ((NimStringDesc*) &TMP211))) goto LA6;
if (eqStrings(token, ((NimStringDesc*) &TMP227))) goto LA22;
break;
	}
	goto LA29;
	LA1: ;
	{
		NimStringDesc* LOC32;
		nimln(571, "times.nim");
		nimln(571, "times.nim");
		LOC32 = 0;
		LOC32 = nimIntToStr(((NI) ((*info).Monthday)));
		(*buf) = resizeString((*buf), LOC32->Sup.len + 0);
appendString((*buf), LOC32);
	}
	goto LA30;
	LA2: ;
	{
		NimStringDesc* LOC38;
		nimln(573, "times.nim");
		{
			nimln(573, "times.nim");
			if (!(((NI) ((*info).Monthday)) < 10)) goto LA36;
			nimln(574, "times.nim");
			(*buf) = resizeString((*buf), 1);
appendString((*buf), ((NimStringDesc*) &TMP233));
		}
		LA36: ;
		nimln(575, "times.nim");
		nimln(575, "times.nim");
		LOC38 = 0;
		LOC38 = nimIntToStr(((NI) ((*info).Monthday)));
		(*buf) = resizeString((*buf), LOC38->Sup.len + 0);
appendString((*buf), LOC38);
	}
	goto LA30;
	LA3: ;
	{
		NimStringDesc* LOC40;
		slice86066 LOC41;
		NimStringDesc* LOC42;
		nimln(577, "times.nim");
		nimln(577, "times.nim");
		nimln(577, "times.nim");
		LOC40 = 0;
		LOC40 = HEX24_107234((*info).Weekday);
		nimln(577, "times.nim");
		LOC41 = HEX2EHEX2E_93099(0, 2);
		LOC42 = 0;
		LOC42 = HEX5BHEX5D_86059(LOC40, LOC41);
		(*buf) = resizeString((*buf), LOC42->Sup.len + 0);
appendString((*buf), LOC42);
	}
	goto LA30;
	LA4: ;
	{
		NimStringDesc* LOC44;
		nimln(579, "times.nim");
		nimln(579, "times.nim");
		LOC44 = 0;
		LOC44 = HEX24_107234((*info).Weekday);
		(*buf) = resizeString((*buf), LOC44->Sup.len + 0);
appendString((*buf), LOC44);
	}
	goto LA30;
	LA5: ;
	{
		NI LOC46;
		NimStringDesc* LOC52;
		nimln(581, "times.nim");
		nimln(581, "times.nim");
		LOC46 = 0;
		nimln(581, "times.nim");
		{
			NI TMP236;
			nimln(581, "times.nim");
			if (!(12 < ((NI) ((*info).Hour)))) goto LA49;
			nimln(581, "times.nim");
			TMP236 = subInt(((NI) ((*info).Hour)), 12);
			LOC46 = ((NI) ((NI64)(TMP236)));
		}
		goto LA47;
		LA49: ;
		{
			LOC46 = ((NI) ((*info).Hour));
		}
		LA47: ;
		LOC52 = 0;
		LOC52 = nimIntToStr(LOC46);
		(*buf) = resizeString((*buf), LOC52->Sup.len + 0);
appendString((*buf), LOC52);
	}
	goto LA30;
	LA6: ;
	{
		NI amerhour;
		NimStringDesc* LOC63;
		nimln(583, "times.nim");
		nimln(583, "times.nim");
		{
			NI TMP237;
			nimln(583, "times.nim");
			if (!(12 < ((NI) ((*info).Hour)))) goto LA56;
			nimln(583, "times.nim");
			TMP237 = subInt(((NI) ((*info).Hour)), 12);
			amerhour = ((NI) ((NI64)(TMP237)));
		}
		goto LA54;
		LA56: ;
		{
			amerhour = ((NI) ((*info).Hour));
		}
		LA54: ;
		nimln(584, "times.nim");
		{
			nimln(584, "times.nim");
			if (!(amerhour < 10)) goto LA61;
			nimln(585, "times.nim");
			(*buf) = addChar((*buf), 48);
		}
		LA61: ;
		nimln(586, "times.nim");
		nimln(586, "times.nim");
		LOC63 = 0;
		LOC63 = nimIntToStr(amerhour);
		(*buf) = resizeString((*buf), LOC63->Sup.len + 0);
appendString((*buf), LOC63);
	}
	goto LA30;
	LA7: ;
	{
		NimStringDesc* LOC65;
		nimln(588, "times.nim");
		nimln(588, "times.nim");
		LOC65 = 0;
		LOC65 = nimIntToStr(((NI) ((*info).Hour)));
		(*buf) = resizeString((*buf), LOC65->Sup.len + 0);
appendString((*buf), LOC65);
	}
	goto LA30;
	LA8: ;
	{
		NimStringDesc* LOC71;
		nimln(590, "times.nim");
		{
			nimln(590, "times.nim");
			if (!(((NI) ((*info).Hour)) < 10)) goto LA69;
			nimln(591, "times.nim");
			(*buf) = addChar((*buf), 48);
		}
		LA69: ;
		nimln(592, "times.nim");
		nimln(592, "times.nim");
		LOC71 = 0;
		LOC71 = nimIntToStr(((NI) ((*info).Hour)));
		(*buf) = resizeString((*buf), LOC71->Sup.len + 0);
appendString((*buf), LOC71);
	}
	goto LA30;
	LA9: ;
	{
		NimStringDesc* LOC73;
		nimln(594, "times.nim");
		nimln(594, "times.nim");
		LOC73 = 0;
		LOC73 = nimIntToStr(((NI) ((*info).Minute)));
		(*buf) = resizeString((*buf), LOC73->Sup.len + 0);
appendString((*buf), LOC73);
	}
	goto LA30;
	LA10: ;
	{
		NimStringDesc* LOC79;
		nimln(596, "times.nim");
		{
			nimln(596, "times.nim");
			if (!(((NI) ((*info).Minute)) < 10)) goto LA77;
			nimln(597, "times.nim");
			(*buf) = addChar((*buf), 48);
		}
		LA77: ;
		nimln(598, "times.nim");
		nimln(598, "times.nim");
		LOC79 = 0;
		LOC79 = nimIntToStr(((NI) ((*info).Minute)));
		(*buf) = resizeString((*buf), LOC79->Sup.len + 0);
appendString((*buf), LOC79);
	}
	goto LA30;
	LA11: ;
	{
		NI TMP238;
		NimStringDesc* LOC81;
		nimln(600, "times.nim");
		nimln(600, "times.nim");
		nimln(600, "times.nim");
		TMP238 = addInt(((NI) ((*info).Month)), 1);
		LOC81 = 0;
		LOC81 = nimIntToStr((NI64)(TMP238));
		(*buf) = resizeString((*buf), LOC81->Sup.len + 0);
appendString((*buf), LOC81);
	}
	goto LA30;
	LA12: ;
	{
		NI TMP239;
		NimStringDesc* LOC87;
		nimln(602, "times.nim");
		{
			nimln(602, "times.nim");
			if (!((*info).Month < ((NU8) 9))) goto LA85;
			nimln(603, "times.nim");
			(*buf) = addChar((*buf), 48);
		}
		LA85: ;
		nimln(604, "times.nim");
		nimln(604, "times.nim");
		nimln(604, "times.nim");
		TMP239 = addInt(((NI) ((*info).Month)), 1);
		LOC87 = 0;
		LOC87 = nimIntToStr((NI64)(TMP239));
		(*buf) = resizeString((*buf), LOC87->Sup.len + 0);
appendString((*buf), LOC87);
	}
	goto LA30;
	LA13: ;
	{
		NimStringDesc* LOC89;
		slice86066 LOC90;
		NimStringDesc* LOC91;
		nimln(606, "times.nim");
		nimln(606, "times.nim");
		nimln(606, "times.nim");
		LOC89 = 0;
		LOC89 = HEX24_107250((*info).Month);
		nimln(606, "times.nim");
		LOC90 = HEX2EHEX2E_93099(0, 2);
		LOC91 = 0;
		LOC91 = HEX5BHEX5D_86059(LOC89, LOC90);
		(*buf) = resizeString((*buf), LOC91->Sup.len + 0);
appendString((*buf), LOC91);
	}
	goto LA30;
	LA14: ;
	{
		NimStringDesc* LOC93;
		nimln(608, "times.nim");
		nimln(608, "times.nim");
		LOC93 = 0;
		LOC93 = HEX24_107250((*info).Month);
		(*buf) = resizeString((*buf), LOC93->Sup.len + 0);
appendString((*buf), LOC93);
	}
	goto LA30;
	LA15: ;
	{
		NimStringDesc* LOC95;
		nimln(610, "times.nim");
		nimln(610, "times.nim");
		LOC95 = 0;
		LOC95 = nimIntToStr(((NI) ((*info).Second)));
		(*buf) = resizeString((*buf), LOC95->Sup.len + 0);
appendString((*buf), LOC95);
	}
	goto LA30;
	LA16: ;
	{
		NimStringDesc* LOC101;
		nimln(612, "times.nim");
		{
			nimln(612, "times.nim");
			if (!(((NI) ((*info).Second)) < 10)) goto LA99;
			nimln(613, "times.nim");
			(*buf) = addChar((*buf), 48);
		}
		LA99: ;
		nimln(614, "times.nim");
		nimln(614, "times.nim");
		LOC101 = 0;
		LOC101 = nimIntToStr(((NI) ((*info).Second)));
		(*buf) = resizeString((*buf), LOC101->Sup.len + 0);
appendString((*buf), LOC101);
	}
	goto LA30;
	LA17: ;
	{
		nimln(616, "times.nim");
		{
			nimln(616, "times.nim");
			if (!(12 <= ((NI) ((*info).Hour)))) goto LA105;
			nimln(617, "times.nim");
			(*buf) = addChar((*buf), 80);
		}
		goto LA103;
		LA105: ;
		{
			nimln(618, "times.nim");
			(*buf) = addChar((*buf), 65);
		}
		LA103: ;
	}
	goto LA30;
	LA18: ;
	{
		nimln(620, "times.nim");
		{
			nimln(620, "times.nim");
			if (!(12 <= ((NI) ((*info).Hour)))) goto LA111;
			nimln(621, "times.nim");
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP240));
		}
		goto LA109;
		LA111: ;
		{
			nimln(622, "times.nim");
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP241));
		}
		LA109: ;
	}
	goto LA30;
	LA19: ;
	{
		NI fr;
		NimStringDesc* LOC115;
		NI TMP242;
		NimStringDesc* LOC120;
		NimStringDesc* LOC121;
		NI TMP243;
		slice86066 LOC122;
		NimStringDesc* LOC123;
		nimln(624, "times.nim");
		nimln(624, "times.nim");
		nimln(624, "times.nim");
		nimln(624, "times.nim");
		LOC115 = 0;
		LOC115 = nimIntToStr(((NI) ((*info).Year)));
		TMP242 = subInt(LOC115->Sup.len, 1);
		fr = (NI64)(TMP242);
		nimln(625, "times.nim");
		{
			nimln(625, "times.nim");
			if (!(fr < 0)) goto LA118;
			nimln(625, "times.nim");
			fr = 0;
		}
		LA118: ;
		nimln(626, "times.nim");
		nimln(626, "times.nim");
		nimln(626, "times.nim");
		LOC120 = 0;
		LOC120 = nimIntToStr(((NI) ((*info).Year)));
		nimln(626, "times.nim");
		nimln(626, "times.nim");
		nimln(626, "times.nim");
		nimln(626, "times.nim");
		LOC121 = 0;
		LOC121 = nimIntToStr(((NI) ((*info).Year)));
		TMP243 = subInt(LOC121->Sup.len, 1);
		LOC122 = HEX2EHEX2E_93099(fr, (NI64)(TMP243));
		LOC123 = 0;
		LOC123 = HEX5BHEX5D_86059(LOC120, LOC122);
		(*buf) = resizeString((*buf), LOC123->Sup.len + 0);
appendString((*buf), LOC123);
	}
	goto LA30;
	LA20: ;
	{
		NI fr;
		NimStringDesc* LOC125;
		NI TMP244;
		NimStringDesc* fyear;
		NimStringDesc* LOC130;
		NimStringDesc* LOC131;
		NI TMP245;
		slice86066 LOC132;
		nimln(628, "times.nim");
		nimln(628, "times.nim");
		nimln(628, "times.nim");
		nimln(628, "times.nim");
		LOC125 = 0;
		LOC125 = nimIntToStr(((NI) ((*info).Year)));
		TMP244 = subInt(LOC125->Sup.len, 2);
		fr = (NI64)(TMP244);
		nimln(629, "times.nim");
		{
			nimln(629, "times.nim");
			if (!(fr < 0)) goto LA128;
			nimln(629, "times.nim");
			fr = 0;
		}
		LA128: ;
		nimln(630, "times.nim");
		nimln(630, "times.nim");
		LOC130 = 0;
		LOC130 = nimIntToStr(((NI) ((*info).Year)));
		nimln(630, "times.nim");
		nimln(630, "times.nim");
		nimln(630, "times.nim");
		nimln(630, "times.nim");
		LOC131 = 0;
		LOC131 = nimIntToStr(((NI) ((*info).Year)));
		TMP245 = subInt(LOC131->Sup.len, 1);
		LOC132 = HEX2EHEX2E_93099(fr, (NI64)(TMP245));
		fyear = HEX5BHEX5D_86059(LOC130, LOC132);
		nimln(631, "times.nim");
		{
			NimStringDesc* LOC137;
			NI TMP247;
			NimStringDesc* LOC138;
			nimln(631, "times.nim");
			nimln(631, "times.nim");
			nimln(631, "times.nim");
			if (!!((fyear->Sup.len == 2))) goto LA135;
			nimln(631, "times.nim");
			nimln(631, "times.nim");
			LOC137 = 0;
			nimln(631, "times.nim");
			nimln(631, "times.nim");
			nimln(631, "times.nim");
			TMP247 = subInt(2, fyear->Sup.len);
			LOC138 = 0;
			LOC138 = nsuRepeatChar((NI64)(TMP247), 48);
			LOC137 = rawNewString(LOC138->Sup.len + fyear->Sup.len + 0);
appendString(LOC137, LOC138);
appendString(LOC137, fyear);
			fyear = LOC137;
		}
		LA135: ;
		nimln(632, "times.nim");
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA21: ;
	{
		NI fr;
		NimStringDesc* LOC140;
		NI TMP248;
		NimStringDesc* fyear;
		NimStringDesc* LOC145;
		NimStringDesc* LOC146;
		NI TMP249;
		slice86066 LOC147;
		nimln(634, "times.nim");
		nimln(634, "times.nim");
		nimln(634, "times.nim");
		nimln(634, "times.nim");
		LOC140 = 0;
		LOC140 = nimIntToStr(((NI) ((*info).Year)));
		TMP248 = subInt(LOC140->Sup.len, 3);
		fr = (NI64)(TMP248);
		nimln(635, "times.nim");
		{
			nimln(635, "times.nim");
			if (!(fr < 0)) goto LA143;
			nimln(635, "times.nim");
			fr = 0;
		}
		LA143: ;
		nimln(636, "times.nim");
		nimln(636, "times.nim");
		LOC145 = 0;
		LOC145 = nimIntToStr(((NI) ((*info).Year)));
		nimln(636, "times.nim");
		nimln(636, "times.nim");
		nimln(636, "times.nim");
		nimln(636, "times.nim");
		LOC146 = 0;
		LOC146 = nimIntToStr(((NI) ((*info).Year)));
		TMP249 = subInt(LOC146->Sup.len, 1);
		LOC147 = HEX2EHEX2E_93099(fr, (NI64)(TMP249));
		fyear = HEX5BHEX5D_86059(LOC145, LOC147);
		nimln(637, "times.nim");
		{
			NimStringDesc* LOC152;
			NI TMP250;
			NimStringDesc* LOC153;
			nimln(637, "times.nim");
			nimln(637, "times.nim");
			nimln(637, "times.nim");
			if (!!((fyear->Sup.len == 3))) goto LA150;
			nimln(637, "times.nim");
			nimln(637, "times.nim");
			LOC152 = 0;
			nimln(637, "times.nim");
			nimln(637, "times.nim");
			nimln(637, "times.nim");
			TMP250 = subInt(3, fyear->Sup.len);
			LOC153 = 0;
			LOC153 = nsuRepeatChar((NI64)(TMP250), 48);
			LOC152 = rawNewString(LOC153->Sup.len + fyear->Sup.len + 0);
appendString(LOC152, LOC153);
appendString(LOC152, fyear);
			fyear = LOC152;
		}
		LA150: ;
		nimln(638, "times.nim");
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA22: ;
	{
		NI fr;
		NimStringDesc* LOC155;
		NI TMP251;
		NimStringDesc* fyear;
		NimStringDesc* LOC160;
		NimStringDesc* LOC161;
		NI TMP252;
		slice86066 LOC162;
		nimln(640, "times.nim");
		nimln(640, "times.nim");
		nimln(640, "times.nim");
		nimln(640, "times.nim");
		LOC155 = 0;
		LOC155 = nimIntToStr(((NI) ((*info).Year)));
		TMP251 = subInt(LOC155->Sup.len, 4);
		fr = (NI64)(TMP251);
		nimln(641, "times.nim");
		{
			nimln(641, "times.nim");
			if (!(fr < 0)) goto LA158;
			nimln(641, "times.nim");
			fr = 0;
		}
		LA158: ;
		nimln(642, "times.nim");
		nimln(642, "times.nim");
		LOC160 = 0;
		LOC160 = nimIntToStr(((NI) ((*info).Year)));
		nimln(642, "times.nim");
		nimln(642, "times.nim");
		nimln(642, "times.nim");
		nimln(642, "times.nim");
		LOC161 = 0;
		LOC161 = nimIntToStr(((NI) ((*info).Year)));
		TMP252 = subInt(LOC161->Sup.len, 1);
		LOC162 = HEX2EHEX2E_93099(fr, (NI64)(TMP252));
		fyear = HEX5BHEX5D_86059(LOC160, LOC162);
		nimln(643, "times.nim");
		{
			NimStringDesc* LOC167;
			NI TMP253;
			NimStringDesc* LOC168;
			nimln(643, "times.nim");
			nimln(643, "times.nim");
			nimln(643, "times.nim");
			if (!!((fyear->Sup.len == 4))) goto LA165;
			nimln(643, "times.nim");
			nimln(643, "times.nim");
			LOC167 = 0;
			nimln(643, "times.nim");
			nimln(643, "times.nim");
			nimln(643, "times.nim");
			TMP253 = subInt(4, fyear->Sup.len);
			LOC168 = 0;
			LOC168 = nsuRepeatChar((NI64)(TMP253), 48);
			LOC167 = rawNewString(LOC168->Sup.len + fyear->Sup.len + 0);
appendString(LOC167, LOC168);
appendString(LOC167, fyear);
			fyear = LOC167;
		}
		LA165: ;
		nimln(644, "times.nim");
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA23: ;
	{
		NI fr;
		NimStringDesc* LOC170;
		NI TMP254;
		NimStringDesc* fyear;
		NimStringDesc* LOC175;
		NimStringDesc* LOC176;
		NI TMP255;
		slice86066 LOC177;
		nimln(646, "times.nim");
		nimln(646, "times.nim");
		nimln(646, "times.nim");
		nimln(646, "times.nim");
		LOC170 = 0;
		LOC170 = nimIntToStr(((NI) ((*info).Year)));
		TMP254 = subInt(LOC170->Sup.len, 5);
		fr = (NI64)(TMP254);
		nimln(647, "times.nim");
		{
			nimln(647, "times.nim");
			if (!(fr < 0)) goto LA173;
			nimln(647, "times.nim");
			fr = 0;
		}
		LA173: ;
		nimln(648, "times.nim");
		nimln(648, "times.nim");
		LOC175 = 0;
		LOC175 = nimIntToStr(((NI) ((*info).Year)));
		nimln(648, "times.nim");
		nimln(648, "times.nim");
		nimln(648, "times.nim");
		nimln(648, "times.nim");
		LOC176 = 0;
		LOC176 = nimIntToStr(((NI) ((*info).Year)));
		TMP255 = subInt(LOC176->Sup.len, 1);
		LOC177 = HEX2EHEX2E_93099(fr, (NI64)(TMP255));
		fyear = HEX5BHEX5D_86059(LOC175, LOC177);
		nimln(649, "times.nim");
		{
			NimStringDesc* LOC182;
			NI TMP256;
			NimStringDesc* LOC183;
			nimln(649, "times.nim");
			nimln(649, "times.nim");
			nimln(649, "times.nim");
			if (!!((fyear->Sup.len == 5))) goto LA180;
			nimln(649, "times.nim");
			nimln(649, "times.nim");
			LOC182 = 0;
			nimln(649, "times.nim");
			nimln(649, "times.nim");
			nimln(649, "times.nim");
			TMP256 = subInt(5, fyear->Sup.len);
			LOC183 = 0;
			LOC183 = nsuRepeatChar((NI64)(TMP256), 48);
			LOC182 = rawNewString(LOC183->Sup.len + fyear->Sup.len + 0);
appendString(LOC182, LOC183);
appendString(LOC182, fyear);
			fyear = LOC182;
		}
		LA180: ;
		nimln(650, "times.nim");
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA24: ;
	{
		NI hrs;
		NI TMP257;
		NI TMP258;
		NimStringDesc* LOC185;
		nimln(652, "times.nim");
		nimln(652, "times.nim");
		nimln(652, "times.nim");
		TMP257 = divInt((*info).Timezone, 60);
		TMP258 = divInt((NI64)(TMP257), 60);
		hrs = (NI64)(TMP258);
		nimln(653, "times.nim");
		nimln(653, "times.nim");
		LOC185 = 0;
		LOC185 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC185->Sup.len + 0);
appendString((*buf), LOC185);
	}
	goto LA30;
	LA25: ;
	{
		NI hrs;
		NI TMP259;
		NI TMP260;
		NimStringDesc* LOC187;
		nimln(655, "times.nim");
		nimln(655, "times.nim");
		nimln(655, "times.nim");
		TMP259 = divInt((*info).Timezone, 60);
		TMP260 = divInt((NI64)(TMP259), 60);
		hrs = (NI64)(TMP260);
		nimln(657, "times.nim");
		nimln(657, "times.nim");
		LOC187 = 0;
		LOC187 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC187->Sup.len + 0);
appendString((*buf), LOC187);
		nimln(658, "times.nim");
		{
			NI atindex;
			NimStringDesc* LOC192;
			NI LOC193;
			NI TMP261;
			NI TMP262;
			nimln(658, "times.nim");
			nimln(658, "times.nim");
			if (hrs == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
			if (!((hrs > 0? (hrs) : -(hrs)) < 10)) goto LA190;
			nimln(659, "times.nim");
			nimln(659, "times.nim");
			nimln(659, "times.nim");
			nimln(659, "times.nim");
			nimln(659, "times.nim");
			nimln(659, "times.nim");
			LOC192 = 0;
			LOC192 = nimIntToStr(hrs);
			LOC193 = 0;
			nimln(659, "times.nim");
			{
				nimln(659, "times.nim");
				if (!(hrs < 0)) goto LA196;
				LOC193 = 1;
			}
			goto LA194;
			LA196: ;
			{
				LOC193 = 0;
			}
			LA194: ;
			TMP261 = subInt(LOC192->Sup.len, LOC193);
			TMP262 = subInt((*buf)->Sup.len, (NI64)(TMP261));
			atindex = (NI64)(TMP262);
			nimln(660, "times.nim");
			insert_87801(buf, ((NimStringDesc*) &TMP233), atindex);
		}
		LA190: ;
	}
	goto LA30;
	LA26: ;
	{
		NI hrs;
		NI TMP263;
		NI TMP264;
		NimStringDesc* LOC200;
		NimStringDesc* LOC201;
		nimln(662, "times.nim");
		nimln(662, "times.nim");
		nimln(662, "times.nim");
		TMP263 = divInt((*info).Timezone, 60);
		TMP264 = divInt((NI64)(TMP263), 60);
		hrs = (NI64)(TMP264);
		nimln(664, "times.nim");
		nimln(664, "times.nim");
		LOC200 = 0;
		nimln(664, "times.nim");
		LOC201 = 0;
		LOC201 = nimIntToStr(hrs);
		LOC200 = rawNewString(LOC201->Sup.len + 3);
appendString(LOC200, LOC201);
appendString(LOC200, ((NimStringDesc*) &TMP265));
		(*buf) = resizeString((*buf), LOC200->Sup.len + 0);
appendString((*buf), LOC200);
		nimln(665, "times.nim");
		{
			NI atindex;
			NimStringDesc* LOC206;
			NimStringDesc* LOC207;
			NI LOC208;
			NI TMP266;
			NI TMP267;
			nimln(665, "times.nim");
			nimln(665, "times.nim");
			if (hrs == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
			if (!((hrs > 0? (hrs) : -(hrs)) < 10)) goto LA204;
			nimln(666, "times.nim");
			nimln(666, "times.nim");
			nimln(666, "times.nim");
			nimln(666, "times.nim");
			nimln(666, "times.nim");
			nimln(666, "times.nim");
			LOC206 = 0;
			nimln(666, "times.nim");
			LOC207 = 0;
			LOC207 = nimIntToStr(hrs);
			LOC206 = rawNewString(LOC207->Sup.len + 3);
appendString(LOC206, LOC207);
appendString(LOC206, ((NimStringDesc*) &TMP265));
			LOC208 = 0;
			nimln(666, "times.nim");
			{
				nimln(666, "times.nim");
				if (!(hrs < 0)) goto LA211;
				LOC208 = 1;
			}
			goto LA209;
			LA211: ;
			{
				LOC208 = 0;
			}
			LA209: ;
			TMP266 = subInt(LOC206->Sup.len, LOC208);
			TMP267 = subInt((*buf)->Sup.len, (NI64)(TMP266));
			atindex = (NI64)(TMP267);
			nimln(667, "times.nim");
			insert_87801(buf, ((NimStringDesc*) &TMP233), atindex);
		}
		LA204: ;
	}
	goto LA30;
	LA27: ;
	{
		nimln(669, "times.nim");
		(*buf) = resizeString((*buf), (*info).Tzname->Sup.len + 0);
appendString((*buf), (*info).Tzname);
	}
	goto LA30;
	LA28: ;
	{
	}
	goto LA30;
	LA29: ;
	{
		valueerror3249* e_107394;
		NimStringDesc* LOC217;
		e_107394 = 0;
		nimln(2149, "system.nim");
		e_107394 = (valueerror3249*) newObj((&NTI21601), sizeof(valueerror3249));
		(*e_107394).Sup.Sup.m_type = (&NTI3249);
		nimln(2150, "system.nim");
		nimln(673, "times.nim");
		LOC217 = 0;
		LOC217 = rawNewString(token->Sup.len + 23);
appendString(LOC217, ((NimStringDesc*) &TMP268));
appendString(LOC217, token);
		asgnRefNoCycle((void**) (&(*e_107394).Sup.message), LOC217);
		nimln(673, "times.nim");
		raiseException((Exception*)e_107394, "ValueError");
	}
	LA30: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, format_107421)(timeinfo105405* info, NimStringDesc* f) {
	NimStringDesc* result;
	NI i;
	NimStringDesc* currentf;
	nimfr("format", "times.nim")
	result = 0;
	nimln(716, "times.nim");
	result = copyString(((NimStringDesc*) &TMP177));
	nimln(717, "times.nim");
	i = 0;
	nimln(718, "times.nim");
	currentf = copyString(((NimStringDesc*) &TMP177));
	{
		nimln(719, "times.nim");
		while (1) {
			nimln(720, "times.nim");
			if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
			switch (((NU8)(f->data[i]))) {
			case 32:
			case 45:
			case 47:
			case 58:
			case 39:
			case 0:
			case 40:
			case 41:
			case 91:
			case 93:
			case 44:
			{
				nimln(722, "times.nim");
				formattoken_107266(info, currentf, (&result));
				nimln(724, "times.nim");
				currentf = copyString(((NimStringDesc*) &TMP177));
				nimln(725, "times.nim");
				{
					nimln(725, "times.nim");
					if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
					if (!((NU8)(f->data[i]) == (NU8)(0))) goto LA6;
					nimln(725, "times.nim");
					goto LA1;
				}
				LA6: ;
				nimln(727, "times.nim");
				{
					nimln(727, "times.nim");
					if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
					if (!((NU8)(f->data[i]) == (NU8)(39))) goto LA10;
					nimln(728, "times.nim");
					i = addInt(i, 1);
					{
						nimln(729, "times.nim");
						while (1) {
							NIM_BOOL LOC14;
							NI TMP269;
							nimln(729, "times.nim");
							LOC14 = 0;
							nimln(729, "times.nim");
							nimln(729, "times.nim");
							if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
							LOC14 = !(((NU8)(f->data[i]) == (NU8)(39)));
							if (!(LOC14)) goto LA15;
							nimln(729, "times.nim");
							nimln(729, "times.nim");
							nimln(729, "times.nim");
							TMP269 = subInt(f->Sup.len, 1);
							LOC14 = (i < (NI64)(TMP269));
							LA15: ;
							if (!LOC14) goto LA13;
							nimln(730, "times.nim");
							if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
							result = addChar(result, f->data[i]);
							nimln(731, "times.nim");
							i = addInt(i, 1);
						} LA13: ;
					}
				}
				goto LA8;
				LA10: ;
				{
					nimln(732, "times.nim");
					if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
					result = addChar(result, f->data[i]);
				}
				LA8: ;
			}
			break;
			default:
			{
				nimln(736, "times.nim");
				{
					NIM_BOOL LOC20;
					nimln(736, "times.nim");
					LOC20 = 0;
					nimln(736, "times.nim");
					nimln(736, "times.nim");
					LOC20 = (currentf->Sup.len < 1);
					if (LOC20) goto LA21;
					nimln(736, "times.nim");
					nimln(736, "times.nim");
					if ((NU)((currentf->Sup.len-1)) > (NU)(currentf->Sup.len)) raiseIndexError();
					if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
					LOC20 = ((NU8)(currentf->data[(currentf->Sup.len-1)]) == (NU8)(f->data[i]));
					LA21: ;
					if (!LOC20) goto LA22;
					nimln(737, "times.nim");
					if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
					currentf = addChar(currentf, f->data[i]);
				}
				goto LA18;
				LA22: ;
				{
					nimln(739, "times.nim");
					formattoken_107266(info, currentf, (&result));
					nimln(740, "times.nim");
					i = subInt(i, 1);
					nimln(741, "times.nim");
					currentf = copyString(((NimStringDesc*) &TMP177));
				}
				LA18: ;
			}
			break;
			}
			nimln(743, "times.nim");
			i = addInt(i, 1);
		}
	} LA1: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void) {
	nimfr("times", "times.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void) {
static TNimNode* TMP155[11];
static TNimNode* TMP156[12];
NI TMP158;
static char* NIM_CONST TMP157[12] = {
"mJan", 
"mFeb", 
"mMar", 
"mApr", 
"mMay", 
"mJun", 
"mJul", 
"mAug", 
"mSep", 
"mOct", 
"mNov", 
"mDec"};
static TNimNode* TMP159[7];
NI TMP161;
static char* NIM_CONST TMP160[7] = {
"dMon", 
"dTue", 
"dWed", 
"dThu", 
"dFri", 
"dSat", 
"dSun"};
static TNimNode TMP137[33];
NTI105405.size = sizeof(timeinfo105405);
NTI105405.kind = 17;
NTI105405.base = (&NTI3211);
TMP155[0] = &TMP137[1];
NTI105408.size = sizeof(NI);
NTI105408.kind = 20;
NTI105408.base = (&NTI108);
NTI105408.flags = 3;
TMP137[1].kind = 1;
TMP137[1].offset = offsetof(timeinfo105405, Second);
TMP137[1].typ = (&NTI105408);
TMP137[1].name = "second";
TMP155[1] = &TMP137[2];
NTI105410.size = sizeof(NI);
NTI105410.kind = 20;
NTI105410.base = (&NTI108);
NTI105410.flags = 3;
TMP137[2].kind = 1;
TMP137[2].offset = offsetof(timeinfo105405, Minute);
TMP137[2].typ = (&NTI105410);
TMP137[2].name = "minute";
TMP155[2] = &TMP137[3];
NTI105412.size = sizeof(NI);
NTI105412.kind = 20;
NTI105412.base = (&NTI108);
NTI105412.flags = 3;
TMP137[3].kind = 1;
TMP137[3].offset = offsetof(timeinfo105405, Hour);
TMP137[3].typ = (&NTI105412);
TMP137[3].name = "hour";
TMP155[3] = &TMP137[4];
NTI105415.size = sizeof(NI);
NTI105415.kind = 20;
NTI105415.base = (&NTI108);
NTI105415.flags = 3;
TMP137[4].kind = 1;
TMP137[4].offset = offsetof(timeinfo105405, Monthday);
TMP137[4].typ = (&NTI105415);
TMP137[4].name = "monthday";
TMP155[4] = &TMP137[5];
NTI102006.size = sizeof(NU8);
NTI102006.kind = 14;
NTI102006.base = 0;
NTI102006.flags = 3;
for (TMP158 = 0; TMP158 < 12; TMP158++) {
TMP137[TMP158+6].kind = 1;
TMP137[TMP158+6].offset = TMP158;
TMP137[TMP158+6].name = TMP157[TMP158];
TMP156[TMP158] = &TMP137[TMP158+6];
}
TMP137[18].len = 12; TMP137[18].kind = 2; TMP137[18].sons = &TMP156[0];
NTI102006.node = &TMP137[18];
TMP137[5].kind = 1;
TMP137[5].offset = offsetof(timeinfo105405, Month);
TMP137[5].typ = (&NTI102006);
TMP137[5].name = "month";
TMP155[5] = &TMP137[19];
NTI105418.size = sizeof(NI);
NTI105418.kind = 20;
NTI105418.base = (&NTI108);
NTI105418.flags = 3;
TMP137[19].kind = 1;
TMP137[19].offset = offsetof(timeinfo105405, Year);
TMP137[19].typ = (&NTI105418);
TMP137[19].name = "year";
TMP155[6] = &TMP137[20];
NTI102008.size = sizeof(NU8);
NTI102008.kind = 14;
NTI102008.base = 0;
NTI102008.flags = 3;
for (TMP161 = 0; TMP161 < 7; TMP161++) {
TMP137[TMP161+21].kind = 1;
TMP137[TMP161+21].offset = TMP161;
TMP137[TMP161+21].name = TMP160[TMP161];
TMP159[TMP161] = &TMP137[TMP161+21];
}
TMP137[28].len = 7; TMP137[28].kind = 2; TMP137[28].sons = &TMP159[0];
NTI102008.node = &TMP137[28];
TMP137[20].kind = 1;
TMP137[20].offset = offsetof(timeinfo105405, Weekday);
TMP137[20].typ = (&NTI102008);
TMP137[20].name = "weekday";
TMP155[7] = &TMP137[29];
NTI105424.size = sizeof(NI);
NTI105424.kind = 20;
NTI105424.base = (&NTI108);
NTI105424.flags = 3;
TMP137[29].kind = 1;
TMP137[29].offset = offsetof(timeinfo105405, Yearday);
TMP137[29].typ = (&NTI105424);
TMP137[29].name = "yearday";
TMP155[8] = &TMP137[30];
TMP137[30].kind = 1;
TMP137[30].offset = offsetof(timeinfo105405, Isdst);
TMP137[30].typ = (&NTI138);
TMP137[30].name = "isDST";
TMP155[9] = &TMP137[31];
TMP137[31].kind = 1;
TMP137[31].offset = offsetof(timeinfo105405, Tzname);
TMP137[31].typ = (&NTI149);
TMP137[31].name = "tzname";
TMP155[10] = &TMP137[32];
TMP137[32].kind = 1;
TMP137[32].offset = offsetof(timeinfo105405, Timezone);
TMP137[32].typ = (&NTI108);
TMP137[32].name = "timezone";
TMP137[0].len = 11; TMP137[0].kind = 2; TMP137[0].sons = &TMP155[0];
NTI105405.node = &TMP137[0];
}

