/* Generated by Nimrod Compiler v0.9.6 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nimrod\lib -o c:\users\simon\rationalnes_\nimcache\graphics.o c:\users\simon\rationalnes_\nimcache\graphics.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <math.h>
typedef struct tcolor215033 tcolor215033;
typedef struct TY211193 TY211193;
typedef struct tsurface222011 tsurface222011;
typedef struct tpixelformat215045 tpixelformat215045;
typedef struct tsurface215055 tsurface215055;
typedef struct trect215027 trect215027;
typedef struct trect222005 trect222005;
typedef struct egraphics222013 egraphics222013;
typedef struct eio2837 eio2837;
typedef struct esystem2835 esystem2835;
typedef struct esynch2833 esynch2833;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tcell43933 tcell43933;
typedef struct tcellseq43949 tcellseq43949;
typedef struct tgcheap46016 tgcheap46016;
typedef struct tcellset43945 tcellset43945;
typedef struct tpagedesc43941 tpagedesc43941;
typedef struct tmemregion26210 tmemregion26210;
typedef struct tsmallchunk25440 tsmallchunk25440;
typedef struct tllchunk26204 tllchunk26204;
typedef struct tbigchunk25442 tbigchunk25442;
typedef struct tintset25417 tintset25417;
typedef struct ttrunk25413 ttrunk25413;
typedef struct tavlnode26208 tavlnode26208;
typedef struct tgcstat46014 tgcstat46014;
typedef struct tfont222015 tfont222015;
typedef struct tfont221221 tfont221221;
typedef struct TY187006 TY187006;
typedef struct TY224151 TY224151;
typedef struct tpalette215041 tpalette215041;
typedef struct tbasechunk25438 tbasechunk25438;
typedef struct tfreecell25430 tfreecell25430;
struct  tcolor215033  {
NU8 R;
NU8 G;
NU8 B;
NU8 Unused;
};
struct TY211193 {
NI Field0;
NI Field1;
NI Field2;
};
typedef N_CDECL_PTR(NI32, TY219235) (tpixelformat215045* format, NU8 r, NU8 g, NU8 b, NU8 a);
struct  tsurface222011  {
NI W;
NI H;
tsurface215055* S;
};
struct  trect215027  {
NI16 X;
NI16 Y;
NU16 W;
NU16 H;
};
struct  tsurface215055  {
NI32 Flags;
tpixelformat215045* Format;
int W;
int H;
NU16 Pitch;
void* Pixels;
int Offset;
void* Hwdata;
trect215027 Cliprect;
NI32 Unused1;
NI32 Locked;
void* Blitmap;
int Formatversion;
int Refcount;
};
struct trect222005 {
NI Field0;
NI Field1;
NI Field2;
NI Field3;
};
typedef N_NIMCALL_PTR(void, TY2689) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY2694) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2689 marker;
TY2694 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  E_Base  {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  esynch2833  {
  E_Base Sup;
};
struct  esystem2835  {
  esynch2833 Sup;
};
struct  eio2837  {
  esystem2835 Sup;
};
struct  egraphics222013  {
  eio2837 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NCSTRING, TY218411) (void);
struct  tcell43933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq43949  {
NI Len;
NI Cap;
tcell43933** D;
};
struct  tcellset43945  {
NI Counter;
NI Max;
tpagedesc43941* Head;
tpagedesc43941** Data;
};
typedef tsmallchunk25440* TY26222[512];
typedef ttrunk25413* ttrunkbuckets25415[256];
struct  tintset25417  {
ttrunkbuckets25415 Data;
};
struct  tmemregion26210  {
NI Minlargeobj;
NI Maxlargeobj;
TY26222 Freesmallchunks;
tllchunk26204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk25442* Freechunkslist;
tintset25417 Chunkstarts;
tavlnode26208* Root;
tavlnode26208* Deleted;
tavlnode26208* Last;
tavlnode26208* Freeavlnodes;
};
struct  tgcstat46014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap46016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq43949 Zct;
tcellseq43949 Decstack;
tcellset43945 Cycleroots;
tcellseq43949 Tempstack;
NI Recgclock;
tmemregion26210 Region;
tgcstat46014 Stat;
};
typedef N_CDECL_PTR(void, TY219313) (tsurface215055* surface);
typedef N_CDECL_PTR(tsurface215055*, TY219286) (NI32 flags, NI width, NI height, NI depth, NI32 rmask, NI32 gmask, NI32 bmask, NI32 amask);
typedef N_CDECL_PTR(void, TY221481) (tfont221221* font);
struct  tfont222015  {
tfont221221* F;
tcolor215033 Color;
};
typedef N_CDECL_PTR(tfont221221*, TY221246) (NCSTRING filename, int ptsize);
typedef N_CDECL_PTR(tsurface215055*, TY219150) (NI width, NI height, NI bpp, NU32 flags);
struct TY187006 {
NI Field0;
NI Field1;
};
typedef N_CDECL_PTR(int, TY221367) (tfont221221* font, NCSTRING text, NI32* w, NI32* y);
typedef N_CDECL_PTR(tsurface215055*, TY221449) (tfont221221* font, NCSTRING text, tcolor215033 fg);
typedef N_CDECL_PTR(tsurface215055*, TY221413) (tfont221221* font, NCSTRING text, tcolor215033 fg, tcolor215033 bg);
typedef N_CDECL_PTR(NI, TY219430) (tsurface215055* dst, trect215027* dstrect, NI32 color);
struct TY224151 {
NF Field0;
NF Field1;
NF Field2;
NF Field3;
};
typedef N_CDECL_PTR(NI, TY218226) (NI32 flags);
typedef N_CDECL_PTR(int, TY221241) (void);
struct  tpixelformat215045  {
tpalette215041* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
NI32 Rmask;
NI32 Gmask;
NI32 Bmask;
NI32 Amask;
NI32 Colorkey;
NU8 Alpha;
};
typedef NI TY25420[8];
struct  tpagedesc43941  {
tpagedesc43941* Next;
NI Key;
TY25420 Bits;
};
struct  tbasechunk25438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk25440  {
  tbasechunk25438 Sup;
tsmallchunk25440* Next;
tsmallchunk25440* Prev;
tfreecell25430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk26204  {
NI Size;
NI Acc;
tllchunk26204* Next;
};
struct  tbigchunk25442  {
  tbasechunk25438 Sup;
tbigchunk25442* Next;
tbigchunk25442* Prev;
NI Align;
NF Data;
};
struct  ttrunk25413  {
ttrunk25413* Next;
NI Key;
TY25420 Bits;
};
typedef tavlnode26208* TY26214[2];
struct  tavlnode26208  {
TY26214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfont221221  {
char dummy;
};
struct  tpalette215041  {
NI Ncolors;
tcolor215033* Colors;
};
struct  tfreecell25430  {
tfreecell25430* Next;
NI Zerofield;
};
N_NIMCALL(tcolor215033, tosdlcolor_222035)(NI c);
N_NIMCALL(TY211193, extractrgb_211190)(NI a);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_17801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI32, createsdlcolor_222053)(tsurface222011* sur, NI c, NI alpha);
N_NIMCALL(trect215027, tosdlrect_222074)(trect222005* r);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, raiseegraphics_222085)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP722)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell43933*, usrtocell_47646)(void* usr);
static N_INLINE(void, rtladdzct_49204)(tcell43933* c);
N_NOINLINE(void, addzct_47617)(tcellseq43949* s, tcell43933* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
N_NIMCALL(void, surfacefinalizer_222114)(tsurface222011* s);
N_NIMCALL(tsurface222011*, newsurface_222123)(NI width, NI height);
N_NIMCALL(void, TMP729)(void* p, NI op);
N_NIMCALL(NIM_BOOL, mustlock_219318)(tsurface215055* surface);
N_NIMCALL(void, failedassertimpl_85825)(NimStringDesc* msg);
N_NIMCALL(void, fontfinalizer_222207)(tfont222015* f);
N_NIMCALL(tfont222015*, newfont_222216)(NimStringDesc* name, NI size, NI color);
N_NIMCALL(void, TMP732)(void* p, NI op);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, initdefaultfont_222301)(NimStringDesc* name, NI size, NI color);
N_NIMCALL(tsurface222011*, newscreensurface_222312)(NI width, NI height);
N_NIMCALL(void, writetobmp_222370)(tsurface222011* sur, NimStringDesc* filename);
N_NIMCALL(NI, savebmp_219357)(tsurface215055* surface, NCSTRING filename);
static N_INLINE(NI, getpixel_222439)(tsurface222011* sur, NI x, NI y);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, setpixel_222819)(tsurface222011* sur, NI x, NI y, NI col);
N_NIMCALL(NI, HEX5BHEX5D_223219)(tsurface222011* sur, TY187006 p);
N_NIMCALL(NI, HEX5BHEX5D_223230)(tsurface222011* sur, NI x, NI y);
N_NIMCALL(void, HEX5BHEX5DHEX3D_223242)(tsurface222011* sur, TY187006 p, NI col);
N_NIMCALL(void, HEX5BHEX5DHEX3D_223253)(tsurface222011* sur, NI x, NI y, NI col);
N_NIMCALL(void, blit_223265)(tsurface222011* destsurf, trect222005* destrect, tsurface222011* srcsurf, trect222005* srcrect);
N_NIMCALL(NI, blitsurface_219402)(tsurface215055* src, trect215027* srcrect, tsurface215055* dst, trect215027* dstrect);
N_NIMCALL(TY187006, textbounds_223282)(NimStringDesc* text, tfont222015* font);
N_NIMCALL(void, drawtext_223306)(tsurface222011* sur, TY187006 p, NimStringDesc* text, tfont222015* font);
N_NIMCALL(void, drawtext_223352)(tsurface222011* sur, TY187006 p, NimStringDesc* text, NI bg, tfont222015* font);
N_NIMCALL(void, drawcircle_223399)(tsurface222011* sur, TY187006 p, NI r, NI color);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI, HEX3EHEX2DHEX3C_223538)(NI val, tsurface222011* s);
static N_INLINE(NI, HEX3EHEX7CHEX3C_223551)(NI val, tsurface222011* s);
N_NIMCALL(void, drawline_223564)(tsurface222011* sur, TY187006 p1, TY187006 p2, NI color);
N_NIMCALL(void, drawhorline_223609)(tsurface222011* sur, NI x, NI y, NI w, NI color);
N_NIMCALL(void, drawverline_223655)(tsurface222011* sur, NI x, NI y, NI h, NI color);
N_NIMCALL(void, fillcircle_223701)(tsurface222011* s, TY187006 p, NI r, NI color);
N_NIMCALL(void, drawrect_223727)(tsurface222011* sur, trect222005* r, NI color);
N_NIMCALL(void, fillrect_223802)(tsurface222011* sur, trect222005* r, NI col);
N_NIMCALL(void, plot4ellipsepoints_223815)(tsurface222011* sur, NI cx, NI cy, NI x, NI y, NI col);
N_NIMCALL(void, drawellipse_223840)(tsurface222011* sur, NI cx, NI cy, NI xradius, NI yradius, NI col);
N_NIMCALL(void, plotaa_224094)(tsurface222011* sur, NI x, NI y, NF c, NI color);
N_NIMCALL(NI, HEX2B_211118)(NI a, NI b);
N_NIMCALL(NI, intensity_211215)(NI a, NF f);
N_NIMCALL(void, drawlineaa_224145)(tsurface222011* sur, TY187006 p1, TY187006 p2, NI color);
N_NIMCALL(void, fillsurface_224301)(tsurface222011* sur, NI color);
STRING_LITERAL(TMP730, "not sdl.MustLock(result.s) ", 27);
STRING_LITERAL(TMP733, "Could not open font file: ", 26);
STRING_LITERAL(TMP734, "cannot write: ", 14);
STRING_LITERAL(TMP735, "x <% sur.w ", 11);
STRING_LITERAL(TMP736, "y <% sur.h ", 11);
extern TFrame* frameptr_15242;
extern TY219235 Dl_219234;
extern TNimType NTI2837; /* EIO */
TNimType NTI222013; /* EGraphics */
TNimType NTI222090; /* ref EGraphics */
extern TY218411 Dl_218410;
extern tgcheap46016 gch_46044;
extern TY219313 Dl_219312;
TNimType NTI222011; /* TSurface */
extern TNimType NTI2807; /* Natural */
extern TNimType NTI215051; /* PSurface */
TNimType NTI222009; /* PSurface */
extern TY219286 Dl_219285;
extern TY221481 Dl_221480;
TNimType NTI222015; /* TFont */
extern TNimType NTI221219; /* PFont */
extern TNimType NTI215033; /* TColor */
TNimType NTI222017; /* PFont */
extern TY221246 Dl_221245;
extern TNimType NTI12001; /* ref EIO */
tfont222015* defaultfont_222296;
extern TY219150 Dl_219149;
extern TY221367 Dl_221366;
extern TY221449 Dl_221448;
extern TY221413 Dl_221412;
extern TY219430 Dl_219429;
extern TY218226 Dl_218225;
extern TY221241 Dl_221240;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_15242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_15242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_15242;
	frameptr_15242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_17801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_15242 = (*frameptr_15242).prev;
}

N_NIMCALL(tcolor215033, tosdlcolor_222035)(NI c) {
	tcolor215033 result;
	TY211193 x;
	nimfr("toSdlColor", "graphics.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(37, "graphics.nim");
	x = extractrgb_211190(c);
	nimln(38, "graphics.nim");
	nimln(38, "graphics.nim");
	result.R = ((NU8) ((NI)(((NI) (x.Field0)) & 255)));
	nimln(39, "graphics.nim");
	nimln(39, "graphics.nim");
	result.G = ((NU8) ((NI)(((NI) (x.Field1)) & 255)));
	nimln(40, "graphics.nim");
	nimln(40, "graphics.nim");
	result.B = ((NU8) ((NI)(((NI) (x.Field2)) & 255)));
	popFrame();
	return result;
}

N_NIMCALL(NI32, createsdlcolor_222053)(tsurface222011* sur, NI c, NI alpha) {
	NI32 result;
	TY211193 x;
	nimfr("createSdlColor", "graphics.nim")
	result = 0;
	nimln(44, "graphics.nim");
	x = extractrgb_211190(c);
	nimln(45, "graphics.nim");
	nimln(45, "graphics.nim");
	nimln(45, "graphics.nim");
	nimln(45, "graphics.nim");
	nimln(46, "graphics.nim");
	nimln(46, "graphics.nim");
	result = Dl_219234((*(*sur).S).Format, ((NU8) ((NI)(((NI) (x.Field0)) & 255))), ((NU8) ((NI)(((NI) (x.Field1)) & 255))), ((NU8) ((NI)(((NI) (x.Field2)) & 255))), ((NU8) ((NI)(alpha & 255))));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(trect215027, tosdlrect_222074)(trect222005* r) {
	trect215027 result;
	nimfr("toSdlRect", "graphics.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(50, "graphics.nim");
	result.X = ((NI16)chckRange((*r).Field0, ((NI16) -32768), ((NI16) 32767)));
	nimln(51, "graphics.nim");
	result.Y = ((NI16)chckRange((*r).Field1, ((NI16) -32768), ((NI16) 32767)));
	nimln(52, "graphics.nim");
	result.W = ((NU16) ((*r).Field2));
	nimln(53, "graphics.nim");
	result.H = ((NU16) ((*r).Field3));
	popFrame();
	return result;
}
N_NIMCALL(void, TMP722)(void* p, NI op) {
	egraphics222013* a;
	a = (egraphics222013*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.Sup.trace, op);
}

static N_INLINE(tcell43933*, usrtocell_47646)(void* usr) {
	tcell43933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell43933*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell43933))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_49204)(tcell43933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_47617(&gch_46044.Zct, c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell43933* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_47646(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell43933* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_47646((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_49204(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, raiseegraphics_222085)(void) {
	egraphics222013* e_222089;
	NCSTRING LOC1;
	nimfr("raiseEGraphics", "graphics.nim")
	e_222089 = 0;
	nimln(2121, "system.nim");
	e_222089 = (egraphics222013*) newObj((&NTI222090), sizeof(egraphics222013));
	(*e_222089).Sup.Sup.Sup.Sup.Sup.m_type = (&NTI222013);
	nimln(2122, "system.nim");
	nimln(56, "graphics.nim");
	nimln(56, "graphics.nim");
	LOC1 = 0;
	LOC1 = Dl_218410();
	asgnRefNoCycle((void**) &(*e_222089).Sup.Sup.Sup.Sup.message, cstrToNimstr(LOC1));
	nimln(56, "graphics.nim");
	raiseException((E_Base*)e_222089, "EGraphics");
	popFrame();
}

N_NIMCALL(void, surfacefinalizer_222114)(tsurface222011* s) {
	nimfr("surfaceFinalizer", "graphics.nim")
	nimln(58, "graphics.nim");
	Dl_219312((*s).S);
	popFrame();
}
N_NIMCALL(void, TMP729)(void* p, NI op) {
	tsurface222011* a;
	a = (tsurface222011*)p;
}

N_NIMCALL(tsurface222011*, newsurface_222123)(NI width, NI height) {
	tsurface222011* result;
	nimfr("newSurface", "graphics.nim")
	result = 0;
	nimln(62, "graphics.nim");
	result = (tsurface222011*) newObj((&NTI222009), sizeof(tsurface222011));
	nimln(63, "graphics.nim");
	(*result).W = ((NI)chckRange(width, 0, IL64(9223372036854775807)));
	nimln(64, "graphics.nim");
	(*result).H = ((NI)chckRange(height, 0, IL64(9223372036854775807)));
	nimln(65, "graphics.nim");
	(*result).S = Dl_219285(((NI32) 0), width, height, 32, ((NI32) 16711680), ((NI32) 65280), ((NI32) 255), ((NI32) 0));
	nimln(67, "graphics.nim");
	{
		nimln(67, "graphics.nim");
		if (!((*result).S == NIM_NIL)) goto LA3;
		nimln(68, "graphics.nim");
		raiseegraphics_222085();
	}
	LA3: ;
	nimln(70, "graphics.nim");
	{
		NIM_BOOL LOC7;
		nimln(70, "graphics.nim");
		nimln(70, "graphics.nim");
		nimln(70, "graphics.nim");
		LOC7 = 0;
		LOC7 = mustlock_219318((*result).S);
		if (!!(!(LOC7))) goto LA8;
		nimln(70, "graphics.nim");
		failedassertimpl_85825(((NimStringDesc*) &TMP730));
	}
	LA8: ;
	popFrame();
	return result;
}

N_NIMCALL(void, fontfinalizer_222207)(tfont222015* f) {
	nimfr("fontFinalizer", "graphics.nim")
	nimln(72, "graphics.nim");
	Dl_221480((*f).F);
	popFrame();
}
N_NIMCALL(void, TMP732)(void* p, NI op) {
	tfont222015* a;
	a = (tfont222015*)p;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(tfont222015*, newfont_222216)(NimStringDesc* name, NI size, NI color) {
	tfont222015* result;
	nimfr("newFont", "graphics.nim")
	result = 0;
	nimln(76, "graphics.nim");
	result = (tfont222015*) newObj((&NTI222017), sizeof(tfont222015));
	nimln(77, "graphics.nim");
	(*result).F = Dl_221245(name->data, ((int)chckRange(size, ((int) (-2147483647 -1)), ((int) 2147483647))));
	nimln(78, "graphics.nim");
	{
		eio2837* e_222271;
		NimStringDesc* LOC5;
		nimln(78, "graphics.nim");
		if (!((*result).F == NIM_NIL)) goto LA3;
		e_222271 = 0;
		nimln(2121, "system.nim");
		e_222271 = (eio2837*) newObj((&NTI12001), sizeof(eio2837));
		(*e_222271).Sup.Sup.Sup.Sup.m_type = (&NTI2837);
		nimln(2122, "system.nim");
		nimln(79, "graphics.nim");
		LOC5 = 0;
		LOC5 = rawNewString(name->Sup.len + 26);
appendString(LOC5, ((NimStringDesc*) &TMP733));
appendString(LOC5, name);
		asgnRefNoCycle((void**) &(*e_222271).Sup.Sup.Sup.message, LOC5);
		nimln(79, "graphics.nim");
		raiseException((E_Base*)e_222271, "EIO");
	}
	LA3: ;
	nimln(80, "graphics.nim");
	(*result).Color = tosdlcolor_222035(color);
	popFrame();
	return result;
}

N_NIMCALL(void, initdefaultfont_222301)(NimStringDesc* name, NI size, NI color) {
	nimfr("initDefaultFont", "graphics.nim")
	nimln(88, "graphics.nim");
	asgnRefNoCycle((void**) &defaultfont_222296, newfont_222216(name, size, color));
	popFrame();
}

N_NIMCALL(tsurface222011*, newscreensurface_222312)(NI width, NI height) {
	tsurface222011* result;
	nimfr("newScreenSurface", "graphics.nim")
	result = 0;
	nimln(92, "graphics.nim");
	result = (tsurface222011*) newObj((&NTI222009), sizeof(tsurface222011));
	nimln(93, "graphics.nim");
	(*result).W = ((NI)chckRange(width, 0, IL64(9223372036854775807)));
	nimln(94, "graphics.nim");
	(*result).H = ((NI)chckRange(height, 0, IL64(9223372036854775807)));
	nimln(95, "graphics.nim");
	(*result).S = Dl_219149(width, height, 0, ((NU32) 0));
	nimln(96, "graphics.nim");
	{
		nimln(96, "graphics.nim");
		if (!((*result).S == NIM_NIL)) goto LA3;
		nimln(97, "graphics.nim");
		raiseegraphics_222085();
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void, writetobmp_222370)(tsurface222011* sur, NimStringDesc* filename) {
	nimfr("writeToBMP", "graphics.nim")
	nimln(102, "graphics.nim");
	{
		NI LOC3;
		eio2837* e_222376;
		NimStringDesc* LOC6;
		nimln(102, "graphics.nim");
		nimln(102, "graphics.nim");
		nimln(102, "graphics.nim");
		LOC3 = 0;
		LOC3 = savebmp_219357((*sur).S, filename->data);
		if (!!((LOC3 == 0))) goto LA4;
		e_222376 = 0;
		nimln(2121, "system.nim");
		e_222376 = (eio2837*) newObj((&NTI12001), sizeof(eio2837));
		(*e_222376).Sup.Sup.Sup.Sup.m_type = (&NTI2837);
		nimln(2122, "system.nim");
		nimln(103, "graphics.nim");
		LOC6 = 0;
		LOC6 = rawNewString(filename->Sup.len + 14);
appendString(LOC6, ((NimStringDesc*) &TMP734));
appendString(LOC6, filename);
		asgnRefNoCycle((void**) &(*e_222376).Sup.Sup.Sup.message, LOC6);
		nimln(103, "graphics.nim");
		raiseException((E_Base*)e_222376, "EIO");
	}
	LA4: ;
	popFrame();
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI64)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, getpixel_222439)(tsurface222011* sur, NI x, NI y) {
	NI result;
	NI TMP737;
	NI TMP738;
	NI TMP739;
	nimfr("getPixel", "graphics.nim")
	result = 0;
	nimln(119, "graphics.nim");
	{
		nimln(119, "graphics.nim");
		nimln(119, "graphics.nim");
		if (!!(((NU64)(x) < (NU64)(((NI) ((*sur).W)))))) goto LA3;
		nimln(119, "graphics.nim");
		failedassertimpl_85825(((NimStringDesc*) &TMP735));
	}
	LA3: ;
	nimln(120, "graphics.nim");
	{
		nimln(120, "graphics.nim");
		nimln(120, "graphics.nim");
		if (!!(((NU64)(y) < (NU64)(((NI) ((*sur).H)))))) goto LA7;
		nimln(120, "graphics.nim");
		failedassertimpl_85825(((NimStringDesc*) &TMP736));
	}
	LA7: ;
	nimln(121, "graphics.nim");
	nimln(121, "graphics.nim");
	nimln(121, "graphics.nim");
	nimln(121, "graphics.nim");
	TMP737 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	TMP738 = mulInt(((NI) (y)), (NI64)(TMP737));
	TMP739 = addInt((NI64)(TMP738), ((NI) (x)));
	if ((NU)((NI64)(TMP739)) > (NU)(999999)) raiseIndexError();
	result = ((NI) (((NI32*) ((*(*sur).S).Pixels))[((NI64)(TMP739))- 0]));
	popFrame();
	return result;
}

static N_INLINE(void, setpixel_222819)(tsurface222011* sur, NI x, NI y, NI col) {
	NI32* pixs;
	NI TMP740;
	NI TMP741;
	NI TMP742;
	nimfr("setPixel", "graphics.nim")
	nimln(125, "graphics.nim");
	{
		nimln(125, "graphics.nim");
		nimln(125, "graphics.nim");
		if (!!(((NU64)(x) < (NU64)(((NI) ((*sur).W)))))) goto LA3;
		nimln(125, "graphics.nim");
		failedassertimpl_85825(((NimStringDesc*) &TMP735));
	}
	LA3: ;
	nimln(126, "graphics.nim");
	{
		nimln(126, "graphics.nim");
		nimln(126, "graphics.nim");
		if (!!(((NU64)(y) < (NU64)(((NI) ((*sur).H)))))) goto LA7;
		nimln(126, "graphics.nim");
		failedassertimpl_85825(((NimStringDesc*) &TMP736));
	}
	LA7: ;
	nimln(127, "graphics.nim");
	pixs = ((NI32*) ((*(*sur).S).Pixels));
	nimln(110, "graphics.nim");
	nimln(110, "graphics.nim");
	nimln(110, "graphics.nim");
	nimln(129, "graphics.nim");
	TMP740 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	TMP741 = mulInt(((NI) (y)), (NI64)(TMP740));
	TMP742 = addInt((NI64)(TMP741), ((NI) (x)));
	if ((NU)((NI64)(TMP742)) > (NU)(999999)) raiseIndexError();
	pixs[((NI64)(TMP742))- 0] = ((NI32)chckRange(col, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
	popFrame();
}

N_NIMCALL(NI, HEX5BHEX5D_223219)(tsurface222011* sur, TY187006 p) {
	NI result;
	nimfr("[]", "graphics.nim")
	result = 0;
	nimln(133, "graphics.nim");
	result = getpixel_222439(sur, ((NI)chckRange(p.Field0, 0, IL64(9223372036854775807))), ((NI)chckRange(p.Field1, 0, IL64(9223372036854775807))));
	popFrame();
	return result;
}

N_NIMCALL(NI, HEX5BHEX5D_223230)(tsurface222011* sur, NI x, NI y) {
	NI result;
	nimfr("[]", "graphics.nim")
	result = 0;
	nimln(137, "graphics.nim");
	result = getpixel_222439(sur, ((NI)chckRange(x, 0, IL64(9223372036854775807))), ((NI)chckRange(y, 0, IL64(9223372036854775807))));
	popFrame();
	return result;
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_223242)(tsurface222011* sur, TY187006 p, NI col) {
	nimfr("[]=", "graphics.nim")
	nimln(141, "graphics.nim");
	setpixel_222819(sur, ((NI)chckRange(p.Field0, 0, IL64(9223372036854775807))), ((NI)chckRange(p.Field1, 0, IL64(9223372036854775807))), col);
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_223253)(tsurface222011* sur, NI x, NI y, NI col) {
	nimfr("[]=", "graphics.nim")
	nimln(145, "graphics.nim");
	setpixel_222819(sur, ((NI)chckRange(x, 0, IL64(9223372036854775807))), ((NI)chckRange(y, 0, IL64(9223372036854775807))), col);
	popFrame();
}

N_NIMCALL(void, blit_223265)(tsurface222011* destsurf, trect222005* destrect, tsurface222011* srcsurf, trect222005* srcrect) {
	trect215027 desttrect;
	trect215027 srctrect;
	nimfr("blit", "graphics.nim")
	memset((void*)&desttrect, 0, sizeof(desttrect));
	memset((void*)&srctrect, 0, sizeof(srctrect));
	nimln(152, "graphics.nim");
	desttrect.X = ((NI16)chckRange((*destrect).Field0, ((NI16) -32768), ((NI16) 32767)));
	nimln(153, "graphics.nim");
	desttrect.Y = ((NI16)chckRange((*destrect).Field1, ((NI16) -32768), ((NI16) 32767)));
	nimln(154, "graphics.nim");
	desttrect.W = ((NU16) ((*destrect).Field2));
	nimln(155, "graphics.nim");
	desttrect.H = ((NU16) ((*destrect).Field3));
	nimln(157, "graphics.nim");
	srctrect.X = ((NI16)chckRange((*srcrect).Field0, ((NI16) -32768), ((NI16) 32767)));
	nimln(158, "graphics.nim");
	srctrect.Y = ((NI16)chckRange((*srcrect).Field1, ((NI16) -32768), ((NI16) 32767)));
	nimln(159, "graphics.nim");
	srctrect.W = ((NU16) ((*srcrect).Field2));
	nimln(160, "graphics.nim");
	srctrect.H = ((NU16) ((*srcrect).Field3));
	nimln(162, "graphics.nim");
	{
		NI LOC3;
		nimln(162, "graphics.nim");
		nimln(162, "graphics.nim");
		nimln(162, "graphics.nim");
		LOC3 = 0;
		LOC3 = blitsurface_219402((*srcsurf).S, &srctrect, (*destsurf).S, &desttrect);
		if (!!((LOC3 == 0))) goto LA4;
		nimln(163, "graphics.nim");
		raiseegraphics_222085();
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(TY187006, textbounds_223282)(NimStringDesc* text, tfont222015* font) {
	TY187006 result;
	int w;
	int h;
	nimfr("textBounds", "graphics.nim")
	memset((void*)&result, 0, sizeof(result));
	w = 0;
	h = 0;
	nimln(167, "graphics.nim");
	{
		int LOC3;
		nimln(167, "graphics.nim");
		nimln(167, "graphics.nim");
		LOC3 = 0;
		LOC3 = Dl_221366((*font).F, text->data, &w, &h);
		if (!(LOC3 < ((NI32) 0))) goto LA4;
		nimln(167, "graphics.nim");
		raiseegraphics_222085();
	}
	LA4: ;
	nimln(168, "graphics.nim");
	result.Field0 = ((NI) (w));
	nimln(169, "graphics.nim");
	result.Field1 = ((NI) (h));
	popFrame();
	return result;
}

N_NIMCALL(void, drawtext_223306)(tsurface222011* sur, TY187006 p, NimStringDesc* text, tfont222015* font) {
	tsurface222011* textsur;
	trect222005 LOC1;
	trect222005 LOC2;
	nimfr("drawText", "graphics.nim")
	textsur = 0;
	nimln(175, "graphics.nim");
	textsur = (tsurface222011*) newObj((&NTI222009), sizeof(tsurface222011));
	nimln(178, "graphics.nim");
	(*textsur).S = Dl_221448((*font).F, text->data, (*font).Color);
	nimln(180, "graphics.nim");
	LOC1.Field0 = p.Field0;
	LOC1.Field1 = p.Field1;
	LOC1.Field2 = (*sur).W;
	LOC1.Field3 = (*sur).H;
	LOC2.Field0 = 0;
	LOC2.Field1 = 0;
	LOC2.Field2 = (*sur).W;
	LOC2.Field3 = (*sur).H;
	blit_223265(sur, &LOC1, textsur, &LOC2);
	popFrame();
}

N_NIMCALL(void, drawtext_223352)(tsurface222011* sur, TY187006 p, NimStringDesc* text, NI bg, tfont222015* font) {
	tsurface222011* textsur;
	tcolor215033 LOC1;
	trect222005 LOC2;
	trect222005 LOC3;
	nimfr("drawText", "graphics.nim")
	textsur = 0;
	nimln(187, "graphics.nim");
	textsur = (tsurface222011*) newObj((&NTI222009), sizeof(tsurface222011));
	nimln(188, "graphics.nim");
	nimln(188, "graphics.nim");
	LOC1 = tosdlcolor_222035(bg);
	(*textsur).S = Dl_221412((*font).F, text->data, (*font).Color, LOC1);
	nimln(190, "graphics.nim");
	LOC2.Field0 = p.Field0;
	LOC2.Field1 = p.Field1;
	LOC2.Field2 = (*sur).W;
	LOC2.Field3 = (*sur).H;
	LOC3.Field0 = 0;
	LOC3.Field1 = 0;
	LOC3.Field2 = (*sur).W;
	LOC3.Field3 = (*sur).H;
	blit_223265(sur, &LOC2, textsur, &LOC3);
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, drawcircle_223399)(tsurface222011* sur, TY187006 p, NI r, NI color) {
	NI32* video;
	NI pitch;
	NI TMP743;
	NI a;
	NI TMP744;
	NI py;
	NI px;
	NI x;
	NI y;
	nimfr("drawCircle", "graphics.nim")
	nimln(195, "graphics.nim");
	video = ((NI32*) ((*(*sur).S).Pixels));
	nimln(196, "graphics.nim");
	nimln(196, "graphics.nim");
	TMP743 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	pitch = (NI64)(TMP743);
	nimln(197, "graphics.nim");
	nimln(197, "graphics.nim");
	TMP744 = subInt(1, ((NI) (r)));
	a = (NI64)(TMP744);
	nimln(198, "graphics.nim");
	py = r;
	nimln(199, "graphics.nim");
	px = 0;
	nimln(200, "graphics.nim");
	x = p.Field0;
	nimln(201, "graphics.nim");
	y = p.Field1;
	{
		nimln(202, "graphics.nim");
		while (1) {
			NI TMP745;
			NI TMP798;
			nimln(202, "graphics.nim");
			nimln(202, "graphics.nim");
			TMP745 = addInt(((NI) (py)), 1);
			if (!(px <= ((NI) ((NI64)(TMP745))))) goto LA2;
			nimln(203, "graphics.nim");
			{
				NI TMP746;
				nimln(203, "graphics.nim");
				nimln(203, "graphics.nim");
				TMP746 = addInt(x, px);
				if (!((NU64)((NI64)(TMP746)) < (NU64)(((NI) ((*sur).W))))) goto LA5;
				nimln(204, "graphics.nim");
				{
					NI TMP747;
					NI TMP748;
					NI TMP749;
					NI TMP750;
					NI TMP751;
					nimln(204, "graphics.nim");
					nimln(204, "graphics.nim");
					TMP747 = addInt(y, ((NI) (py)));
					if (!((NU64)((NI64)(TMP747)) < (NU64)(((NI) ((*sur).H))))) goto LA9;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(204, "graphics.nim");
					TMP748 = addInt(y, ((NI) (py)));
					TMP749 = mulInt((NI64)(TMP748), pitch);
					nimln(204, "graphics.nim");
					TMP750 = addInt(x, px);
					TMP751 = addInt((NI64)(TMP749), (NI64)(TMP750));
					if ((NU)((NI64)(TMP751)) > (NU)(999999)) raiseIndexError();
					video[((NI64)(TMP751))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
				}
				LA9: ;
				nimln(205, "graphics.nim");
				{
					NI TMP752;
					NI TMP753;
					NI TMP754;
					NI TMP755;
					NI TMP756;
					nimln(205, "graphics.nim");
					nimln(205, "graphics.nim");
					TMP752 = subInt(y, ((NI) (py)));
					if (!((NU64)((NI64)(TMP752)) < (NU64)(((NI) ((*sur).H))))) goto LA13;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(205, "graphics.nim");
					TMP753 = subInt(y, ((NI) (py)));
					TMP754 = mulInt((NI64)(TMP753), pitch);
					nimln(205, "graphics.nim");
					TMP755 = addInt(x, px);
					TMP756 = addInt((NI64)(TMP754), (NI64)(TMP755));
					if ((NU)((NI64)(TMP756)) > (NU)(999999)) raiseIndexError();
					video[((NI64)(TMP756))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
				}
				LA13: ;
			}
			LA5: ;
			nimln(207, "graphics.nim");
			{
				NI TMP757;
				nimln(207, "graphics.nim");
				nimln(207, "graphics.nim");
				TMP757 = subInt(x, px);
				if (!((NU64)((NI64)(TMP757)) < (NU64)(((NI) ((*sur).W))))) goto LA17;
				nimln(208, "graphics.nim");
				{
					NI TMP758;
					NI TMP759;
					NI TMP760;
					NI TMP761;
					NI TMP762;
					nimln(208, "graphics.nim");
					nimln(208, "graphics.nim");
					TMP758 = addInt(y, ((NI) (py)));
					if (!((NU64)((NI64)(TMP758)) < (NU64)(((NI) ((*sur).H))))) goto LA21;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(208, "graphics.nim");
					TMP759 = addInt(y, ((NI) (py)));
					TMP760 = mulInt((NI64)(TMP759), pitch);
					nimln(208, "graphics.nim");
					TMP761 = subInt(x, px);
					TMP762 = addInt((NI64)(TMP760), (NI64)(TMP761));
					if ((NU)((NI64)(TMP762)) > (NU)(999999)) raiseIndexError();
					video[((NI64)(TMP762))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
				}
				LA21: ;
				nimln(209, "graphics.nim");
				{
					NI TMP763;
					NI TMP764;
					NI TMP765;
					NI TMP766;
					NI TMP767;
					nimln(209, "graphics.nim");
					nimln(209, "graphics.nim");
					TMP763 = subInt(y, ((NI) (py)));
					if (!((NU64)((NI64)(TMP763)) < (NU64)(((NI) ((*sur).H))))) goto LA25;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(209, "graphics.nim");
					TMP764 = subInt(y, ((NI) (py)));
					TMP765 = mulInt((NI64)(TMP764), pitch);
					nimln(209, "graphics.nim");
					TMP766 = subInt(x, px);
					TMP767 = addInt((NI64)(TMP765), (NI64)(TMP766));
					if ((NU)((NI64)(TMP767)) > (NU)(999999)) raiseIndexError();
					video[((NI64)(TMP767))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
				}
				LA25: ;
			}
			LA17: ;
			nimln(211, "graphics.nim");
			{
				NI TMP768;
				nimln(211, "graphics.nim");
				nimln(211, "graphics.nim");
				TMP768 = addInt(x, ((NI) (py)));
				if (!((NU64)((NI64)(TMP768)) < (NU64)(((NI) ((*sur).W))))) goto LA29;
				nimln(212, "graphics.nim");
				{
					NI TMP769;
					NI TMP770;
					NI TMP771;
					NI TMP772;
					NI TMP773;
					nimln(212, "graphics.nim");
					nimln(212, "graphics.nim");
					TMP769 = addInt(y, px);
					if (!((NU64)((NI64)(TMP769)) < (NU64)(((NI) ((*sur).H))))) goto LA33;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(212, "graphics.nim");
					TMP770 = addInt(y, px);
					TMP771 = mulInt((NI64)(TMP770), pitch);
					nimln(212, "graphics.nim");
					TMP772 = addInt(x, ((NI) (py)));
					TMP773 = addInt((NI64)(TMP771), (NI64)(TMP772));
					if ((NU)((NI64)(TMP773)) > (NU)(999999)) raiseIndexError();
					video[((NI64)(TMP773))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
				}
				LA33: ;
				nimln(213, "graphics.nim");
				{
					NI TMP774;
					NI TMP775;
					NI TMP776;
					NI TMP777;
					NI TMP778;
					nimln(213, "graphics.nim");
					nimln(213, "graphics.nim");
					TMP774 = subInt(y, px);
					if (!((NU64)((NI64)(TMP774)) < (NU64)(((NI) ((*sur).H))))) goto LA37;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(213, "graphics.nim");
					TMP775 = subInt(y, px);
					TMP776 = mulInt((NI64)(TMP775), pitch);
					nimln(213, "graphics.nim");
					TMP777 = addInt(x, ((NI) (py)));
					TMP778 = addInt((NI64)(TMP776), (NI64)(TMP777));
					if ((NU)((NI64)(TMP778)) > (NU)(999999)) raiseIndexError();
					video[((NI64)(TMP778))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
				}
				LA37: ;
			}
			LA29: ;
			nimln(215, "graphics.nim");
			{
				NI TMP779;
				nimln(215, "graphics.nim");
				nimln(215, "graphics.nim");
				TMP779 = subInt(x, ((NI) (py)));
				if (!((NU64)((NI64)(TMP779)) < (NU64)(((NI) ((*sur).W))))) goto LA41;
				nimln(216, "graphics.nim");
				{
					NI TMP780;
					NI TMP781;
					NI TMP782;
					NI TMP783;
					NI TMP784;
					nimln(216, "graphics.nim");
					nimln(216, "graphics.nim");
					TMP780 = addInt(y, px);
					if (!((NU64)((NI64)(TMP780)) < (NU64)(((NI) ((*sur).H))))) goto LA45;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(216, "graphics.nim");
					TMP781 = addInt(y, px);
					TMP782 = mulInt((NI64)(TMP781), pitch);
					nimln(216, "graphics.nim");
					TMP783 = subInt(x, ((NI) (py)));
					TMP784 = addInt((NI64)(TMP782), (NI64)(TMP783));
					if ((NU)((NI64)(TMP784)) > (NU)(999999)) raiseIndexError();
					video[((NI64)(TMP784))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
				}
				LA45: ;
				nimln(217, "graphics.nim");
				{
					NI TMP785;
					NI TMP786;
					NI TMP787;
					NI TMP788;
					NI TMP789;
					nimln(217, "graphics.nim");
					nimln(217, "graphics.nim");
					TMP785 = subInt(y, px);
					if (!((NU64)((NI64)(TMP785)) < (NU64)(((NI) ((*sur).H))))) goto LA49;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(217, "graphics.nim");
					TMP786 = subInt(y, px);
					TMP787 = mulInt((NI64)(TMP786), pitch);
					nimln(217, "graphics.nim");
					TMP788 = subInt(x, ((NI) (py)));
					TMP789 = addInt((NI64)(TMP787), (NI64)(TMP788));
					if ((NU)((NI64)(TMP789)) > (NU)(999999)) raiseIndexError();
					video[((NI64)(TMP789))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
				}
				LA49: ;
			}
			LA41: ;
			nimln(219, "graphics.nim");
			{
				NI TMP790;
				NI TMP791;
				NI TMP792;
				nimln(219, "graphics.nim");
				if (!(a < 0)) goto LA53;
				nimln(220, "graphics.nim");
				nimln(220, "graphics.nim");
				nimln(220, "graphics.nim");
				nimln(220, "graphics.nim");
				TMP790 = mulInt(2, px);
				TMP791 = addInt((NI64)(TMP790), 3);
				TMP792 = addInt(a, (NI64)(TMP791));
				a = (NI64)(TMP792);
			}
			goto LA51;
			LA53: ;
			{
				NI TMP793;
				NI TMP794;
				NI TMP795;
				NI TMP796;
				NI TMP797;
				nimln(222, "graphics.nim");
				nimln(222, "graphics.nim");
				nimln(222, "graphics.nim");
				nimln(222, "graphics.nim");
				nimln(222, "graphics.nim");
				TMP793 = subInt(px, ((NI) (py)));
				TMP794 = mulInt(2, (NI64)(TMP793));
				TMP795 = addInt((NI64)(TMP794), 5);
				TMP796 = addInt(a, (NI64)(TMP795));
				a = (NI64)(TMP796);
				nimln(223, "graphics.nim");
				nimln(223, "graphics.nim");
				TMP797 = subInt(((NI) (py)), 1);
				py = ((NI)chckRange((NI64)(TMP797), 0, IL64(9223372036854775807)));
			}
			LA51: ;
			nimln(224, "graphics.nim");
			nimln(224, "graphics.nim");
			TMP798 = addInt(px, 1);
			px = (NI64)(TMP798);
		} LA2: ;
	}
	popFrame();
}

static N_INLINE(NI, HEX3EHEX2DHEX3C_223538)(NI val, tsurface222011* s) {
	NI result;
	nimfr(">-<", "graphics.nim")
	result = 0;
	nimln(227, "graphics.nim");
	nimln(227, "graphics.nim");
	nimln(227, "graphics.nim");
	{
		nimln(227, "graphics.nim");
		if (!(val < 0)) goto LA3;
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		NI TMP799;
		nimln(227, "graphics.nim");
		if (!(((NI) ((*s).W)) <= val)) goto LA6;
		nimln(227, "graphics.nim");
		TMP799 = subInt(((NI) ((*s).W)), 1);
		result = ((NI) ((NI64)(TMP799)));
	}
	goto LA1;
	LA6: ;
	{
		result = val;
	}
	LA1: ;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, HEX3EHEX7CHEX3C_223551)(NI val, tsurface222011* s) {
	NI result;
	nimfr(">|<", "graphics.nim")
	result = 0;
	nimln(230, "graphics.nim");
	nimln(230, "graphics.nim");
	nimln(230, "graphics.nim");
	{
		nimln(230, "graphics.nim");
		if (!(val < 0)) goto LA3;
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		NI TMP800;
		nimln(230, "graphics.nim");
		if (!(((NI) ((*s).H)) <= val)) goto LA6;
		nimln(230, "graphics.nim");
		TMP800 = subInt(((NI) ((*s).H)), 1);
		result = ((NI) ((NI64)(TMP800)));
	}
	goto LA1;
	LA6: ;
	{
		result = val;
	}
	LA1: ;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, drawline_223564)(tsurface222011* sur, TY187006 p1, TY187006 p2, NI color) {
	NI stepx;
	NI stepy;
	NI x0;
	NI x1;
	NI y0;
	NI y1;
	NI dy;
	NI TMP801;
	NI dx;
	NI TMP802;
	NI TMP803;
	NI TMP804;
	NI32* video;
	NI pitch;
	NI TMP805;
	NI TMP806;
	NI TMP807;
	nimfr("drawLine", "graphics.nim")
	nimln(235, "graphics.nim");
	stepx = 0;
	nimln(235, "graphics.nim");
	stepy = 0;
	nimln(236, "graphics.nim");
	x0 = HEX3EHEX2DHEX3C_223538(p1.Field0, sur);
	nimln(237, "graphics.nim");
	x1 = HEX3EHEX2DHEX3C_223538(p2.Field0, sur);
	nimln(238, "graphics.nim");
	y0 = HEX3EHEX7CHEX3C_223551(p1.Field1, sur);
	nimln(239, "graphics.nim");
	y1 = HEX3EHEX7CHEX3C_223551(p2.Field1, sur);
	nimln(240, "graphics.nim");
	nimln(240, "graphics.nim");
	TMP801 = subInt(y1, y0);
	dy = (NI64)(TMP801);
	nimln(241, "graphics.nim");
	nimln(241, "graphics.nim");
	TMP802 = subInt(x1, x0);
	dx = (NI64)(TMP802);
	nimln(242, "graphics.nim");
	{
		nimln(242, "graphics.nim");
		if (!(dy < 0)) goto LA3;
		nimln(243, "graphics.nim");
		nimln(243, "graphics.nim");
		if (dy == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
		dy = ((NI64)-(dy));
		nimln(244, "graphics.nim");
		stepy = -1;
	}
	goto LA1;
	LA3: ;
	{
		nimln(246, "graphics.nim");
		stepy = 1;
	}
	LA1: ;
	nimln(247, "graphics.nim");
	{
		nimln(247, "graphics.nim");
		if (!(dx < 0)) goto LA8;
		nimln(248, "graphics.nim");
		nimln(248, "graphics.nim");
		if (dx == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
		dx = ((NI64)-(dx));
		nimln(249, "graphics.nim");
		stepx = -1;
	}
	goto LA6;
	LA8: ;
	{
		nimln(251, "graphics.nim");
		stepx = 1;
	}
	LA6: ;
	nimln(252, "graphics.nim");
	nimln(252, "graphics.nim");
	TMP803 = mulInt(dy, 2);
	dy = (NI64)(TMP803);
	nimln(253, "graphics.nim");
	nimln(253, "graphics.nim");
	TMP804 = mulInt(dx, 2);
	dx = (NI64)(TMP804);
	nimln(254, "graphics.nim");
	video = ((NI32*) ((*(*sur).S).Pixels));
	nimln(255, "graphics.nim");
	nimln(255, "graphics.nim");
	TMP805 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	pitch = (NI64)(TMP805);
	nimln(110, "graphics.nim");
	nimln(110, "graphics.nim");
	nimln(110, "graphics.nim");
	TMP806 = mulInt(y0, pitch);
	TMP807 = addInt((NI64)(TMP806), x0);
	if ((NU)((NI64)(TMP807)) > (NU)(999999)) raiseIndexError();
	video[((NI64)(TMP807))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
	nimln(257, "graphics.nim");
	{
		NI fraction;
		NI TMP808;
		NI TMP809;
		nimln(257, "graphics.nim");
		if (!(dy < dx)) goto LA13;
		nimln(258, "graphics.nim");
		nimln(258, "graphics.nim");
		nimln(258, "graphics.nim");
		TMP808 = divInt(dx, 2);
		TMP809 = subInt(dy, (NI64)(TMP808));
		fraction = (NI64)(TMP809);
		{
			nimln(259, "graphics.nim");
			while (1) {
				NI TMP812;
				NI TMP813;
				NI TMP814;
				NI TMP815;
				nimln(259, "graphics.nim");
				nimln(259, "graphics.nim");
				if (!!((x0 == x1))) goto LA16;
				nimln(260, "graphics.nim");
				{
					NI TMP810;
					NI TMP811;
					nimln(260, "graphics.nim");
					if (!(0 <= fraction)) goto LA19;
					nimln(261, "graphics.nim");
					nimln(261, "graphics.nim");
					TMP810 = addInt(y0, stepy);
					y0 = (NI64)(TMP810);
					nimln(262, "graphics.nim");
					nimln(262, "graphics.nim");
					TMP811 = subInt(fraction, dx);
					fraction = (NI64)(TMP811);
				}
				LA19: ;
				nimln(263, "graphics.nim");
				nimln(263, "graphics.nim");
				TMP812 = addInt(x0, stepx);
				x0 = (NI64)(TMP812);
				nimln(264, "graphics.nim");
				nimln(264, "graphics.nim");
				TMP813 = addInt(fraction, dy);
				fraction = (NI64)(TMP813);
				nimln(110, "graphics.nim");
				nimln(110, "graphics.nim");
				nimln(110, "graphics.nim");
				TMP814 = mulInt(y0, pitch);
				TMP815 = addInt((NI64)(TMP814), x0);
				if ((NU)((NI64)(TMP815)) > (NU)(999999)) raiseIndexError();
				video[((NI64)(TMP815))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
			} LA16: ;
		}
	}
	goto LA11;
	LA13: ;
	{
		NI fraction;
		NI TMP816;
		NI TMP817;
		nimln(267, "graphics.nim");
		nimln(267, "graphics.nim");
		nimln(267, "graphics.nim");
		TMP816 = divInt(dy, 2);
		TMP817 = subInt(dx, (NI64)(TMP816));
		fraction = (NI64)(TMP817);
		{
			nimln(268, "graphics.nim");
			while (1) {
				NI TMP820;
				NI TMP821;
				NI TMP822;
				NI TMP823;
				nimln(268, "graphics.nim");
				nimln(268, "graphics.nim");
				if (!!((y0 == y1))) goto LA23;
				nimln(269, "graphics.nim");
				{
					NI TMP818;
					NI TMP819;
					nimln(269, "graphics.nim");
					if (!(0 <= fraction)) goto LA26;
					nimln(270, "graphics.nim");
					nimln(270, "graphics.nim");
					TMP818 = addInt(x0, stepx);
					x0 = (NI64)(TMP818);
					nimln(271, "graphics.nim");
					nimln(271, "graphics.nim");
					TMP819 = subInt(fraction, dy);
					fraction = (NI64)(TMP819);
				}
				LA26: ;
				nimln(272, "graphics.nim");
				nimln(272, "graphics.nim");
				TMP820 = addInt(y0, stepy);
				y0 = (NI64)(TMP820);
				nimln(273, "graphics.nim");
				nimln(273, "graphics.nim");
				TMP821 = addInt(fraction, dx);
				fraction = (NI64)(TMP821);
				nimln(110, "graphics.nim");
				nimln(110, "graphics.nim");
				nimln(110, "graphics.nim");
				TMP822 = mulInt(y0, pitch);
				TMP823 = addInt((NI64)(TMP822), x0);
				if ((NU)((NI64)(TMP823)) > (NU)(999999)) raiseIndexError();
				video[((NI64)(TMP823))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
			} LA23: ;
		}
	}
	LA11: ;
	popFrame();
}

N_NIMCALL(void, drawhorline_223609)(tsurface222011* sur, NI x, NI y, NI w, NI color) {
	NI32* video;
	NI pitch;
	NI TMP824;
	nimfr("drawHorLine", "graphics.nim")
	nimln(278, "graphics.nim");
	video = ((NI32*) ((*(*sur).S).Pixels));
	nimln(279, "graphics.nim");
	nimln(279, "graphics.nim");
	TMP824 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	pitch = (NI64)(TMP824);
	nimln(281, "graphics.nim");
	{
		NIM_BOOL LOC3;
		nimln(281, "graphics.nim");
		LOC3 = 0;
		nimln(281, "graphics.nim");
		LOC3 = (0 <= ((NI) (y)));
		if (!(LOC3)) goto LA4;
		nimln(281, "graphics.nim");
		LOC3 = (((NI) (y)) <= ((NI) ((*(*sur).S).H)));
		LA4: ;
		if (!LOC3) goto LA5;
		{
			NI i_223631;
			NI HEX3Atmp_223635;
			NI TMP825;
			NI TMP826;
			NI res_223638;
			i_223631 = 0;
			HEX3Atmp_223635 = 0;
			nimln(282, "graphics.nim");
			nimln(282, "graphics.nim");
			nimln(282, "graphics.nim");
			nimln(282, "graphics.nim");
			TMP825 = subInt(((NI) ((*(*sur).S).W)), ((NI) (x)));
			TMP826 = subInt((((NI64)(TMP825) <= ((NI) (w))) ? (NI64)(TMP825) : ((NI) (w))), 1);
			HEX3Atmp_223635 = (NI64)(TMP826);
			nimln(1551, "system.nim");
			res_223638 = 0;
			{
				nimln(1552, "system.nim");
				while (1) {
					NI TMP827;
					NI TMP828;
					NI TMP829;
					nimln(1552, "system.nim");
					if (!(res_223638 <= HEX3Atmp_223635)) goto LA9;
					nimln(1551, "system.nim");
					i_223631 = res_223638;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					TMP827 = mulInt(((NI) (y)), pitch);
					nimln(283, "graphics.nim");
					TMP828 = addInt(((NI) (x)), i_223631);
					TMP829 = addInt((NI64)(TMP827), (NI64)(TMP828));
					if ((NU)((NI64)(TMP829)) > (NU)(999999)) raiseIndexError();
					video[((NI64)(TMP829))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
					nimln(1554, "system.nim");
					res_223638 = addInt(res_223638, 1);
				} LA9: ;
			}
		}
	}
	LA5: ;
	popFrame();
}

N_NIMCALL(void, drawverline_223655)(tsurface222011* sur, NI x, NI y, NI h, NI color) {
	NI32* video;
	NI pitch;
	NI TMP830;
	nimfr("drawVerLine", "graphics.nim")
	nimln(287, "graphics.nim");
	video = ((NI32*) ((*(*sur).S).Pixels));
	nimln(288, "graphics.nim");
	nimln(288, "graphics.nim");
	TMP830 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	pitch = (NI64)(TMP830);
	nimln(290, "graphics.nim");
	{
		NIM_BOOL LOC3;
		nimln(290, "graphics.nim");
		LOC3 = 0;
		nimln(290, "graphics.nim");
		LOC3 = (0 <= ((NI) (x)));
		if (!(LOC3)) goto LA4;
		nimln(290, "graphics.nim");
		LOC3 = (((NI) (x)) <= ((NI) ((*(*sur).S).W)));
		LA4: ;
		if (!LOC3) goto LA5;
		{
			NI i_223677;
			NI HEX3Atmp_223681;
			NI TMP831;
			NI TMP832;
			NI res_223684;
			i_223677 = 0;
			HEX3Atmp_223681 = 0;
			nimln(291, "graphics.nim");
			nimln(291, "graphics.nim");
			nimln(291, "graphics.nim");
			nimln(291, "graphics.nim");
			TMP831 = subInt(((NI) ((*(*sur).S).H)), ((NI) (y)));
			TMP832 = subInt((((NI64)(TMP831) <= ((NI) (h))) ? (NI64)(TMP831) : ((NI) (h))), 1);
			HEX3Atmp_223681 = (NI64)(TMP832);
			nimln(1551, "system.nim");
			res_223684 = 0;
			{
				nimln(1552, "system.nim");
				while (1) {
					NI TMP833;
					NI TMP834;
					NI TMP835;
					nimln(1552, "system.nim");
					if (!(res_223684 <= HEX3Atmp_223681)) goto LA9;
					nimln(1551, "system.nim");
					i_223677 = res_223684;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(292, "graphics.nim");
					TMP833 = addInt(((NI) (y)), i_223677);
					TMP834 = mulInt((NI64)(TMP833), pitch);
					TMP835 = addInt((NI64)(TMP834), ((NI) (x)));
					if ((NU)((NI64)(TMP835)) > (NU)(999999)) raiseIndexError();
					video[((NI64)(TMP835))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
					nimln(1554, "system.nim");
					res_223684 = addInt(res_223684, 1);
				} LA9: ;
			}
		}
	}
	LA5: ;
	popFrame();
}

N_NIMCALL(void, fillcircle_223701)(tsurface222011* s, TY187006 p, NI r, NI color) {
	NI a;
	NI TMP836;
	NI py;
	NI px;
	NI x;
	NI y;
	nimfr("fillCircle", "graphics.nim")
	nimln(297, "graphics.nim");
	nimln(297, "graphics.nim");
	TMP836 = subInt(1, ((NI) (r)));
	a = (NI64)(TMP836);
	nimln(298, "graphics.nim");
	py = ((NI) (r));
	nimln(299, "graphics.nim");
	px = 0;
	nimln(300, "graphics.nim");
	x = p.Field0;
	nimln(301, "graphics.nim");
	y = p.Field1;
	{
		nimln(302, "graphics.nim");
		while (1) {
			NI TMP837;
			NI TMP838;
			NI TMP839;
			NI TMP840;
			NI TMP865;
			nimln(302, "graphics.nim");
			if (!(px <= py)) goto LA2;
			nimln(304, "graphics.nim");
			nimln(304, "graphics.nim");
			TMP837 = addInt(x, px);
			nimln(304, "graphics.nim");
			TMP838 = addInt(py, 1);
			drawverline_223655(s, ((NI)chckRange((NI64)(TMP837), 0, IL64(9223372036854775807))), ((NI)chckRange(y, 0, IL64(9223372036854775807))), ((NI)chckRange((NI64)(TMP838), 0, IL64(9223372036854775807))), color);
			nimln(305, "graphics.nim");
			nimln(305, "graphics.nim");
			TMP839 = addInt(x, px);
			nimln(305, "graphics.nim");
			TMP840 = subInt(y, py);
			drawverline_223655(s, ((NI)chckRange((NI64)(TMP839), 0, IL64(9223372036854775807))), ((NI)chckRange((NI64)(TMP840), 0, IL64(9223372036854775807))), ((NI)chckRange(py, 0, IL64(9223372036854775807))), color);
			nimln(306, "graphics.nim");
			{
				NI TMP841;
				NI TMP842;
				NI TMP843;
				NI TMP844;
				nimln(306, "graphics.nim");
				nimln(306, "graphics.nim");
				if (!!((px == 0))) goto LA5;
				nimln(307, "graphics.nim");
				nimln(307, "graphics.nim");
				TMP841 = subInt(x, px);
				nimln(307, "graphics.nim");
				TMP842 = addInt(py, 1);
				drawverline_223655(s, ((NI)chckRange((NI64)(TMP841), 0, IL64(9223372036854775807))), ((NI)chckRange(y, 0, IL64(9223372036854775807))), ((NI)chckRange((NI64)(TMP842), 0, IL64(9223372036854775807))), color);
				nimln(308, "graphics.nim");
				nimln(308, "graphics.nim");
				TMP843 = subInt(x, px);
				nimln(308, "graphics.nim");
				TMP844 = subInt(y, py);
				drawverline_223655(s, ((NI)chckRange((NI64)(TMP843), 0, IL64(9223372036854775807))), ((NI)chckRange((NI64)(TMP844), 0, IL64(9223372036854775807))), ((NI)chckRange(py, 0, IL64(9223372036854775807))), color);
			}
			LA5: ;
			nimln(309, "graphics.nim");
			{
				NI TMP845;
				NI TMP846;
				NI TMP847;
				nimln(309, "graphics.nim");
				if (!(a < 0)) goto LA9;
				nimln(310, "graphics.nim");
				nimln(310, "graphics.nim");
				nimln(310, "graphics.nim");
				nimln(310, "graphics.nim");
				TMP845 = mulInt(2, px);
				TMP846 = addInt((NI64)(TMP845), 3);
				TMP847 = addInt(a, (NI64)(TMP846));
				a = (NI64)(TMP847);
			}
			goto LA7;
			LA9: ;
			{
				NI TMP848;
				NI TMP849;
				NI TMP850;
				NI TMP851;
				NI TMP852;
				nimln(312, "graphics.nim");
				nimln(312, "graphics.nim");
				nimln(312, "graphics.nim");
				nimln(312, "graphics.nim");
				nimln(312, "graphics.nim");
				TMP848 = subInt(px, py);
				TMP849 = mulInt(2, (NI64)(TMP848));
				TMP850 = addInt((NI64)(TMP849), 5);
				TMP851 = addInt(a, (NI64)(TMP850));
				a = (NI64)(TMP851);
				nimln(313, "graphics.nim");
				nimln(313, "graphics.nim");
				TMP852 = subInt(py, 1);
				py = (NI64)(TMP852);
				nimln(315, "graphics.nim");
				{
					NI TMP853;
					NI TMP854;
					NI TMP855;
					NI TMP856;
					NI TMP857;
					NI TMP858;
					NI TMP859;
					NI TMP860;
					NI TMP861;
					NI TMP862;
					NI TMP863;
					NI TMP864;
					nimln(315, "graphics.nim");
					if (!(px <= py)) goto LA14;
					nimln(316, "graphics.nim");
					nimln(316, "graphics.nim");
					nimln(316, "graphics.nim");
					TMP853 = addInt(x, py);
					TMP854 = addInt((NI64)(TMP853), 1);
					nimln(316, "graphics.nim");
					TMP855 = addInt(px, 1);
					drawverline_223655(s, ((NI)chckRange((NI64)(TMP854), 0, IL64(9223372036854775807))), ((NI)chckRange(y, 0, IL64(9223372036854775807))), ((NI)chckRange((NI64)(TMP855), 0, IL64(9223372036854775807))), color);
					nimln(317, "graphics.nim");
					nimln(317, "graphics.nim");
					nimln(317, "graphics.nim");
					TMP856 = addInt(x, py);
					TMP857 = addInt((NI64)(TMP856), 1);
					nimln(317, "graphics.nim");
					TMP858 = subInt(y, px);
					drawverline_223655(s, ((NI)chckRange((NI64)(TMP857), 0, IL64(9223372036854775807))), ((NI)chckRange((NI64)(TMP858), 0, IL64(9223372036854775807))), ((NI)chckRange(px, 0, IL64(9223372036854775807))), color);
					nimln(318, "graphics.nim");
					nimln(318, "graphics.nim");
					nimln(318, "graphics.nim");
					TMP859 = subInt(x, py);
					TMP860 = subInt((NI64)(TMP859), 1);
					nimln(318, "graphics.nim");
					TMP861 = addInt(px, 1);
					drawverline_223655(s, ((NI)chckRange((NI64)(TMP860), 0, IL64(9223372036854775807))), ((NI)chckRange(y, 0, IL64(9223372036854775807))), ((NI)chckRange((NI64)(TMP861), 0, IL64(9223372036854775807))), color);
					nimln(319, "graphics.nim");
					nimln(319, "graphics.nim");
					nimln(319, "graphics.nim");
					TMP862 = subInt(x, py);
					TMP863 = subInt((NI64)(TMP862), 1);
					nimln(319, "graphics.nim");
					TMP864 = subInt(y, px);
					drawverline_223655(s, ((NI)chckRange((NI64)(TMP863), 0, IL64(9223372036854775807))), ((NI)chckRange((NI64)(TMP864), 0, IL64(9223372036854775807))), ((NI)chckRange(px, 0, IL64(9223372036854775807))), color);
				}
				LA14: ;
			}
			LA7: ;
			nimln(320, "graphics.nim");
			nimln(320, "graphics.nim");
			TMP865 = addInt(px, 1);
			px = (NI64)(TMP865);
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(void, drawrect_223727)(tsurface222011* sur, trect222005* r, NI color) {
	NI32* video;
	NI pitch;
	NI TMP866;
	nimfr("drawRect", "graphics.nim")
	nimln(324, "graphics.nim");
	video = ((NI32*) ((*(*sur).S).Pixels));
	nimln(325, "graphics.nim");
	nimln(325, "graphics.nim");
	TMP866 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	pitch = (NI64)(TMP866);
	nimln(326, "graphics.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NIM_BOOL LOC7;
		NI minw;
		NI TMP867;
		NI minh;
		NI TMP868;
		nimln(326, "graphics.nim");
		LOC3 = 0;
		nimln(326, "graphics.nim");
		LOC4 = 0;
		nimln(326, "graphics.nim");
		LOC4 = (0 <= (*r).Field0);
		if (!(LOC4)) goto LA5;
		nimln(326, "graphics.nim");
		LOC4 = ((*r).Field0 <= ((NI) ((*(*sur).S).W)));
		LA5: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA6;
		nimln(326, "graphics.nim");
		LOC7 = 0;
		nimln(326, "graphics.nim");
		LOC7 = (0 <= (*r).Field1);
		if (!(LOC7)) goto LA8;
		nimln(326, "graphics.nim");
		LOC7 = ((*r).Field1 <= ((NI) ((*(*sur).S).H)));
		LA8: ;
		LOC3 = LOC7;
		LA6: ;
		if (!LOC3) goto LA9;
		nimln(327, "graphics.nim");
		nimln(327, "graphics.nim");
		nimln(327, "graphics.nim");
		TMP867 = subInt(((NI) ((*(*sur).S).W)), (*r).Field0);
		minw = (((NI64)(TMP867) <= (*r).Field2) ? (NI64)(TMP867) : (*r).Field2);
		nimln(328, "graphics.nim");
		nimln(328, "graphics.nim");
		nimln(328, "graphics.nim");
		TMP868 = subInt(((NI) ((*(*sur).S).H)), (*r).Field1);
		minh = (((NI64)(TMP868) <= (*r).Field3) ? (NI64)(TMP868) : (*r).Field3);
		{
			NI i_223752;
			NI HEX3Atmp_223767;
			NI TMP869;
			NI res_223770;
			i_223752 = 0;
			HEX3Atmp_223767 = 0;
			nimln(331, "graphics.nim");
			nimln(331, "graphics.nim");
			TMP869 = subInt(minw, 1);
			HEX3Atmp_223767 = (NI64)(TMP869);
			nimln(1551, "system.nim");
			res_223770 = 0;
			{
				nimln(1552, "system.nim");
				while (1) {
					NI TMP870;
					NI TMP871;
					NI TMP872;
					NI TMP873;
					NI TMP874;
					NI TMP875;
					NI TMP876;
					NI TMP877;
					nimln(1552, "system.nim");
					if (!(res_223770 <= HEX3Atmp_223767)) goto LA13;
					nimln(1551, "system.nim");
					i_223752 = res_223770;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					TMP870 = mulInt((*r).Field1, pitch);
					nimln(332, "graphics.nim");
					TMP871 = addInt((*r).Field0, i_223752);
					TMP872 = addInt((NI64)(TMP870), (NI64)(TMP871));
					if ((NU)((NI64)(TMP872)) > (NU)(999999)) raiseIndexError();
					video[((NI64)(TMP872))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(333, "graphics.nim");
					nimln(333, "graphics.nim");
					TMP873 = addInt((*r).Field1, minh);
					TMP874 = subInt((NI64)(TMP873), 1);
					TMP875 = mulInt((NI64)(TMP874), pitch);
					nimln(333, "graphics.nim");
					TMP876 = addInt((*r).Field0, i_223752);
					TMP877 = addInt((NI64)(TMP875), (NI64)(TMP876));
					if ((NU)((NI64)(TMP877)) > (NU)(999999)) raiseIndexError();
					video[((NI64)(TMP877))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
					nimln(1554, "system.nim");
					res_223770 = addInt(res_223770, 1);
				} LA13: ;
			}
		}
		{
			NI i_223763;
			NI HEX3Atmp_223773;
			NI TMP878;
			NI res_223776;
			i_223763 = 0;
			HEX3Atmp_223773 = 0;
			nimln(336, "graphics.nim");
			nimln(336, "graphics.nim");
			TMP878 = subInt(minh, 1);
			HEX3Atmp_223773 = (NI64)(TMP878);
			nimln(1551, "system.nim");
			res_223776 = 0;
			{
				nimln(1552, "system.nim");
				while (1) {
					NI TMP879;
					NI TMP880;
					NI TMP881;
					NI TMP882;
					NI TMP883;
					NI TMP884;
					NI TMP885;
					NI TMP886;
					nimln(1552, "system.nim");
					if (!(res_223776 <= HEX3Atmp_223773)) goto LA16;
					nimln(1551, "system.nim");
					i_223763 = res_223776;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(337, "graphics.nim");
					TMP879 = addInt((*r).Field1, i_223763);
					TMP880 = mulInt((NI64)(TMP879), pitch);
					TMP881 = addInt((NI64)(TMP880), (*r).Field0);
					if ((NU)((NI64)(TMP881)) > (NU)(999999)) raiseIndexError();
					video[((NI64)(TMP881))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(338, "graphics.nim");
					TMP882 = addInt((*r).Field1, i_223763);
					TMP883 = mulInt((NI64)(TMP882), pitch);
					nimln(338, "graphics.nim");
					nimln(338, "graphics.nim");
					TMP884 = addInt((*r).Field0, minw);
					TMP885 = subInt((NI64)(TMP884), 1);
					TMP886 = addInt((NI64)(TMP883), (NI64)(TMP885));
					if ((NU)((NI64)(TMP886)) > (NU)(999999)) raiseIndexError();
					video[((NI64)(TMP886))- 0] = ((NI32)chckRange(color, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
					nimln(1554, "system.nim");
					res_223776 = addInt(res_223776, 1);
				} LA16: ;
			}
		}
	}
	LA9: ;
	popFrame();
}

N_NIMCALL(void, fillrect_223802)(tsurface222011* sur, trect222005* r, NI col) {
	trect215027 rect;
	nimfr("fillRect", "graphics.nim")
	nimln(342, "graphics.nim");
	rect = tosdlrect_222074(r);
	nimln(343, "graphics.nim");
	{
		NI32 LOC3;
		NI LOC4;
		nimln(343, "graphics.nim");
		nimln(343, "graphics.nim");
		nimln(343, "graphics.nim");
		LOC3 = 0;
		LOC3 = createsdlcolor_222053(sur, col, 0);
		LOC4 = 0;
		LOC4 = Dl_219429((*sur).S, &rect, LOC3);
		if (!(LOC4 == -1)) goto LA5;
		nimln(344, "graphics.nim");
		raiseegraphics_222085();
	}
	LA5: ;
	popFrame();
}

N_NIMCALL(void, plot4ellipsepoints_223815)(tsurface222011* sur, NI cx, NI cy, NI x, NI y, NI col) {
	NI32* video;
	NI pitch;
	NI TMP887;
	nimfr("plot4EllipsePoints", "graphics.nim")
	nimln(347, "graphics.nim");
	video = ((NI32*) ((*(*sur).S).Pixels));
	nimln(348, "graphics.nim");
	nimln(348, "graphics.nim");
	TMP887 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	pitch = (NI64)(TMP887);
	nimln(349, "graphics.nim");
	{
		NI TMP888;
		NI TMP889;
		nimln(349, "graphics.nim");
		nimln(349, "graphics.nim");
		TMP888 = addInt(((NI) (cx)), ((NI) (x)));
		nimln(349, "graphics.nim");
		TMP889 = subInt((*(*sur).S).W, ((NI32) 1));
		if (TMP889 < (-2147483647 -1) || TMP889 > 2147483647) raiseOverflow();
		if (!(((NI) ((NI64)(TMP888))) <= ((NI) ((NI32)(TMP889))))) goto LA3;
		nimln(350, "graphics.nim");
		{
			NI TMP890;
			NI TMP891;
			NI TMP892;
			NI TMP893;
			NI TMP894;
			NI TMP895;
			nimln(350, "graphics.nim");
			nimln(350, "graphics.nim");
			TMP890 = addInt(((NI) (cy)), ((NI) (y)));
			nimln(350, "graphics.nim");
			TMP891 = subInt((*(*sur).S).H, ((NI32) 1));
			if (TMP891 < (-2147483647 -1) || TMP891 > 2147483647) raiseOverflow();
			if (!(((NI) ((NI64)(TMP890))) <= ((NI) ((NI32)(TMP891))))) goto LA7;
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(350, "graphics.nim");
			TMP892 = addInt(((NI) (cy)), ((NI) (y)));
			TMP893 = mulInt(((NI) ((NI64)(TMP892))), pitch);
			nimln(350, "graphics.nim");
			TMP894 = addInt(((NI) (cx)), ((NI) (x)));
			TMP895 = addInt((NI64)(TMP893), ((NI) ((NI64)(TMP894))));
			if ((NU)((NI64)(TMP895)) > (NU)(999999)) raiseIndexError();
			video[((NI64)(TMP895))- 0] = ((NI32)chckRange(col, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
		}
		LA7: ;
		nimln(351, "graphics.nim");
		{
			NI TMP896;
			NI TMP897;
			NI TMP898;
			NI TMP899;
			NI TMP900;
			NI TMP901;
			nimln(351, "graphics.nim");
			nimln(351, "graphics.nim");
			TMP896 = subInt(((NI) (cy)), ((NI) (y)));
			nimln(351, "graphics.nim");
			TMP897 = subInt((*(*sur).S).H, ((NI32) 1));
			if (TMP897 < (-2147483647 -1) || TMP897 > 2147483647) raiseOverflow();
			if (!((NI64)(TMP896) <= ((NI) ((NI32)(TMP897))))) goto LA11;
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(351, "graphics.nim");
			TMP898 = subInt(((NI) (cy)), ((NI) (y)));
			TMP899 = mulInt((NI64)(TMP898), pitch);
			nimln(351, "graphics.nim");
			TMP900 = addInt(((NI) (cx)), ((NI) (x)));
			TMP901 = addInt((NI64)(TMP899), ((NI) ((NI64)(TMP900))));
			if ((NU)((NI64)(TMP901)) > (NU)(999999)) raiseIndexError();
			video[((NI64)(TMP901))- 0] = ((NI32)chckRange(col, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
		}
		LA11: ;
	}
	LA3: ;
	nimln(352, "graphics.nim");
	{
		NI TMP902;
		NI TMP903;
		nimln(352, "graphics.nim");
		nimln(352, "graphics.nim");
		TMP902 = subInt(((NI) (cx)), ((NI) (x)));
		nimln(352, "graphics.nim");
		TMP903 = subInt((*(*sur).S).W, ((NI32) 1));
		if (TMP903 < (-2147483647 -1) || TMP903 > 2147483647) raiseOverflow();
		if (!((NI64)(TMP902) <= ((NI) ((NI32)(TMP903))))) goto LA15;
		nimln(353, "graphics.nim");
		{
			NI TMP904;
			NI TMP905;
			NI TMP906;
			NI TMP907;
			NI TMP908;
			NI TMP909;
			nimln(353, "graphics.nim");
			nimln(353, "graphics.nim");
			TMP904 = addInt(((NI) (cy)), ((NI) (y)));
			nimln(353, "graphics.nim");
			TMP905 = subInt((*(*sur).S).H, ((NI32) 1));
			if (TMP905 < (-2147483647 -1) || TMP905 > 2147483647) raiseOverflow();
			if (!(((NI) ((NI64)(TMP904))) <= ((NI) ((NI32)(TMP905))))) goto LA19;
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(353, "graphics.nim");
			TMP906 = addInt(((NI) (cy)), ((NI) (y)));
			TMP907 = mulInt(((NI) ((NI64)(TMP906))), pitch);
			nimln(353, "graphics.nim");
			TMP908 = subInt(((NI) (cx)), ((NI) (x)));
			TMP909 = addInt((NI64)(TMP907), (NI64)(TMP908));
			if ((NU)((NI64)(TMP909)) > (NU)(999999)) raiseIndexError();
			video[((NI64)(TMP909))- 0] = ((NI32)chckRange(col, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
		}
		LA19: ;
		nimln(354, "graphics.nim");
		{
			NI TMP910;
			NI TMP911;
			NI TMP912;
			NI TMP913;
			NI TMP914;
			NI TMP915;
			nimln(354, "graphics.nim");
			nimln(354, "graphics.nim");
			TMP910 = subInt(((NI) (cy)), ((NI) (y)));
			nimln(354, "graphics.nim");
			TMP911 = subInt((*(*sur).S).H, ((NI32) 1));
			if (TMP911 < (-2147483647 -1) || TMP911 > 2147483647) raiseOverflow();
			if (!((NI64)(TMP910) <= ((NI) ((NI32)(TMP911))))) goto LA23;
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(354, "graphics.nim");
			TMP912 = subInt(((NI) (cy)), ((NI) (y)));
			TMP913 = mulInt((NI64)(TMP912), pitch);
			nimln(354, "graphics.nim");
			TMP914 = subInt(((NI) (cx)), ((NI) (x)));
			TMP915 = addInt((NI64)(TMP913), (NI64)(TMP914));
			if ((NU)((NI64)(TMP915)) > (NU)(999999)) raiseIndexError();
			video[((NI64)(TMP915))- 0] = ((NI32)chckRange(col, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
		}
		LA23: ;
	}
	LA15: ;
	popFrame();
}

N_NIMCALL(void, drawellipse_223840)(tsurface222011* sur, NI cx, NI cy, NI xradius, NI yradius, NI col) {
	NI x;
	NI y;
	NI xchange;
	NI ychange;
	NI ellipseerror;
	NI twoasquare;
	NI twobsquare;
	NI stoppingx;
	NI stoppingy;
	NI TMP916;
	NI TMP917;
	NI TMP918;
	NI TMP919;
	NI TMP920;
	NI TMP921;
	NI TMP922;
	NI TMP923;
	NI TMP924;
	NI TMP925;
	NI TMP928;
	NI TMP929;
	NI TMP930;
	NI TMP931;
	NI TMP932;
	NI TMP933;
	nimfr("drawEllipse", "graphics.nim")
	x = 0;
	y = 0;
	xchange = 0;
	ychange = 0;
	ellipseerror = 0;
	twoasquare = 0;
	twobsquare = 0;
	stoppingx = 0;
	stoppingy = 0;
	nimln(368, "graphics.nim");
	nimln(368, "graphics.nim");
	nimln(368, "graphics.nim");
	TMP916 = mulInt(2, ((NI) (xradius)));
	TMP917 = mulInt(((NI) ((NI64)(TMP916))), ((NI) (xradius)));
	twoasquare = (NI64)(TMP917);
	nimln(369, "graphics.nim");
	nimln(369, "graphics.nim");
	nimln(369, "graphics.nim");
	TMP918 = mulInt(2, ((NI) (yradius)));
	TMP919 = mulInt(((NI) ((NI64)(TMP918))), ((NI) (yradius)));
	twobsquare = (NI64)(TMP919);
	nimln(370, "graphics.nim");
	x = xradius;
	nimln(371, "graphics.nim");
	y = 0;
	nimln(372, "graphics.nim");
	nimln(372, "graphics.nim");
	nimln(372, "graphics.nim");
	TMP920 = mulInt(((NI) (yradius)), ((NI) (yradius)));
	nimln(372, "graphics.nim");
	nimln(372, "graphics.nim");
	TMP921 = mulInt(2, ((NI) (xradius)));
	TMP922 = subInt(1, ((NI) ((NI64)(TMP921))));
	TMP923 = mulInt(((NI) ((NI64)(TMP920))), (NI64)(TMP922));
	xchange = (NI64)(TMP923);
	nimln(373, "graphics.nim");
	nimln(373, "graphics.nim");
	TMP924 = mulInt(((NI) (xradius)), ((NI) (xradius)));
	ychange = ((NI) ((NI64)(TMP924)));
	nimln(374, "graphics.nim");
	ellipseerror = 0;
	nimln(375, "graphics.nim");
	nimln(375, "graphics.nim");
	TMP925 = mulInt(((NI) (twobsquare)), ((NI) (xradius)));
	stoppingx = (NI64)(TMP925);
	nimln(376, "graphics.nim");
	stoppingy = 0;
	{
		nimln(378, "graphics.nim");
		while (1) {
			nimln(378, "graphics.nim");
			if (!(((NI) (stoppingy)) <= ((NI) (stoppingx)))) goto LA2;
			nimln(379, "graphics.nim");
			plot4ellipsepoints_223815(sur, cx, cy, x, y, col);
			nimln(380, "graphics.nim");
			y = addInt(y, 1);
			nimln(381, "graphics.nim");
			stoppingy = addInt(stoppingy, ((NI) (twoasquare)));
			nimln(382, "graphics.nim");
			ellipseerror = addInt(ellipseerror, ychange);
			nimln(383, "graphics.nim");
			ychange = addInt(ychange, ((NI) (twoasquare)));
			nimln(384, "graphics.nim");
			{
				NI TMP926;
				NI TMP927;
				nimln(384, "graphics.nim");
				nimln(384, "graphics.nim");
				nimln(384, "graphics.nim");
				TMP926 = mulInt(2, ((NI) (ellipseerror)));
				TMP927 = addInt(((NI) ((NI64)(TMP926))), xchange);
				if (!(0 < (NI64)(TMP927))) goto LA5;
				nimln(385, "graphics.nim");
				x = subInt(x, 1);
				nimln(386, "graphics.nim");
				stoppingx = subInt(stoppingx, ((NI) (twobsquare)));
				nimln(387, "graphics.nim");
				ellipseerror = addInt(ellipseerror, xchange);
				nimln(388, "graphics.nim");
				xchange = addInt(xchange, ((NI) (twobsquare)));
			}
			LA5: ;
		} LA2: ;
	}
	nimln(391, "graphics.nim");
	x = 0;
	nimln(392, "graphics.nim");
	y = yradius;
	nimln(393, "graphics.nim");
	nimln(393, "graphics.nim");
	TMP928 = mulInt(((NI) (yradius)), ((NI) (yradius)));
	xchange = ((NI) ((NI64)(TMP928)));
	nimln(394, "graphics.nim");
	nimln(394, "graphics.nim");
	nimln(394, "graphics.nim");
	TMP929 = mulInt(((NI) (xradius)), ((NI) (xradius)));
	nimln(394, "graphics.nim");
	nimln(394, "graphics.nim");
	TMP930 = mulInt(2, ((NI) (yradius)));
	TMP931 = subInt(1, ((NI) ((NI64)(TMP930))));
	TMP932 = mulInt(((NI) ((NI64)(TMP929))), (NI64)(TMP931));
	ychange = (NI64)(TMP932);
	nimln(395, "graphics.nim");
	ellipseerror = 0;
	nimln(396, "graphics.nim");
	stoppingx = 0;
	nimln(397, "graphics.nim");
	nimln(397, "graphics.nim");
	TMP933 = mulInt(((NI) (twoasquare)), ((NI) (yradius)));
	stoppingy = (NI64)(TMP933);
	{
		nimln(398, "graphics.nim");
		while (1) {
			nimln(398, "graphics.nim");
			if (!(((NI) (stoppingx)) <= ((NI) (stoppingy)))) goto LA8;
			nimln(399, "graphics.nim");
			plot4ellipsepoints_223815(sur, cx, cy, x, y, col);
			nimln(400, "graphics.nim");
			x = addInt(x, 1);
			nimln(401, "graphics.nim");
			stoppingx = addInt(stoppingx, ((NI) (twobsquare)));
			nimln(402, "graphics.nim");
			ellipseerror = addInt(ellipseerror, xchange);
			nimln(403, "graphics.nim");
			xchange = addInt(xchange, ((NI) (twobsquare)));
			nimln(404, "graphics.nim");
			{
				NI TMP934;
				NI TMP935;
				nimln(404, "graphics.nim");
				nimln(404, "graphics.nim");
				nimln(404, "graphics.nim");
				TMP934 = mulInt(2, ((NI) (ellipseerror)));
				TMP935 = addInt(((NI) ((NI64)(TMP934))), ychange);
				if (!(0 < (NI64)(TMP935))) goto LA11;
				nimln(405, "graphics.nim");
				y = subInt(y, 1);
				nimln(406, "graphics.nim");
				stoppingy = subInt(stoppingy, ((NI) (twoasquare)));
				nimln(407, "graphics.nim");
				ellipseerror = addInt(ellipseerror, ychange);
				nimln(408, "graphics.nim");
				ychange = addInt(ychange, ((NI) (twoasquare)));
			}
			LA11: ;
		} LA8: ;
	}
	popFrame();
}

N_NIMCALL(void, plotaa_224094)(tsurface222011* sur, NI x, NI y, NF c, NI color) {
	nimfr("plotAA", "graphics.nim")
	nimln(412, "graphics.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NIM_BOOL LOC7;
		NI32* video;
		NI pitch;
		NI TMP936;
		NI pixcolor;
		NI TMP937;
		NI TMP938;
		NI TMP939;
		NI TMP940;
		NI LOC11;
		NI LOC12;
		NI LOC13;
		nimln(412, "graphics.nim");
		LOC3 = 0;
		nimln(412, "graphics.nim");
		LOC4 = 0;
		nimln(412, "graphics.nim");
		LOC4 = (0 < x);
		if (!(LOC4)) goto LA5;
		nimln(412, "graphics.nim");
		LOC4 = (x < ((NI) ((*(*sur).S).W)));
		LA5: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA6;
		nimln(412, "graphics.nim");
		LOC7 = 0;
		nimln(412, "graphics.nim");
		LOC7 = (0 < y);
		if (!(LOC7)) goto LA8;
		nimln(412, "graphics.nim");
		LOC7 = (y < ((NI) ((*(*sur).S).H)));
		LA8: ;
		LOC3 = LOC7;
		LA6: ;
		if (!LOC3) goto LA9;
		nimln(413, "graphics.nim");
		video = ((NI32*) ((*(*sur).S).Pixels));
		nimln(414, "graphics.nim");
		nimln(414, "graphics.nim");
		TMP936 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
		pitch = (NI64)(TMP936);
		nimln(416, "graphics.nim");
		nimln(416, "graphics.nim");
		nimln(416, "graphics.nim");
		TMP937 = mulInt(y, pitch);
		TMP938 = addInt((NI64)(TMP937), x);
		if ((NU)((NI64)(TMP938)) > (NU)(999999)) raiseIndexError();
		pixcolor = ((NI) (video[((NI64)(TMP938))- 0]));
		nimln(110, "graphics.nim");
		nimln(110, "graphics.nim");
		nimln(110, "graphics.nim");
		TMP939 = mulInt(y, pitch);
		TMP940 = addInt((NI64)(TMP939), x);
		if ((NU)((NI64)(TMP940)) > (NU)(999999)) raiseIndexError();
		nimln(419, "graphics.nim");
		nimln(419, "graphics.nim");
		nimln(419, "graphics.nim");
		LOC11 = 0;
		LOC11 = intensity_211215(pixcolor, ((NF)(1.0000000000000000e+000) - (NF)(c)));
		nimln(419, "graphics.nim");
		LOC12 = 0;
		LOC12 = intensity_211215(color, c);
		LOC13 = 0;
		LOC13 = HEX2B_211118(LOC11, LOC12);
		video[((NI64)(TMP940))- 0] = ((NI32)chckRange(LOC13, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
	}
	LA9: ;
	popFrame();
}

N_NIMCALL(void, drawlineaa_224145)(tsurface222011* sur, TY187006 p1, TY187006 p2, NI color) {
	TY224151 LOC1;
	NF x1;
	NF x2;
	NF y1;
	NF y2;
	NF dx;
	NF dy;
	NF ax;
	NF ay;
	NF gradient;
	NF xend;
	NF yend;
	NF xgap;
	NF LOC23;
	NI xpxl1;
	NI ypxl1;
	NF LOC24;
	NF intery;
	NF LOC39;
	NI xpxl2;
	NI ypxl2;
	NF LOC40;
	NI x;
	NI TMP945;
	nimfr("drawLineAA", "graphics.nim")
	nimln(430, "graphics.nim");
	nimln(430, "graphics.nim");
	LOC1.Field0 = ((double) (p1.Field0));
	nimln(430, "graphics.nim");
	LOC1.Field1 = ((double) (p2.Field0));
	nimln(431, "graphics.nim");
	LOC1.Field2 = ((double) (p1.Field1));
	nimln(431, "graphics.nim");
	LOC1.Field3 = ((double) (p2.Field1));
	x1 = LOC1.Field0;
	x2 = LOC1.Field1;
	y1 = LOC1.Field2;
	y2 = LOC1.Field3;
	nimln(432, "graphics.nim");
	nimln(432, "graphics.nim");
	dx = ((NF)(x2) - (NF)(x1));
	nimln(433, "graphics.nim");
	nimln(433, "graphics.nim");
	dy = ((NF)(y2) - (NF)(y1));
	nimln(435, "graphics.nim");
	ax = dx;
	nimln(436, "graphics.nim");
	{
		nimln(436, "graphics.nim");
		if (!(ax < 0.0)) goto LA4;
		nimln(437, "graphics.nim");
		nimln(437, "graphics.nim");
		ax = ((NF)(0.0) - (NF)(ax));
	}
	LA4: ;
	nimln(438, "graphics.nim");
	ay = dy;
	nimln(439, "graphics.nim");
	{
		nimln(439, "graphics.nim");
		if (!(ay < 0.0)) goto LA8;
		nimln(440, "graphics.nim");
		nimln(440, "graphics.nim");
		ay = ((NF)(0.0) - (NF)(ay));
	}
	LA8: ;
	nimln(442, "graphics.nim");
	{
		NF LOC14;
		NF LOC15;
		NF LOC16;
		nimln(442, "graphics.nim");
		if (!(ax < ay)) goto LA12;
		nimln(443, "graphics.nim");
		LOC14 = 0;
		LOC14 = x1;
		x1 = y1;
		y1 = LOC14;
		nimln(444, "graphics.nim");
		LOC15 = 0;
		LOC15 = x2;
		x2 = y2;
		y2 = LOC15;
		nimln(445, "graphics.nim");
		LOC16 = 0;
		LOC16 = dx;
		dx = dy;
		dy = LOC16;
	}
	LA12: ;
	nimln(453, "graphics.nim");
	{
		NF LOC21;
		NF LOC22;
		nimln(453, "graphics.nim");
		if (!(x2 < x1)) goto LA19;
		nimln(454, "graphics.nim");
		LOC21 = 0;
		LOC21 = x1;
		x1 = x2;
		x2 = LOC21;
		nimln(455, "graphics.nim");
		LOC22 = 0;
		LOC22 = y1;
		y1 = y2;
		y2 = LOC22;
	}
	LA19: ;
	nimln(457, "graphics.nim");
	nimln(457, "graphics.nim");
	gradient = ((NF)(dy) / (NF)(dx));
	nimln(459, "graphics.nim");
	nimln(459, "graphics.nim");
	xend = floor(((NF)(x1) + (NF)(5.0000000000000000e-001)));
	nimln(460, "graphics.nim");
	nimln(460, "graphics.nim");
	nimln(460, "graphics.nim");
	nimln(460, "graphics.nim");
	yend = ((NF)(y1) + (NF)(((NF)(gradient) * (NF)(((NF)(xend) - (NF)(x1))))));
	nimln(461, "graphics.nim");
	nimln(461, "graphics.nim");
	nimln(461, "graphics.nim");
	nimln(461, "graphics.nim");
	nimln(461, "graphics.nim");
	nimln(461, "graphics.nim");
	LOC23 = 0;
	LOC23 = floor(((NF)(x1) + (NF)(5.0000000000000000e-001)));
	xgap = ((NF)(1.0000000000000000e+000) - (NF)(((NF)(((NF)(x1) + (NF)(5.0000000000000000e-001))) - (NF)(LOC23))));
	nimln(462, "graphics.nim");
	xpxl1 = ((NI) (xend));
	nimln(463, "graphics.nim");
	nimln(463, "graphics.nim");
	LOC24 = 0;
	LOC24 = floor(yend);
	ypxl1 = ((NI) (LOC24));
	nimln(448, "graphics.nim");
	{
		NF LOC29;
		nimln(448, "graphics.nim");
		if (!(ax < ay)) goto LA27;
		nimln(449, "graphics.nim");
		nimln(464, "graphics.nim");
		nimln(464, "graphics.nim");
		nimln(464, "graphics.nim");
		nimln(464, "graphics.nim");
		LOC29 = 0;
		LOC29 = floor(yend);
		plotaa_224094(sur, ypxl1, xpxl1, ((NF)(((NF)(1.0000000000000000e+000) - (NF)(((NF)(yend) - (NF)(LOC29))))) * (NF)(xgap)), color);
	}
	goto LA25;
	LA27: ;
	{
		NF LOC31;
		nimln(451, "graphics.nim");
		nimln(464, "graphics.nim");
		nimln(464, "graphics.nim");
		nimln(464, "graphics.nim");
		nimln(464, "graphics.nim");
		LOC31 = 0;
		LOC31 = floor(yend);
		plotaa_224094(sur, xpxl1, ypxl1, ((NF)(((NF)(1.0000000000000000e+000) - (NF)(((NF)(yend) - (NF)(LOC31))))) * (NF)(xgap)), color);
	}
	LA25: ;
	nimln(448, "graphics.nim");
	{
		NI TMP941;
		NF LOC36;
		nimln(448, "graphics.nim");
		if (!(ax < ay)) goto LA34;
		nimln(449, "graphics.nim");
		nimln(465, "graphics.nim");
		TMP941 = addInt(ypxl1, 1);
		nimln(465, "graphics.nim");
		nimln(465, "graphics.nim");
		nimln(465, "graphics.nim");
		LOC36 = 0;
		LOC36 = floor(yend);
		plotaa_224094(sur, (NI64)(TMP941), xpxl1, ((NF)(((NF)(yend) - (NF)(LOC36))) * (NF)(xgap)), color);
	}
	goto LA32;
	LA34: ;
	{
		NI TMP942;
		NF LOC38;
		nimln(451, "graphics.nim");
		nimln(465, "graphics.nim");
		TMP942 = addInt(ypxl1, 1);
		nimln(465, "graphics.nim");
		nimln(465, "graphics.nim");
		nimln(465, "graphics.nim");
		LOC38 = 0;
		LOC38 = floor(yend);
		plotaa_224094(sur, xpxl1, (NI64)(TMP942), ((NF)(((NF)(yend) - (NF)(LOC38))) * (NF)(xgap)), color);
	}
	LA32: ;
	nimln(466, "graphics.nim");
	nimln(466, "graphics.nim");
	intery = ((NF)(yend) + (NF)(gradient));
	nimln(469, "graphics.nim");
	nimln(469, "graphics.nim");
	xend = floor(((NF)(x2) + (NF)(5.0000000000000000e-001)));
	nimln(470, "graphics.nim");
	nimln(470, "graphics.nim");
	nimln(470, "graphics.nim");
	nimln(470, "graphics.nim");
	yend = ((NF)(y2) + (NF)(((NF)(gradient) * (NF)(((NF)(xend) - (NF)(x2))))));
	nimln(471, "graphics.nim");
	nimln(471, "graphics.nim");
	nimln(471, "graphics.nim");
	nimln(471, "graphics.nim");
	nimln(471, "graphics.nim");
	LOC39 = 0;
	LOC39 = floor(((NF)(x2) + (NF)(5.0000000000000000e-001)));
	xgap = ((NF)(((NF)(x2) + (NF)(5.0000000000000000e-001))) - (NF)(LOC39));
	nimln(472, "graphics.nim");
	xpxl2 = ((NI) (xend));
	nimln(473, "graphics.nim");
	nimln(473, "graphics.nim");
	LOC40 = 0;
	LOC40 = floor(yend);
	ypxl2 = ((NI) (LOC40));
	nimln(448, "graphics.nim");
	{
		NF LOC45;
		nimln(448, "graphics.nim");
		if (!(ax < ay)) goto LA43;
		nimln(449, "graphics.nim");
		nimln(474, "graphics.nim");
		nimln(474, "graphics.nim");
		nimln(474, "graphics.nim");
		nimln(474, "graphics.nim");
		LOC45 = 0;
		LOC45 = floor(yend);
		plotaa_224094(sur, ypxl2, xpxl2, ((NF)(((NF)(1.0000000000000000e+000) - (NF)(((NF)(yend) - (NF)(LOC45))))) * (NF)(xgap)), color);
	}
	goto LA41;
	LA43: ;
	{
		NF LOC47;
		nimln(451, "graphics.nim");
		nimln(474, "graphics.nim");
		nimln(474, "graphics.nim");
		nimln(474, "graphics.nim");
		nimln(474, "graphics.nim");
		LOC47 = 0;
		LOC47 = floor(yend);
		plotaa_224094(sur, xpxl2, ypxl2, ((NF)(((NF)(1.0000000000000000e+000) - (NF)(((NF)(yend) - (NF)(LOC47))))) * (NF)(xgap)), color);
	}
	LA41: ;
	nimln(448, "graphics.nim");
	{
		NI TMP943;
		NF LOC52;
		nimln(448, "graphics.nim");
		if (!(ax < ay)) goto LA50;
		nimln(449, "graphics.nim");
		nimln(475, "graphics.nim");
		TMP943 = addInt(ypxl2, 1);
		nimln(475, "graphics.nim");
		nimln(475, "graphics.nim");
		nimln(475, "graphics.nim");
		LOC52 = 0;
		LOC52 = floor(yend);
		plotaa_224094(sur, (NI64)(TMP943), xpxl2, ((NF)(((NF)(yend) - (NF)(LOC52))) * (NF)(xgap)), color);
	}
	goto LA48;
	LA50: ;
	{
		NI TMP944;
		NF LOC54;
		nimln(451, "graphics.nim");
		nimln(475, "graphics.nim");
		TMP944 = addInt(ypxl2, 1);
		nimln(475, "graphics.nim");
		nimln(475, "graphics.nim");
		nimln(475, "graphics.nim");
		LOC54 = 0;
		LOC54 = floor(yend);
		plotaa_224094(sur, xpxl2, (NI64)(TMP944), ((NF)(((NF)(yend) - (NF)(LOC54))) * (NF)(xgap)), color);
	}
	LA48: ;
	nimln(478, "graphics.nim");
	nimln(478, "graphics.nim");
	TMP945 = addInt(xpxl1, 1);
	x = (NI64)(TMP945);
	{
		nimln(479, "graphics.nim");
		while (1) {
			NI TMP946;
			nimln(479, "graphics.nim");
			nimln(479, "graphics.nim");
			TMP946 = subInt(xpxl2, 1);
			if (!(x <= (NI64)(TMP946))) goto LA56;
			nimln(448, "graphics.nim");
			{
				NF LOC61;
				NF LOC62;
				nimln(448, "graphics.nim");
				if (!(ax < ay)) goto LA59;
				nimln(449, "graphics.nim");
				nimln(480, "graphics.nim");
				LOC61 = 0;
				LOC61 = floor(intery);
				nimln(480, "graphics.nim");
				nimln(480, "graphics.nim");
				nimln(480, "graphics.nim");
				LOC62 = 0;
				LOC62 = floor(intery);
				plotaa_224094(sur, ((NI) (LOC61)), x, ((NF)(1.0000000000000000e+000) - (NF)(((NF)(intery) - (NF)(LOC62)))), color);
			}
			goto LA57;
			LA59: ;
			{
				NF LOC64;
				NF LOC65;
				nimln(451, "graphics.nim");
				nimln(480, "graphics.nim");
				LOC64 = 0;
				LOC64 = floor(intery);
				nimln(480, "graphics.nim");
				nimln(480, "graphics.nim");
				nimln(480, "graphics.nim");
				LOC65 = 0;
				LOC65 = floor(intery);
				plotaa_224094(sur, x, ((NI) (LOC64)), ((NF)(1.0000000000000000e+000) - (NF)(((NF)(intery) - (NF)(LOC65)))), color);
			}
			LA57: ;
			nimln(448, "graphics.nim");
			{
				NF LOC70;
				NI TMP947;
				NF LOC71;
				nimln(448, "graphics.nim");
				if (!(ax < ay)) goto LA68;
				nimln(449, "graphics.nim");
				nimln(481, "graphics.nim");
				nimln(481, "graphics.nim");
				LOC70 = 0;
				LOC70 = floor(intery);
				TMP947 = addInt(((NI) (LOC70)), 1);
				nimln(481, "graphics.nim");
				nimln(481, "graphics.nim");
				LOC71 = 0;
				LOC71 = floor(intery);
				plotaa_224094(sur, (NI64)(TMP947), x, ((NF)(intery) - (NF)(LOC71)), color);
			}
			goto LA66;
			LA68: ;
			{
				NF LOC73;
				NI TMP948;
				NF LOC74;
				nimln(451, "graphics.nim");
				nimln(481, "graphics.nim");
				nimln(481, "graphics.nim");
				LOC73 = 0;
				LOC73 = floor(intery);
				TMP948 = addInt(((NI) (LOC73)), 1);
				nimln(481, "graphics.nim");
				nimln(481, "graphics.nim");
				LOC74 = 0;
				LOC74 = floor(intery);
				plotaa_224094(sur, x, (NI64)(TMP948), ((NF)(intery) - (NF)(LOC74)), color);
			}
			LA66: ;
			nimln(482, "graphics.nim");
			nimln(482, "graphics.nim");
			intery = ((NF)(intery) + (NF)(gradient));
			nimln(483, "graphics.nim");
			x = addInt(x, 1);
		} LA56: ;
	}
	popFrame();
}

N_NIMCALL(void, fillsurface_224301)(tsurface222011* sur, NI color) {
	nimfr("fillSurface", "graphics.nim")
	nimln(487, "graphics.nim");
	{
		NI32 LOC3;
		NI LOC4;
		nimln(487, "graphics.nim");
		nimln(487, "graphics.nim");
		nimln(487, "graphics.nim");
		LOC3 = 0;
		LOC3 = createsdlcolor_222053(sur, color, 0);
		LOC4 = 0;
		LOC4 = Dl_219429((*sur).S, NIM_NIL, LOC3);
		if (!(LOC4 == -1)) goto LA5;
		nimln(488, "graphics.nim");
		raiseegraphics_222085();
	}
	LA5: ;
	popFrame();
}
N_NOINLINE(void, HEX00_graphicsInit)(void) {
	nimfr("graphics", "graphics.nim")
	nimln(499, "graphics.nim");
	{
		NI LOC3;
		nimln(499, "graphics.nim");
		nimln(499, "graphics.nim");
		LOC3 = 0;
		LOC3 = Dl_218225(((NI32) 32));
		if (!(LOC3 < 0)) goto LA4;
		nimln(499, "graphics.nim");
		raiseegraphics_222085();
	}
	LA4: ;
	nimln(500, "graphics.nim");
	{
		int LOC8;
		nimln(500, "graphics.nim");
		nimln(500, "graphics.nim");
		LOC8 = 0;
		LOC8 = Dl_221240();
		if (!(LOC8 < ((NI32) 0))) goto LA9;
		nimln(500, "graphics.nim");
		raiseegraphics_222085();
	}
	LA9: ;
	popFrame();
}

N_NOINLINE(void, HEX00_graphicsDatInit)(void) {
static TNimNode* TMP723[3];
static TNimNode* TMP731[2];
static TNimNode TMP548[8];
NTI222013.size = sizeof(egraphics222013);
NTI222013.kind = 17;
NTI222013.base = (&NTI2837);
TMP548[0].len = 0; TMP548[0].kind = 2;
NTI222013.node = &TMP548[0];
NTI222090.size = sizeof(egraphics222013*);
NTI222090.kind = 22;
NTI222090.base = (&NTI222013);
NTI222090.marker = TMP722;
NTI222011.size = sizeof(tsurface222011);
NTI222011.kind = 18;
NTI222011.base = 0;
NTI222011.flags = 3;
TMP723[0] = &TMP548[2];
TMP548[2].kind = 1;
TMP548[2].offset = offsetof(tsurface222011, W);
TMP548[2].typ = (&NTI2807);
TMP548[2].name = "w";
TMP723[1] = &TMP548[3];
TMP548[3].kind = 1;
TMP548[3].offset = offsetof(tsurface222011, H);
TMP548[3].typ = (&NTI2807);
TMP548[3].name = "h";
TMP723[2] = &TMP548[4];
TMP548[4].kind = 1;
TMP548[4].offset = offsetof(tsurface222011, S);
TMP548[4].typ = (&NTI215051);
TMP548[4].name = "s";
TMP548[1].len = 3; TMP548[1].kind = 2; TMP548[1].sons = &TMP723[0];
NTI222011.node = &TMP548[1];
NTI222009.size = sizeof(tsurface222011*);
NTI222009.kind = 22;
NTI222009.base = (&NTI222011);
NTI222009.flags = 2;
NTI222009.marker = TMP729;
(&NTI222009)->finalizer = (void*)surfacefinalizer_222114;
NTI222015.size = sizeof(tfont222015);
NTI222015.kind = 18;
NTI222015.base = 0;
NTI222015.flags = 3;
TMP731[0] = &TMP548[6];
TMP548[6].kind = 1;
TMP548[6].offset = offsetof(tfont222015, F);
TMP548[6].typ = (&NTI221219);
TMP548[6].name = "f";
TMP731[1] = &TMP548[7];
TMP548[7].kind = 1;
TMP548[7].offset = offsetof(tfont222015, Color);
TMP548[7].typ = (&NTI215033);
TMP548[7].name = "color";
TMP548[5].len = 2; TMP548[5].kind = 2; TMP548[5].sons = &TMP731[0];
NTI222015.node = &TMP548[5];
NTI222017.size = sizeof(tfont222015*);
NTI222017.kind = 22;
NTI222017.base = (&NTI222015);
NTI222017.flags = 2;
NTI222017.marker = TMP732;
(&NTI222017)->finalizer = (void*)fontfinalizer_222207;
(&NTI222009)->finalizer = (void*)surfacefinalizer_222114;
(&NTI222009)->finalizer = (void*)surfacefinalizer_222114;
(&NTI222009)->finalizer = (void*)surfacefinalizer_222114;
}

