/* Generated by Nimrod Compiler v0.9.6 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nimrod\lib -o c:\users\simon\rationalnes_\nimcache\hashes.o c:\users\simon\rationalnes_\nimcache\hashes.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, HEX21HEX26_197025)(NI h, NI val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_17801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, HEX21HEX24_197054)(NI h);
N_NIMCALL(NI, hashdata_197082)(void* data, NI size);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI, hash_197401)(void* x);
static N_INLINE(NI, hash_197804)(NI x);
static N_INLINE(NI, hash_197814)(NI64 x);
static N_INLINE(NI, hash_197824)(NIM_CHAR x);
N_NIMCALL(NI, hash_197842)(NimStringDesc* x);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, hashignorestyle_197888)(NimStringDesc* x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NI, hashignorecase_197980)(NimStringDesc* x);
static N_INLINE(NI, hash_198082)(NF x);
extern TFrame* frameptr_15242;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_15242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_15242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_15242;
	frameptr_15242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_17801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_15242 = (*frameptr_15242).prev;
}

static N_INLINE(NI, HEX21HEX26_197025)(NI h, NI val) {
	NI result;
	nimfr("!&", "hashes.nim")
	result = 0;
	nimln(51, "hashes.nim");
	nimln(51, "hashes.nim");
	result = (NI)((NU64)(h) + (NU64)(val));
	nimln(52, "hashes.nim");
	nimln(52, "hashes.nim");
	nimln(52, "hashes.nim");
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(10))));
	nimln(53, "hashes.nim");
	nimln(53, "hashes.nim");
	nimln(53, "hashes.nim");
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(6)));
	popFrame();
	return result;
}

static N_INLINE(NI, HEX21HEX24_197054)(NI h) {
	NI result;
	nimfr("!$", "hashes.nim")
	result = 0;
	nimln(58, "hashes.nim");
	nimln(58, "hashes.nim");
	nimln(58, "hashes.nim");
	result = (NI)((NU64)(h) + (NU64)((NI)((NU64)(h) << (NU64)(3))));
	nimln(59, "hashes.nim");
	nimln(59, "hashes.nim");
	nimln(59, "hashes.nim");
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(11)));
	nimln(60, "hashes.nim");
	nimln(60, "hashes.nim");
	nimln(60, "hashes.nim");
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(15))));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, hashdata_197082)(void* data, NI size) {
	NI result;
	NI h;
	NCSTRING p;
	NI i;
	NI s;
	nimfr("hashData", "hashes.nim")
	result = 0;
	nimln(64, "hashes.nim");
	h = 0;
	nimln(69, "hashes.nim");
	p = ((NCSTRING) (data));
	nimln(70, "hashes.nim");
	i = 0;
	nimln(71, "hashes.nim");
	s = size;
	{
		nimln(72, "hashes.nim");
		while (1) {
			nimln(72, "hashes.nim");
			if (!(0 < s)) goto LA2;
			nimln(73, "hashes.nim");
			nimln(73, "hashes.nim");
			h = HEX21HEX26_197025(h, ((NI) (((NU8)(p[i])))));
			nimln(74, "hashes.nim");
			i = addInt(i, 1);
			nimln(75, "hashes.nim");
			s = subInt(s, 1);
		} LA2: ;
	}
	nimln(76, "hashes.nim");
	result = HEX21HEX24_197054(h);
	popFrame();
	return result;
}

static N_INLINE(NI, hash_197401)(void* x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(95, "hashes.nim");
	nimln(95, "hashes.nim");
	result = (NI)((NU64)(((NI) (x))) >> (NU64)(3));
	popFrame();
	return result;
}

static N_INLINE(NI, hash_197804)(NI x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(107, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(NI, hash_197814)(NI64 x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(111, "hashes.nim");
	nimln(111, "hashes.nim");
	result = ((NI) (((NI32)(NU32)(NU64)(x))));
	popFrame();
	return result;
}

static N_INLINE(NI, hash_197824)(NIM_CHAR x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(115, "hashes.nim");
	nimln(115, "hashes.nim");
	result = ((NI) (((NU8)(x))));
	popFrame();
	return result;
}

N_NIMCALL(NI, hash_197842)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(119, "hashes.nim");
	h = 0;
	{
		NI i_197857;
		NI HEX3Atmp_197868;
		NI TMP336;
		NI res_197871;
		i_197857 = 0;
		HEX3Atmp_197868 = 0;
		nimln(120, "hashes.nim");
		nimln(120, "hashes.nim");
		nimln(120, "hashes.nim");
		TMP336 = subInt(x->Sup.len, 1);
		HEX3Atmp_197868 = (NI64)(TMP336);
		nimln(1551, "system.nim");
		res_197871 = 0;
		{
			nimln(1552, "system.nim");
			while (1) {
				nimln(1552, "system.nim");
				if (!(res_197871 <= HEX3Atmp_197868)) goto LA3;
				nimln(1551, "system.nim");
				i_197857 = res_197871;
				nimln(121, "hashes.nim");
				nimln(121, "hashes.nim");
				if ((NU)(i_197857) > (NU)(x->Sup.len)) raiseIndexError();
				h = HEX21HEX26_197025(h, ((NI) (((NU8)(x->data[i_197857])))));
				nimln(1554, "system.nim");
				res_197871 = addInt(res_197871, 1);
			} LA3: ;
		}
	}
	nimln(122, "hashes.nim");
	result = HEX21HEX24_197054(h);
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, hashignorestyle_197888)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr("hashIgnoreStyle", "hashes.nim")
	result = 0;
	nimln(126, "hashes.nim");
	h = 0;
	{
		NI i_197903;
		NI HEX3Atmp_197957;
		NI TMP337;
		NI res_197960;
		i_197903 = 0;
		HEX3Atmp_197957 = 0;
		nimln(127, "hashes.nim");
		nimln(127, "hashes.nim");
		nimln(127, "hashes.nim");
		TMP337 = subInt(x->Sup.len, 1);
		HEX3Atmp_197957 = (NI64)(TMP337);
		nimln(1551, "system.nim");
		res_197960 = 0;
		{
			nimln(1552, "system.nim");
			while (1) {
				nimln(1552, "system.nim");
				if (!(res_197960 <= HEX3Atmp_197957)) goto LA3;
				nimln(1551, "system.nim");
				i_197903 = res_197960;
				{
					NIM_CHAR c;
					nimln(128, "hashes.nim");
					if ((NU)(i_197903) > (NU)(x->Sup.len)) raiseIndexError();
					c = x->data[i_197903];
					nimln(129, "hashes.nim");
					{
						nimln(129, "hashes.nim");
						if (!((NU8)(c) == (NU8)(95))) goto LA7;
						nimln(130, "hashes.nim");
						goto LA4;
					}
					LA7: ;
					nimln(131, "hashes.nim");
					{
						NI TMP338;
						nimln(131, "hashes.nim");
						if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA11;
						nimln(132, "hashes.nim");
						nimln(132, "hashes.nim");
						nimln(132, "hashes.nim");
						nimln(132, "hashes.nim");
						TMP338 = addInt(((NI) (((NU8)(c)))), 32);
						c = ((NIM_CHAR) (((NI)chckRange((NI64)(TMP338), 0, 255))));
					}
					LA11: ;
					nimln(133, "hashes.nim");
					nimln(133, "hashes.nim");
					h = HEX21HEX26_197025(h, ((NI) (((NU8)(c)))));
				} LA4: ;
				nimln(1554, "system.nim");
				res_197960 = addInt(res_197960, 1);
			} LA3: ;
		}
	}
	nimln(134, "hashes.nim");
	result = HEX21HEX24_197054(h);
	popFrame();
	return result;
}

N_NIMCALL(NI, hashignorecase_197980)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr("hashIgnoreCase", "hashes.nim")
	result = 0;
	nimln(138, "hashes.nim");
	h = 0;
	{
		NI i_197995;
		NI HEX3Atmp_198048;
		NI TMP339;
		NI res_198051;
		i_197995 = 0;
		HEX3Atmp_198048 = 0;
		nimln(139, "hashes.nim");
		nimln(139, "hashes.nim");
		nimln(139, "hashes.nim");
		TMP339 = subInt(x->Sup.len, 1);
		HEX3Atmp_198048 = (NI64)(TMP339);
		nimln(1551, "system.nim");
		res_198051 = 0;
		{
			nimln(1552, "system.nim");
			while (1) {
				NIM_CHAR c;
				nimln(1552, "system.nim");
				if (!(res_198051 <= HEX3Atmp_198048)) goto LA3;
				nimln(1551, "system.nim");
				i_197995 = res_198051;
				nimln(140, "hashes.nim");
				if ((NU)(i_197995) > (NU)(x->Sup.len)) raiseIndexError();
				c = x->data[i_197995];
				nimln(141, "hashes.nim");
				{
					NI TMP340;
					nimln(141, "hashes.nim");
					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA6;
					nimln(142, "hashes.nim");
					nimln(142, "hashes.nim");
					nimln(142, "hashes.nim");
					nimln(142, "hashes.nim");
					TMP340 = addInt(((NI) (((NU8)(c)))), 32);
					c = ((NIM_CHAR) (((NI)chckRange((NI64)(TMP340), 0, 255))));
				}
				LA6: ;
				nimln(143, "hashes.nim");
				nimln(143, "hashes.nim");
				h = HEX21HEX26_197025(h, ((NI) (((NU8)(c)))));
				nimln(1554, "system.nim");
				res_198051 = addInt(res_198051, 1);
			} LA3: ;
		}
	}
	nimln(144, "hashes.nim");
	result = HEX21HEX24_197054(h);
	popFrame();
	return result;
}

static N_INLINE(NI, hash_198082)(NF x) {
	NI result;
	NF y;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(153, "hashes.nim");
	nimln(153, "hashes.nim");
	y = ((NF)(x) + (NF)(1.0000000000000000e+000));
	nimln(154, "hashes.nim");
	result = (*((NI*) (&y)));
	popFrame();
	return result;
}
N_NOINLINE(void, HEX00_hashesInit)(void) {
	nimfr("hashes", "hashes.nim")
	popFrame();
}

N_NOINLINE(void, HEX00_hashesDatInit)(void) {
}

