/* Generated by Nimrod Compiler v0.9.6 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nimrod\lib -o c:\users\simon\rationalnes_\nimcache\sdl_ttf.o c:\users\simon\rationalnes_\nimcache\sdl_ttf.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tversion214328 tversion214328;
typedef struct tfont221221 tfont221221;
typedef struct trwops214268 trwops214268;
typedef struct tsurface215055 tsurface215055;
typedef struct tcolor215033 tcolor215033;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tmem214256 tmem214256;
typedef struct tpixelformat215045 tpixelformat215045;
typedef struct trect215027 trect215027;
typedef struct tpalette215041 tpalette215041;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(tversion214328*, TY221229) (void);
typedef N_CDECL_PTR(void, TY221235) (int swapped);
typedef N_CDECL_PTR(int, TY221241) (void);
typedef N_CDECL_PTR(tfont221221*, TY221246) (NCSTRING filename, int ptsize);
typedef N_CDECL_PTR(tfont221221*, TY221253) (NCSTRING filename, int ptsize, NI32 index);
typedef N_CDECL_PTR(tfont221221*, TY221261) (trwops214268* src, int freesrc, int ptsize);
typedef N_CDECL_PTR(tfont221221*, TY221269) (trwops214268* src, int freesrc, int ptsize, NI32 index);
typedef N_CDECL_PTR(int, TY221278) (tfont221221* font);
typedef N_CDECL_PTR(void, TY221284) (tfont221221* font, int style);
typedef N_CDECL_PTR(int, TY221291) (tfont221221* font);
typedef N_CDECL_PTR(int, TY221297) (tfont221221* font);
typedef N_CDECL_PTR(int, TY221303) (tfont221221* font);
typedef N_CDECL_PTR(int, TY221309) (tfont221221* font);
typedef N_CDECL_PTR(NI32, TY221315) (tfont221221* font);
typedef N_CDECL_PTR(int, TY221321) (tfont221221* font);
typedef N_CDECL_PTR(NCSTRING, TY221327) (tfont221221* font);
typedef N_CDECL_PTR(NCSTRING, TY221333) (tfont221221* font);
typedef N_CDECL_PTR(int, TY221339) (tfont221221* font, NU16 ch, NI32* minx, NI32* maxx, NI32* miny, NI32* maxy, NI32* advance);
typedef N_CDECL_PTR(int, TY221356) (tfont221221* font, NCSTRING text, NI32* w, NI32* y);
typedef N_CDECL_PTR(int, TY221367) (tfont221221* font, NCSTRING text, NI32* w, NI32* y);
typedef N_CDECL_PTR(int, TY221378) (tfont221221* font, NU16* text, NI32* w, NI32* y);
struct  tcolor215033  {
NU8 R;
NU8 G;
NU8 B;
NU8 Unused;
};
typedef N_CDECL_PTR(tsurface215055*, TY221389) (tfont221221* font, NCSTRING text, tcolor215033 fg);
typedef N_CDECL_PTR(tsurface215055*, TY221397) (tfont221221* font, NU16* text, tcolor215033 fg);
typedef N_CDECL_PTR(tsurface215055*, TY221405) (tfont221221* font, NU16 ch, tcolor215033 fg);
typedef N_CDECL_PTR(tsurface215055*, TY221413) (tfont221221* font, NCSTRING text, tcolor215033 fg, tcolor215033 bg);
typedef N_CDECL_PTR(tsurface215055*, TY221422) (tfont221221* font, NCSTRING text, tcolor215033 fg, tcolor215033 bg);
typedef N_CDECL_PTR(tsurface215055*, TY221431) (tfont221221* font, NU16* text, tcolor215033 fg, tcolor215033 bg);
typedef N_CDECL_PTR(tsurface215055*, TY221440) (tfont221221* font, NU16 ch, tcolor215033 fg, tcolor215033 bg);
typedef N_CDECL_PTR(tsurface215055*, TY221449) (tfont221221* font, NCSTRING text, tcolor215033 fg);
typedef N_CDECL_PTR(tsurface215055*, TY221457) (tfont221221* font, NCSTRING text, tcolor215033 fg);
typedef N_CDECL_PTR(tsurface215055*, TY221465) (tfont221221* font, NU16* text, tcolor215033 fg);
typedef N_CDECL_PTR(tsurface215055*, TY221473) (tfont221221* font, NU16 ch, tcolor215033 fg);
typedef N_CDECL_PTR(void, TY221481) (tfont221221* font);
typedef N_CDECL_PTR(void, TY221487) (void);
typedef N_CDECL_PTR(int, TY221492) (void);
struct  tversion214328  {
NU8 Major;
NU8 Minor;
NU8 Patch;
};
typedef N_CDECL_PTR(tsurface215055*, TY221508) (tfont221221* font, NCSTRING text, tcolor215033 fg);
struct  tfont221221  {
char dummy;
};
typedef N_NIMCALL_PTR(void, TY2689) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY2694) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2689 marker;
TY2694 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NI, tseek214260) (trwops214268* context, NI offset, NI whence);
typedef N_CDECL_PTR(NI, tread214262) (trwops214268* context, void* theptr, NI size, NI maxnum);
typedef N_CDECL_PTR(NI, twrite214264) (trwops214268* context, void* theptr, NI size, NI num);
typedef N_CDECL_PTR(NI, tclose214266) (trwops214268* context);
struct  tmem214256  {
NU8* Base;
NU8* Here;
NU8* Stop;
};
struct  trwops214268  {
tseek214260 Seek;
tread214262 Read;
twrite214264 Write;
tclose214266 Closefile;
int Thetype;
tmem214256 Mem;
};
struct  trect215027  {
NI16 X;
NI16 Y;
NU16 W;
NU16 H;
};
struct  tsurface215055  {
NI32 Flags;
tpixelformat215045* Format;
int W;
int H;
NU16 Pitch;
void* Pixels;
int Offset;
void* Hwdata;
trect215027 Cliprect;
NI32 Unused1;
NI32 Locked;
void* Blitmap;
int Formatversion;
int Refcount;
};
struct  tpixelformat215045  {
tpalette215041* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
NI32 Rmask;
NI32 Gmask;
NI32 Bmask;
NI32 Amask;
NI32 Colorkey;
NU8 Alpha;
};
struct  tpalette215041  {
NI Ncolors;
tcolor215033* Colors;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_NIMCALL(void, version_221496)(tversion214328* x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_17801)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP717, "SDL_ttf.dll", 11);
STRING_LITERAL(TMP718, "SDL_ttf.dll", 11);
static void* TMP716;
TY221229 Dl_221228;
TY221235 Dl_221234;
TY221241 Dl_221240;
TY221246 Dl_221245;
TY221253 Dl_221252;
TY221261 Dl_221260;
TY221269 Dl_221268;
TY221278 Dl_221277;
TY221284 Dl_221283;
TY221291 Dl_221290;
TY221297 Dl_221296;
TY221303 Dl_221302;
TY221309 Dl_221308;
TY221315 Dl_221314;
TY221321 Dl_221320;
TY221327 Dl_221326;
TY221333 Dl_221332;
TY221339 Dl_221338;
TY221356 Dl_221355;
TY221367 Dl_221366;
TY221378 Dl_221377;
TY221389 Dl_221388;
TY221397 Dl_221396;
TY221405 Dl_221404;
TY221413 Dl_221412;
TY221422 Dl_221421;
TY221431 Dl_221430;
TY221440 Dl_221439;
TY221449 Dl_221448;
TY221457 Dl_221456;
TY221465 Dl_221464;
TY221473 Dl_221472;
TY221481 Dl_221480;
TY221487 Dl_221486;
TY221492 Dl_221491;
extern TFrame* frameptr_15242;
TY221508 Dl_221507;
TNimType NTI221221; /* TFont */
TNimType NTI221219; /* PFont */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_15242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_15242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_15242;
	frameptr_15242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_17801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_15242 = (*frameptr_15242).prev;
}

N_NIMCALL(void, version_221496)(tversion214328* x) {
	nimfr("VERSION", "sdl_ttf.nim")
	nimln(331, "sdl_ttf.nim");
	(*x).Major = ((NU8) 2);
	nimln(332, "sdl_ttf.nim");
	(*x).Minor = ((NU8) 0);
	nimln(333, "sdl_ttf.nim");
	(*x).Patch = ((NU8) 8);
	popFrame();
}
N_NOINLINE(void, HEX00_sdl_ttfInit)(void) {
	nimfr("sdl_ttf", "sdl_ttf.nim")
	popFrame();
}

N_NOINLINE(void, HEX00_sdl_ttfDatInit)(void) {
static TNimNode TMP714[1];
NTI221221.size = sizeof(tfont221221);
NTI221221.kind = 18;
NTI221221.base = 0;
NTI221221.flags = 3;
TMP714[0].len = 0; TMP714[0].kind = 2;
NTI221221.node = &TMP714[0];
NTI221219.size = sizeof(tfont221221*);
NTI221219.kind = 21;
NTI221219.base = (&NTI221221);
NTI221219.flags = 3;
if (!((TMP716 = nimLoadLibrary((NimStringDesc*) &TMP717))
)) nimLoadLibraryError((NimStringDesc*) &TMP718);
	Dl_221228 = (TY221229) nimGetProcAddr(TMP716, "TTF_Linked_Version");
	Dl_221234 = (TY221235) nimGetProcAddr(TMP716, "TTF_ByteSwappedUNICODE");
	Dl_221240 = (TY221241) nimGetProcAddr(TMP716, "TTF_Init");
	Dl_221245 = (TY221246) nimGetProcAddr(TMP716, "TTF_OpenFont");
	Dl_221252 = (TY221253) nimGetProcAddr(TMP716, "TTF_OpenFontIndex");
	Dl_221260 = (TY221261) nimGetProcAddr(TMP716, "TTF_OpenFontRW");
	Dl_221268 = (TY221269) nimGetProcAddr(TMP716, "TTF_OpenFontIndexRW");
	Dl_221277 = (TY221278) nimGetProcAddr(TMP716, "TTF_GetFontStyle");
	Dl_221283 = (TY221284) nimGetProcAddr(TMP716, "TTF_SetFontStyle");
	Dl_221290 = (TY221291) nimGetProcAddr(TMP716, "TTF_FontHeight");
	Dl_221296 = (TY221297) nimGetProcAddr(TMP716, "TTF_FontAscent");
	Dl_221302 = (TY221303) nimGetProcAddr(TMP716, "TTF_FontDescent");
	Dl_221308 = (TY221309) nimGetProcAddr(TMP716, "TTF_FontLineSkip");
	Dl_221314 = (TY221315) nimGetProcAddr(TMP716, "TTF_FontFaces");
	Dl_221320 = (TY221321) nimGetProcAddr(TMP716, "TTF_FontFaceIsFixedWidth");
	Dl_221326 = (TY221327) nimGetProcAddr(TMP716, "TTF_FontFaceFamilyName");
	Dl_221332 = (TY221333) nimGetProcAddr(TMP716, "TTF_FontFaceStyleName");
	Dl_221338 = (TY221339) nimGetProcAddr(TMP716, "TTF_GlyphMetrics");
	Dl_221355 = (TY221356) nimGetProcAddr(TMP716, "TTF_SizeText");
	Dl_221366 = (TY221367) nimGetProcAddr(TMP716, "TTF_SizeUTF8");
	Dl_221377 = (TY221378) nimGetProcAddr(TMP716, "TTF_SizeUNICODE");
	Dl_221388 = (TY221389) nimGetProcAddr(TMP716, "TTF_RenderUTF8_Solid");
	Dl_221396 = (TY221397) nimGetProcAddr(TMP716, "TTF_RenderUNICODE_Solid");
	Dl_221404 = (TY221405) nimGetProcAddr(TMP716, "TTF_RenderGlyph_Solid");
	Dl_221412 = (TY221413) nimGetProcAddr(TMP716, "TTF_RenderText_Shaded");
	Dl_221421 = (TY221422) nimGetProcAddr(TMP716, "TTF_RenderUTF8_Shaded");
	Dl_221430 = (TY221431) nimGetProcAddr(TMP716, "TTF_RenderUNICODE_Shaded");
	Dl_221439 = (TY221440) nimGetProcAddr(TMP716, "TTF_RenderGlyph_Shaded");
	Dl_221448 = (TY221449) nimGetProcAddr(TMP716, "TTF_RenderText_Blended");
	Dl_221456 = (TY221457) nimGetProcAddr(TMP716, "TTF_RenderUTF8_Blended");
	Dl_221464 = (TY221465) nimGetProcAddr(TMP716, "TTF_RenderUNICODE_Blended");
	Dl_221472 = (TY221473) nimGetProcAddr(TMP716, "TTF_RenderGlyph_Blended");
	Dl_221480 = (TY221481) nimGetProcAddr(TMP716, "TTF_CloseFont");
	Dl_221486 = (TY221487) nimGetProcAddr(TMP716, "TTF_Quit");
	Dl_221491 = (TY221492) nimGetProcAddr(TMP716, "TTF_WasInit");
	Dl_221507 = (TY221508) nimGetProcAddr(TMP716, "TTF_RenderText_Solid");
}

