/* Generated by Nimrod Compiler v0.9.6 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nimrod\lib -o c:\users\simon\rationalnes_\rnes\nimcache\tables.o c:\users\simon\rationalnes_\rnes\nimcache\tables.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY207969 TY207969;
typedef struct ttable207972 ttable207972;
typedef struct tkeyvaluepairseq207975 tkeyvaluepairseq207975;
typedef struct tkeyvaluepair207978 tkeyvaluepair207978;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell43933 tcell43933;
typedef struct tcellseq43949 tcellseq43949;
typedef struct tgcheap46016 tgcheap46016;
typedef struct tcellset43945 tcellset43945;
typedef struct tpagedesc43941 tpagedesc43941;
typedef struct tmemregion26210 tmemregion26210;
typedef struct tsmallchunk25440 tsmallchunk25440;
typedef struct tllchunk26204 tllchunk26204;
typedef struct tbigchunk25442 tbigchunk25442;
typedef struct tintset25417 tintset25417;
typedef struct ttrunk25413 ttrunk25413;
typedef struct tavlnode26208 tavlnode26208;
typedef struct tgcstat46014 tgcstat46014;
typedef struct TY208603 TY208603;
typedef struct ttable208606 ttable208606;
typedef struct tkeyvaluepairseq208609 tkeyvaluepairseq208609;
typedef struct tkeyvaluepair208612 tkeyvaluepair208612;
typedef struct tbasechunk25438 tbasechunk25438;
typedef struct tfreecell25430 tfreecell25430;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY207074) (NI vbyte);
struct TY207969 {
NimStringDesc* Field0;
TY207074 Field1;
};
struct tkeyvaluepair207978 {
NU8 Field0;
NimStringDesc* Field1;
TY207074 Field2;
};
struct  ttable207972  {
tkeyvaluepairseq207975* Data;
NI Counter;
};
typedef N_NIMCALL_PTR(void, TY2689) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY2694) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2689 marker;
TY2694 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell43933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq43949  {
NI Len;
NI Cap;
tcell43933** D;
};
struct  tcellset43945  {
NI Counter;
NI Max;
tpagedesc43941* Head;
tpagedesc43941** Data;
};
typedef tsmallchunk25440* TY26222[512];
typedef ttrunk25413* ttrunkbuckets25415[256];
struct  tintset25417  {
ttrunkbuckets25415 Data;
};
struct  tmemregion26210  {
NI Minlargeobj;
NI Maxlargeobj;
TY26222 Freesmallchunks;
tllchunk26204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk25442* Freechunkslist;
tintset25417 Chunkstarts;
tavlnode26208* Root;
tavlnode26208* Deleted;
tavlnode26208* Last;
tavlnode26208* Freeavlnodes;
};
struct  tgcstat46014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap46016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq43949 Zct;
tcellseq43949 Decstack;
tcellset43945 Cycleroots;
tcellseq43949 Tempstack;
NI Recgclock;
tmemregion26210 Region;
tgcstat46014 Stat;
};
typedef N_NIMCALL_PTR(NI, TY207712) (void);
struct TY208603 {
NimStringDesc* Field0;
TY207712 Field1;
};
struct tkeyvaluepair208612 {
NU8 Field0;
NimStringDesc* Field1;
TY207712 Field2;
};
struct  ttable208606  {
tkeyvaluepairseq208609* Data;
NI Counter;
};
typedef NI TY25420[8];
struct  tpagedesc43941  {
tpagedesc43941* Next;
NI Key;
TY25420 Bits;
};
struct  tbasechunk25438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk25440  {
  tbasechunk25438 Sup;
tsmallchunk25440* Next;
tsmallchunk25440* Prev;
tfreecell25430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk26204  {
NI Size;
NI Acc;
tllchunk26204* Next;
};
struct  tbigchunk25442  {
  tbasechunk25438 Sup;
tbigchunk25442* Next;
tbigchunk25442* Prev;
NI Align;
NF Data;
};
struct  ttrunk25413  {
ttrunk25413* Next;
NI Key;
TY25420 Bits;
};
typedef tavlnode26208* TY26214[2];
struct  tavlnode26208  {
TY26214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell25430  {
tfreecell25430* Next;
NI Zerofield;
};
struct tkeyvaluepairseq207975 {
  TGenericSeq Sup;
  tkeyvaluepair207978 data[SEQ_DECL_SIZE];
};
struct tkeyvaluepairseq208609 {
  TGenericSeq Sup;
  tkeyvaluepair208612 data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, mustrehash_199428)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_85825)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_17801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, nexttry_199610)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, inittable_207992)(NI initialsize_207997, ttable207972* Result);
N_NIMCALL(NIM_BOOL, ispoweroftwo_193318)(NI x);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP423)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NI, nextpoweroftwo_193328)(NI x);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, HEX5BHEX5DHEX3D_208275)(ttable207972* t_208284, NimStringDesc* key_208288, TY207074 val_208290);
N_NIMCALL(NI, rawget_208293)(ttable207972 t_208300, NimStringDesc* key_208303);
N_NIMCALL(NI, hash_197842)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, enlarge_208350)(ttable207972* t_208359);
N_NIMCALL(void, rawinsert_208420)(ttable207972* t_208429, tkeyvaluepairseq207975** data_208437, NimStringDesc* key_208441, TY207074 val_208443);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell43933*, usrtocell_47646)(void* usr);
static N_INLINE(void, rtladdzct_49204)(tcell43933* c);
N_NOINLINE(void, addzct_47617)(tcellseq43949* s, tcell43933* c);
N_NIMCALL(void, inittable_208626)(NI initialsize_208631, ttable208606* Result);
N_NIMCALL(void, TMP428)(void* p, NI op);
N_NIMCALL(void, HEX5BHEX5DHEX3D_208875)(ttable208606* t_208884, NimStringDesc* key_208888, TY207712 val_208890);
N_NIMCALL(NI, rawget_208893)(ttable208606 t_208900, NimStringDesc* key_208903);
N_NIMCALL(void, enlarge_208950)(ttable208606* t_208959);
N_NIMCALL(void, rawinsert_209020)(ttable208606* t_209029, tkeyvaluepairseq208609** data_209037, NimStringDesc* key_209041, TY207712 val_209043);
STRING_LITERAL(TMP341, "length > counter ", 17);
STRING_LITERAL(TMP418, "isPowerOfTwo(initialSize) ", 26);
extern TFrame* frameptr_15242;
TNimType NTI207978; /* TKeyValuePair */
TNimType NTI199009; /* TSlotEnum */
extern TNimType NTI161; /* string */
extern TNimType NTI207074; /* proc (int) */
TNimType NTI207975; /* TKeyValuePairSeq */
TNimType NTI207972; /* TTable */
extern TNimType NTI116; /* int */
extern tgcheap46016 gch_46044;
TNimType NTI208612; /* TKeyValuePair */
extern TNimType NTI207712; /* proc (): int */
TNimType NTI208609; /* TKeyValuePairSeq */
TNimType NTI208606; /* TTable */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_15242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_15242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_15242;
	frameptr_15242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_17801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_15242 = (*frameptr_15242).prev;
}

static N_INLINE(NIM_BOOL, mustrehash_199428)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP342;
	NI TMP343;
	NI TMP344;
	nimfr("mustRehash", "tables.nim")
	result = 0;
	nimln(109, "tables.nim");
	{
		nimln(109, "tables.nim");
		nimln(109, "tables.nim");
		if (!!((counter < length))) goto LA3;
		nimln(109, "tables.nim");
		failedassertimpl_85825(((NimStringDesc*) &TMP341));
	}
	LA3: ;
	nimln(110, "tables.nim");
	nimln(110, "tables.nim");
	LOC5 = 0;
	nimln(110, "tables.nim");
	nimln(110, "tables.nim");
	TMP342 = mulInt(length, 2);
	nimln(110, "tables.nim");
	TMP343 = mulInt(counter, 3);
	LOC5 = ((NI64)(TMP342) < (NI64)(TMP343));
	if (LOC5) goto LA6;
	nimln(110, "tables.nim");
	nimln(110, "tables.nim");
	TMP344 = subInt(length, counter);
	LOC5 = ((NI64)(TMP344) < 4);
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_199610)(NI h, NI maxhash) {
	NI result;
	NI TMP345;
	NI TMP346;
	nimfr("nextTry", "tables.nim")
	result = 0;
	nimln(113, "tables.nim");
	nimln(113, "tables.nim");
	nimln(113, "tables.nim");
	nimln(113, "tables.nim");
	TMP345 = mulInt(5, h);
	TMP346 = addInt((NI64)(TMP345), 1);
	result = (NI)((NI64)(TMP346) & maxhash);
	popFrame();
	return result;
}
N_NIMCALL(void, TMP423)(void* p, NI op) {
	tkeyvaluepairseq207975* a;
	NI LOC1;
	a = (tkeyvaluepairseq207975*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}

N_NIMCALL(void, inittable_207992)(NI initialsize_207997, ttable207972* Result) {
	nimfr("initTable", "tables.nim")
	nimln(218, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(218, "tables.nim");
		nimln(218, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_193318(initialsize_207997);
		if (!!(LOC3)) goto LA4;
		nimln(218, "tables.nim");
		failedassertimpl_85825(((NimStringDesc*) &TMP418));
	}
	LA4: ;
	nimln(219, "tables.nim");
	(*Result).Counter = 0;
	nimln(220, "tables.nim");
	unsureAsgnRef((void**) &(*Result).Data, (tkeyvaluepairseq207975*) newSeq((&NTI207975), initialsize_207997));
	popFrame();
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, rawget_208293)(ttable207972 t_208300, NimStringDesc* key_208303) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "tables.nim")
	result = 0;
	nimln(116, "tables.nim");
	nimln(116, "tables.nim");
	nimln(116, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_197842(key_208303);
	nimln(116, "tables.nim");
	h = (NI)(LOC1 & (t_208300.Data->Sup.len-1));
	{
		nimln(117, "tables.nim");
		while (1) {
			nimln(117, "tables.nim");
			nimln(117, "tables.nim");
			if ((NU)(h) >= (NU)(t_208300.Data->Sup.len)) raiseIndexError();
			if (!!((t_208300.Data->data[h].Field0 == ((NU8) 0)))) goto LA3;
			nimln(118, "tables.nim");
			{
				NIM_BOOL LOC6;
				nimln(118, "tables.nim");
				LOC6 = 0;
				nimln(118, "tables.nim");
				if ((NU)(h) >= (NU)(t_208300.Data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings(t_208300.Data->data[h].Field1, key_208303);
				if (!(LOC6)) goto LA7;
				nimln(118, "tables.nim");
				if ((NU)(h) >= (NU)(t_208300.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_208300.Data->data[h].Field0 == ((NU8) 1));
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(119, "tables.nim");
				nimln(119, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(120, "tables.nim");
			nimln(120, "tables.nim");
			h = nexttry_199610(h, (t_208300.Data->Sup.len-1));
		} LA3: ;
	}
	nimln(121, "tables.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(tcell43933*, usrtocell_47646)(void* usr) {
	tcell43933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell43933*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell43933))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_49204)(tcell43933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_47617(&gch_46044.Zct, c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell43933* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_47646(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_49204(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, rawinsert_208420)(ttable207972* t_208429, tkeyvaluepairseq207975** data_208437, NimStringDesc* key_208441, TY207074 val_208443) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC4;
	nimfr("rawInsert", "tables.nim")
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_197842(key_208441);
	nimln(124, "tables.nim");
	h = (NI)(LOC1 & ((*data_208437)->Sup.len-1));
	{
		nimln(125, "tables.nim");
		while (1) {
			nimln(125, "tables.nim");
			if ((NU)(h) >= (NU)((*data_208437)->Sup.len)) raiseIndexError();
			if (!((*data_208437)->data[h].Field0 == ((NU8) 1))) goto LA3;
			nimln(126, "tables.nim");
			nimln(126, "tables.nim");
			h = nexttry_199610(h, ((*data_208437)->Sup.len-1));
		} LA3: ;
	}
	nimln(127, "tables.nim");
	if ((NU)(h) >= (NU)((*data_208437)->Sup.len)) raiseIndexError();
	LOC4 = 0;
	LOC4 = (*data_208437)->data[h].Field1; (*data_208437)->data[h].Field1 = copyStringRC1(key_208441);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(128, "tables.nim");
	if ((NU)(h) >= (NU)((*data_208437)->Sup.len)) raiseIndexError();
	(*data_208437)->data[h].Field2 = val_208443;
	nimln(129, "tables.nim");
	if ((NU)(h) >= (NU)((*data_208437)->Sup.len)) raiseIndexError();
	(*data_208437)->data[h].Field0 = ((NU8) 1);
	popFrame();
}

N_NIMCALL(void, enlarge_208350)(ttable207972* t_208359) {
	tkeyvaluepairseq207975* n;
	NI TMP426;
	tkeyvaluepairseq207975* LOC8;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(167, "tables.nim");
	nimln(167, "tables.nim");
	nimln(167, "tables.nim");
	TMP426 = mulInt((*t_208359).Data->Sup.len, 2);
	n = (tkeyvaluepairseq207975*) newSeq((&NTI207975), (NI64)(TMP426));
	{
		NI i_208405;
		NI HEX3Atmp_208484;
		NI res_208487;
		i_208405 = 0;
		HEX3Atmp_208484 = 0;
		nimln(168, "tables.nim");
		nimln(168, "tables.nim");
		HEX3Atmp_208484 = ((*t_208359).Data->Sup.len-1);
		nimln(1544, "system.nim");
		res_208487 = 0;
		{
			nimln(1545, "system.nim");
			while (1) {
				nimln(1545, "system.nim");
				if (!(res_208487 <= HEX3Atmp_208484)) goto LA3;
				nimln(1544, "system.nim");
				i_208405 = res_208487;
				nimln(169, "tables.nim");
				{
					nimln(169, "tables.nim");
					if ((NU)(i_208405) >= (NU)((*t_208359).Data->Sup.len)) raiseIndexError();
					if (!((*t_208359).Data->data[i_208405].Field0 == ((NU8) 1))) goto LA6;
					nimln(169, "tables.nim");
					if ((NU)(i_208405) >= (NU)((*t_208359).Data->Sup.len)) raiseIndexError();
					if ((NU)(i_208405) >= (NU)((*t_208359).Data->Sup.len)) raiseIndexError();
					rawinsert_208420(t_208359, &n, (*t_208359).Data->data[i_208405].Field1, (*t_208359).Data->data[i_208405].Field2);
				}
				LA6: ;
				nimln(1547, "system.nim");
				res_208487 = addInt(res_208487, 1);
			} LA3: ;
		}
	}
	nimln(170, "tables.nim");
	LOC8 = 0;
	LOC8 = (*t_208359).Data;
	unsureAsgnRef((void**) &(*t_208359).Data, n);
	n = LOC8;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_208275)(ttable207972* t_208284, NimStringDesc* key_208288, TY207074 val_208290) {
	NI index;
	nimfr("[]=", "tables.nim")
	nimln(178, "tables.nim");
	index = rawget_208293((*t_208284), key_208288);
	nimln(179, "tables.nim");
	{
		nimln(179, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(180, "tables.nim");
		if ((NU)(index) >= (NU)((*t_208284).Data->Sup.len)) raiseIndexError();
		(*t_208284).Data->data[index].Field2 = val_208290;
	}
	goto LA1;
	LA3: ;
	{
		nimln(173, "tables.nim");
		{
			NIM_BOOL LOC8;
			nimln(173, "tables.nim");
			nimln(173, "tables.nim");
			LOC8 = 0;
			LOC8 = mustrehash_199428((*t_208284).Data->Sup.len, (*t_208284).Counter);
			if (!LOC8) goto LA9;
			nimln(173, "tables.nim");
			enlarge_208350(t_208284);
		}
		LA9: ;
		nimln(174, "tables.nim");
		rawinsert_208420(t_208284, &(*t_208284).Data, key_208288, val_208290);
		nimln(175, "tables.nim");
		(*t_208284).Counter = addInt((*t_208284).Counter, 1);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(void, totable_207954)(TY207969* pairs_207967, NI pairs_207967Len0, ttable207972* Result) {
	NI TMP424;
	NI LOC1;
	nimfr("toTable", "tables.nim")
	nimln(225, "tables.nim");
	nimln(225, "tables.nim");
	nimln(225, "tables.nim");
	nimln(225, "tables.nim");
	TMP424 = addInt(pairs_207967Len0, 10);
	LOC1 = 0;
	LOC1 = nextpoweroftwo_193328((NI64)(TMP424));
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI207972));
	inittable_207992(LOC1, Result);
	{
		NimStringDesc* key_208270;
		TY207074 val_208271;
		NI i_208550;
		key_208270 = 0;
		val_208271 = 0;
		nimln(1624, "system.nim");
		i_208550 = 0;
		{
			nimln(1625, "system.nim");
			while (1) {
				nimln(1625, "system.nim");
				nimln(1625, "system.nim");
				if (!(i_208550 < pairs_207967Len0)) goto LA4;
				nimln(1626, "system.nim");
				if ((NU)(i_208550) >= (NU)(pairs_207967Len0)) raiseIndexError();
				key_208270 = pairs_207967[i_208550].Field0;
				nimln(1626, "system.nim");
				if ((NU)(i_208550) >= (NU)(pairs_207967Len0)) raiseIndexError();
				val_208271 = pairs_207967[i_208550].Field1;
				nimln(226, "tables.nim");
				HEX5BHEX5DHEX3D_208275(Result, key_208270, val_208271);
				nimln(1627, "system.nim");
				i_208550 = addInt(i_208550, 1);
			} LA4: ;
		}
	}
	popFrame();
}
N_NIMCALL(void, TMP428)(void* p, NI op) {
	tkeyvaluepairseq208609* a;
	NI LOC1;
	a = (tkeyvaluepairseq208609*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}

N_NIMCALL(void, inittable_208626)(NI initialsize_208631, ttable208606* Result) {
	nimfr("initTable", "tables.nim")
	nimln(218, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(218, "tables.nim");
		nimln(218, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_193318(initialsize_208631);
		if (!!(LOC3)) goto LA4;
		nimln(218, "tables.nim");
		failedassertimpl_85825(((NimStringDesc*) &TMP418));
	}
	LA4: ;
	nimln(219, "tables.nim");
	(*Result).Counter = 0;
	nimln(220, "tables.nim");
	unsureAsgnRef((void**) &(*Result).Data, (tkeyvaluepairseq208609*) newSeq((&NTI208609), initialsize_208631));
	popFrame();
}

N_NIMCALL(NI, rawget_208893)(ttable208606 t_208900, NimStringDesc* key_208903) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "tables.nim")
	result = 0;
	nimln(116, "tables.nim");
	nimln(116, "tables.nim");
	nimln(116, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_197842(key_208903);
	nimln(116, "tables.nim");
	h = (NI)(LOC1 & (t_208900.Data->Sup.len-1));
	{
		nimln(117, "tables.nim");
		while (1) {
			nimln(117, "tables.nim");
			nimln(117, "tables.nim");
			if ((NU)(h) >= (NU)(t_208900.Data->Sup.len)) raiseIndexError();
			if (!!((t_208900.Data->data[h].Field0 == ((NU8) 0)))) goto LA3;
			nimln(118, "tables.nim");
			{
				NIM_BOOL LOC6;
				nimln(118, "tables.nim");
				LOC6 = 0;
				nimln(118, "tables.nim");
				if ((NU)(h) >= (NU)(t_208900.Data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings(t_208900.Data->data[h].Field1, key_208903);
				if (!(LOC6)) goto LA7;
				nimln(118, "tables.nim");
				if ((NU)(h) >= (NU)(t_208900.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_208900.Data->data[h].Field0 == ((NU8) 1));
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(119, "tables.nim");
				nimln(119, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(120, "tables.nim");
			nimln(120, "tables.nim");
			h = nexttry_199610(h, (t_208900.Data->Sup.len-1));
		} LA3: ;
	}
	nimln(121, "tables.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, rawinsert_209020)(ttable208606* t_209029, tkeyvaluepairseq208609** data_209037, NimStringDesc* key_209041, TY207712 val_209043) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC4;
	nimfr("rawInsert", "tables.nim")
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_197842(key_209041);
	nimln(124, "tables.nim");
	h = (NI)(LOC1 & ((*data_209037)->Sup.len-1));
	{
		nimln(125, "tables.nim");
		while (1) {
			nimln(125, "tables.nim");
			if ((NU)(h) >= (NU)((*data_209037)->Sup.len)) raiseIndexError();
			if (!((*data_209037)->data[h].Field0 == ((NU8) 1))) goto LA3;
			nimln(126, "tables.nim");
			nimln(126, "tables.nim");
			h = nexttry_199610(h, ((*data_209037)->Sup.len-1));
		} LA3: ;
	}
	nimln(127, "tables.nim");
	if ((NU)(h) >= (NU)((*data_209037)->Sup.len)) raiseIndexError();
	LOC4 = 0;
	LOC4 = (*data_209037)->data[h].Field1; (*data_209037)->data[h].Field1 = copyStringRC1(key_209041);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(128, "tables.nim");
	if ((NU)(h) >= (NU)((*data_209037)->Sup.len)) raiseIndexError();
	(*data_209037)->data[h].Field2 = val_209043;
	nimln(129, "tables.nim");
	if ((NU)(h) >= (NU)((*data_209037)->Sup.len)) raiseIndexError();
	(*data_209037)->data[h].Field0 = ((NU8) 1);
	popFrame();
}

N_NIMCALL(void, enlarge_208950)(ttable208606* t_208959) {
	tkeyvaluepairseq208609* n;
	NI TMP431;
	tkeyvaluepairseq208609* LOC8;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(167, "tables.nim");
	nimln(167, "tables.nim");
	nimln(167, "tables.nim");
	TMP431 = mulInt((*t_208959).Data->Sup.len, 2);
	n = (tkeyvaluepairseq208609*) newSeq((&NTI208609), (NI64)(TMP431));
	{
		NI i_209005;
		NI HEX3Atmp_209084;
		NI res_209087;
		i_209005 = 0;
		HEX3Atmp_209084 = 0;
		nimln(168, "tables.nim");
		nimln(168, "tables.nim");
		HEX3Atmp_209084 = ((*t_208959).Data->Sup.len-1);
		nimln(1544, "system.nim");
		res_209087 = 0;
		{
			nimln(1545, "system.nim");
			while (1) {
				nimln(1545, "system.nim");
				if (!(res_209087 <= HEX3Atmp_209084)) goto LA3;
				nimln(1544, "system.nim");
				i_209005 = res_209087;
				nimln(169, "tables.nim");
				{
					nimln(169, "tables.nim");
					if ((NU)(i_209005) >= (NU)((*t_208959).Data->Sup.len)) raiseIndexError();
					if (!((*t_208959).Data->data[i_209005].Field0 == ((NU8) 1))) goto LA6;
					nimln(169, "tables.nim");
					if ((NU)(i_209005) >= (NU)((*t_208959).Data->Sup.len)) raiseIndexError();
					if ((NU)(i_209005) >= (NU)((*t_208959).Data->Sup.len)) raiseIndexError();
					rawinsert_209020(t_208959, &n, (*t_208959).Data->data[i_209005].Field1, (*t_208959).Data->data[i_209005].Field2);
				}
				LA6: ;
				nimln(1547, "system.nim");
				res_209087 = addInt(res_209087, 1);
			} LA3: ;
		}
	}
	nimln(170, "tables.nim");
	LOC8 = 0;
	LOC8 = (*t_208959).Data;
	unsureAsgnRef((void**) &(*t_208959).Data, n);
	n = LOC8;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_208875)(ttable208606* t_208884, NimStringDesc* key_208888, TY207712 val_208890) {
	NI index;
	nimfr("[]=", "tables.nim")
	nimln(178, "tables.nim");
	index = rawget_208893((*t_208884), key_208888);
	nimln(179, "tables.nim");
	{
		nimln(179, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(180, "tables.nim");
		if ((NU)(index) >= (NU)((*t_208884).Data->Sup.len)) raiseIndexError();
		(*t_208884).Data->data[index].Field2 = val_208890;
	}
	goto LA1;
	LA3: ;
	{
		nimln(173, "tables.nim");
		{
			NIM_BOOL LOC8;
			nimln(173, "tables.nim");
			nimln(173, "tables.nim");
			LOC8 = 0;
			LOC8 = mustrehash_199428((*t_208884).Data->Sup.len, (*t_208884).Counter);
			if (!LOC8) goto LA9;
			nimln(173, "tables.nim");
			enlarge_208950(t_208884);
		}
		LA9: ;
		nimln(174, "tables.nim");
		rawinsert_209020(t_208884, &(*t_208884).Data, key_208888, val_208890);
		nimln(175, "tables.nim");
		(*t_208884).Counter = addInt((*t_208884).Counter, 1);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(void, totable_208588)(TY208603* pairs_208601, NI pairs_208601Len0, ttable208606* Result) {
	NI TMP429;
	NI LOC1;
	nimfr("toTable", "tables.nim")
	nimln(225, "tables.nim");
	nimln(225, "tables.nim");
	nimln(225, "tables.nim");
	nimln(225, "tables.nim");
	TMP429 = addInt(pairs_208601Len0, 10);
	LOC1 = 0;
	LOC1 = nextpoweroftwo_193328((NI64)(TMP429));
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI208606));
	inittable_208626(LOC1, Result);
	{
		NimStringDesc* key_208870;
		TY207712 val_208871;
		NI i_209150;
		key_208870 = 0;
		val_208871 = 0;
		nimln(1624, "system.nim");
		i_209150 = 0;
		{
			nimln(1625, "system.nim");
			while (1) {
				nimln(1625, "system.nim");
				nimln(1625, "system.nim");
				if (!(i_209150 < pairs_208601Len0)) goto LA4;
				nimln(1626, "system.nim");
				if ((NU)(i_209150) >= (NU)(pairs_208601Len0)) raiseIndexError();
				key_208870 = pairs_208601[i_209150].Field0;
				nimln(1626, "system.nim");
				if ((NU)(i_209150) >= (NU)(pairs_208601Len0)) raiseIndexError();
				val_208871 = pairs_208601[i_209150].Field1;
				nimln(226, "tables.nim");
				HEX5BHEX5DHEX3D_208875(Result, key_208870, val_208871);
				nimln(1627, "system.nim");
				i_209150 = addInt(i_209150, 1);
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(TY207712, HEX5BHEX5D_209889)(ttable208606 t_209896, NimStringDesc* key_209899) {
	TY207712 result;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	nimln(139, "tables.nim");
	index = rawget_208893(t_209896, key_209899);
	nimln(140, "tables.nim");
	{
		nimln(140, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(140, "tables.nim");
		if ((NU)(index) >= (NU)(t_209896.Data->Sup.len)) raiseIndexError();
		result = t_209896.Data->data[index].Field2;
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(TY207074, HEX5BHEX5D_209922)(ttable207972 t_209929, NimStringDesc* key_209932) {
	TY207074 result;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	nimln(139, "tables.nim");
	index = rawget_208293(t_209929, key_209932);
	nimln(140, "tables.nim");
	{
		nimln(140, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(140, "tables.nim");
		if ((NU)(index) >= (NU)(t_209929.Data->Sup.len)) raiseIndexError();
		result = t_209929.Data->data[index].Field2;
	}
	LA3: ;
	popFrame();
	return result;
}
N_NOINLINE(void, HEX00_tablesInit)(void) {
	nimfr("tables", "tables.nim")
	popFrame();
}

N_NOINLINE(void, HEX00_tablesDatInit)(void) {
static TNimNode* TMP419[3];
static TNimNode* TMP420[3];
NI TMP422;
static char* NIM_CONST TMP421[3] = {
"seEmpty", 
"seFilled", 
"seDeleted"};
static TNimNode* TMP425[2];
static TNimNode* TMP427[3];
static TNimNode* TMP430[2];
static TNimNode TMP332[18];
NTI207978.size = sizeof(tkeyvaluepair207978);
NTI207978.kind = 18;
NTI207978.base = 0;
NTI207978.flags = 2;
TMP419[0] = &TMP332[1];
NTI199009.size = sizeof(NU8);
NTI199009.kind = 14;
NTI199009.base = 0;
NTI199009.flags = 3;
for (TMP422 = 0; TMP422 < 3; TMP422++) {
TMP332[TMP422+2].kind = 1;
TMP332[TMP422+2].offset = TMP422;
TMP332[TMP422+2].name = TMP421[TMP422];
TMP420[TMP422] = &TMP332[TMP422+2];
}
TMP332[5].len = 3; TMP332[5].kind = 2; TMP332[5].sons = &TMP420[0];
NTI199009.node = &TMP332[5];
TMP332[1].kind = 1;
TMP332[1].offset = offsetof(tkeyvaluepair207978, Field0);
TMP332[1].typ = (&NTI199009);
TMP332[1].name = "Field0";
TMP419[1] = &TMP332[6];
TMP332[6].kind = 1;
TMP332[6].offset = offsetof(tkeyvaluepair207978, Field1);
TMP332[6].typ = (&NTI161);
TMP332[6].name = "Field1";
TMP419[2] = &TMP332[7];
TMP332[7].kind = 1;
TMP332[7].offset = offsetof(tkeyvaluepair207978, Field2);
TMP332[7].typ = (&NTI207074);
TMP332[7].name = "Field2";
TMP332[0].len = 3; TMP332[0].kind = 2; TMP332[0].sons = &TMP419[0];
NTI207978.node = &TMP332[0];
NTI207975.size = sizeof(tkeyvaluepairseq207975*);
NTI207975.kind = 24;
NTI207975.base = (&NTI207978);
NTI207975.flags = 2;
NTI207975.marker = TMP423;
NTI207972.size = sizeof(ttable207972);
NTI207972.kind = 18;
NTI207972.base = 0;
NTI207972.flags = 2;
TMP425[0] = &TMP332[9];
TMP332[9].kind = 1;
TMP332[9].offset = offsetof(ttable207972, Data);
TMP332[9].typ = (&NTI207975);
TMP332[9].name = "data";
TMP425[1] = &TMP332[10];
TMP332[10].kind = 1;
TMP332[10].offset = offsetof(ttable207972, Counter);
TMP332[10].typ = (&NTI116);
TMP332[10].name = "counter";
TMP332[8].len = 2; TMP332[8].kind = 2; TMP332[8].sons = &TMP425[0];
NTI207972.node = &TMP332[8];
NTI208612.size = sizeof(tkeyvaluepair208612);
NTI208612.kind = 18;
NTI208612.base = 0;
NTI208612.flags = 2;
TMP427[0] = &TMP332[12];
TMP332[12].kind = 1;
TMP332[12].offset = offsetof(tkeyvaluepair208612, Field0);
TMP332[12].typ = (&NTI199009);
TMP332[12].name = "Field0";
TMP427[1] = &TMP332[13];
TMP332[13].kind = 1;
TMP332[13].offset = offsetof(tkeyvaluepair208612, Field1);
TMP332[13].typ = (&NTI161);
TMP332[13].name = "Field1";
TMP427[2] = &TMP332[14];
TMP332[14].kind = 1;
TMP332[14].offset = offsetof(tkeyvaluepair208612, Field2);
TMP332[14].typ = (&NTI207712);
TMP332[14].name = "Field2";
TMP332[11].len = 3; TMP332[11].kind = 2; TMP332[11].sons = &TMP427[0];
NTI208612.node = &TMP332[11];
NTI208609.size = sizeof(tkeyvaluepairseq208609*);
NTI208609.kind = 24;
NTI208609.base = (&NTI208612);
NTI208609.flags = 2;
NTI208609.marker = TMP428;
NTI208606.size = sizeof(ttable208606);
NTI208606.kind = 18;
NTI208606.base = 0;
NTI208606.flags = 2;
TMP430[0] = &TMP332[16];
TMP332[16].kind = 1;
TMP332[16].offset = offsetof(ttable208606, Data);
TMP332[16].typ = (&NTI208609);
TMP332[16].name = "data";
TMP430[1] = &TMP332[17];
TMP332[17].kind = 1;
TMP332[17].offset = offsetof(ttable208606, Counter);
TMP332[17].typ = (&NTI116);
TMP332[17].name = "counter";
TMP332[15].len = 2; TMP332[15].kind = 2; TMP332[15].sons = &TMP430[0];
NTI208606.node = &TMP332[15];
}

