/* Generated by Nimrod Compiler v0.9.4 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files (x86)\Nimrod\dist\mingw\bin\gcc.exe" -c  -w  -I"C:\Program Files (x86)\Nimrod\lib" -o c:\users\simon\rationalnes_\nimcache\typeinfo.o c:\users\simon\rationalnes_\nimcache\typeinfo.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct tnimnode123207 tnimnode123207;
typedef struct tnimtype123211 tnimtype123211;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tany123298 tany123298;
typedef struct TNimType TNimType;
typedef struct tgenseq123304 tgenseq123304;
typedef struct einvalidindex2459 einvalidindex2459;
typedef struct esynch2429 esynch2429;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct TNimNode TNimNode;
typedef struct tcell41088 tcell41088;
typedef struct tcellseq41104 tcellseq41104;
typedef struct tgcheap43016 tgcheap43016;
typedef struct tcellset41100 tcellset41100;
typedef struct tpagedesc41096 tpagedesc41096;
typedef struct tmemregion23410 tmemregion23410;
typedef struct tsmallchunk22638 tsmallchunk22638;
typedef struct tllchunk23404 tllchunk23404;
typedef struct tbigchunk22640 tbigchunk22640;
typedef struct tintset22615 tintset22615;
typedef struct ttrunk22611 ttrunk22611;
typedef struct tavlnode23408 tavlnode23408;
typedef struct tgcstat43014 tgcstat43014;
typedef struct einvalidvalue2453 einvalidvalue2453;
typedef struct TY126424 TY126424;
typedef struct TY126603 TY126603;
typedef struct tbasechunk22636 tbasechunk22636;
typedef struct tfreecell22628 tfreecell22628;
struct  tnimnode123207  {
NU8 Kind;
NI Offset;
tnimtype123211* Typ;
NCSTRING Name;
NI Len;
tnimnode123207** Sons;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY123288) (void* p, NI op);
struct  tnimtype123211  {
NI Size;
NU8 Kind;
NU8 Flags;
tnimtype123211* Base;
tnimnode123207* Node;
void* Finalizer;
TY123288 Marker;
};
struct  tany123298  {
void* Value;
tnimtype123211* Rawtype;
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  E_Base  {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  esynch2429  {
  E_Base Sup;
};
struct  einvalidindex2459  {
  esynch2429 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell41088  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq41104  {
NI Len;
NI Cap;
tcell41088** D;
};
struct  tcellset41100  {
NI Counter;
NI Max;
tpagedesc41096* Head;
tpagedesc41096** Data;
};
typedef tsmallchunk22638* TY23422[512];
typedef ttrunk22611* ttrunkbuckets22613[256];
struct  tintset22615  {
ttrunkbuckets22613 Data;
};
struct  tmemregion23410  {
NI Minlargeobj;
NI Maxlargeobj;
TY23422 Freesmallchunks;
tllchunk23404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk22640* Freechunkslist;
tintset22615 Chunkstarts;
tavlnode23408* Root;
tavlnode23408* Deleted;
tavlnode23408* Last;
tavlnode23408* Freeavlnodes;
};
struct  tgcstat43014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap43016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq41104 Zct;
tcellseq41104 Decstack;
tcellset41100 Cycleroots;
tcellseq41104 Tempstack;
NI Recgclock;
tmemregion23410 Region;
tgcstat43014 Stat;
};
struct  einvalidvalue2453  {
  esynch2429 Sup;
};
struct  tgenseq123304  {
NI Len;
NI Space;
};
struct TY126603 {
NCSTRING Field0;
tany123298 Field1;
};
typedef NI TY22618[8];
struct  tpagedesc41096  {
tpagedesc41096* Next;
NI Key;
TY22618 Bits;
};
struct  tbasechunk22636  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk22638  {
  tbasechunk22636 Sup;
tsmallchunk22638* Next;
tsmallchunk22638* Prev;
tfreecell22628* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk23404  {
NI Size;
NI Acc;
tllchunk23404* Next;
};
struct  tbigchunk22640  {
  tbasechunk22636 Sup;
tbigchunk22640* Next;
tbigchunk22640* Prev;
NI Align;
NF Data;
};
struct  ttrunk22611  {
ttrunk22611* Next;
NI Key;
TY22618 Bits;
};
typedef tavlnode23408* TY23414[2];
struct  tavlnode23408  {
TY23414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell22628  {
tfreecell22628* Next;
NI Zerofield;
};
struct TY126424 {
  TGenericSeq Sup;
  TY126603 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, getdiscriminant_123406)(void* aa, tnimnode123207* n);
N_NIMCALL(void, failedassertimpl_81021)(NimStringDesc* msg);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(tnimnode123207*, selectbranch_123809)(void* aa, tnimnode123207* n);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(tany123298, newany_123845)(void* value, tnimtype123211* rawtype);
static N_INLINE(NU8, kind_124010)(tany123298 x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, size_124024)(tany123298 x);
static N_INLINE(NU8, basetypekind_124030)(tany123298 x);
static N_INLINE(NI, basetypesize_124061)(tany123298 x);
N_NIMCALL(void, invokenew_124084)(tany123298 x);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, invokenewseq_124214)(tany123298 x, NI len);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, extendseq_124414)(tany123298 x);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(void, setobjectruntimetype_124617)(tany123298 x);
N_NIMCALL(void, objectInit)(void* dest, TNimType* typ);
static N_INLINE(tnimtype123211*, skiprange_124812)(tnimtype123211* x);
N_NIMCALL(tany123298, HEX5BHEX5D_124827)(tany123298 x, NI i);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell41088*, usrtocell_44443)(void* usr);
static N_INLINE(void, rtladdzct_46002)(tcell41088* c);
N_NOINLINE(void, addzct_44418)(tcellseq41104* s, tcell41088* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, HEX5BHEX5DHEX3D_125012)(tany123298 x, NI i, tany123298 y);
N_NIMCALL(NI, len_125612)(tany123298 x);
N_NIMCALL(tany123298, base_125805)(tany123298 x);
N_NIMCALL(NIM_BOOL, isnil_125811)(tany123298 x);
N_NIMCALL(void*, getpointer_126018)(tany123298 x);
N_NIMCALL(void, setpointer_126218)(tany123298 x, void* y);
N_NIMCALL(void, fieldsaux_126418)(void* p, tnimnode123207* n, TY126424** ret);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI, cmpignorestyle_127425)(NCSTRING a, NCSTRING b);
static N_INLINE(NIM_CHAR, tolower_127430)(NIM_CHAR c);
N_NIMCALL(tnimnode123207*, getfieldnode_127565)(void* p, tnimnode123207* n, NCSTRING name);
N_NIMCALL(void, HEX5BHEX5DHEX3D_127654)(tany123298 x, NimStringDesc* fieldname, tany123298 value);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(tany123298, HEX5BHEX5D_128242)(tany123298 x, NimStringDesc* fieldname);
N_NIMCALL(tany123298, HEX5BHEX5D_128658)(tany123298 x);
N_NIMCALL(void, HEX5BHEX5DHEX3D_128818)(tany123298 x, tany123298 y);
N_NIMCALL(NI, getint_129220)(tany123298 x);
N_NIMCALL(NI8, getint8_129414)(tany123298 x);
N_NIMCALL(NI16, getint16_129614)(tany123298 x);
N_NIMCALL(NI32, getint32_129814)(tany123298 x);
N_NIMCALL(NI64, getint64_130014)(tany123298 x);
N_NIMCALL(NI64, getbiggestint_130214)(tany123298 x);
N_NIMCALL(void, setbiggestint_130631)(tany123298 x, NI64 y);
N_NIMCALL(NI64, chckRange64)(NI64 i, NI64 a, NI64 b);
N_NIMCALL(NIM_CHAR, getchar_131024)(tany123298 x);
N_NIMCALL(NIM_BOOL, getbool_131214)(tany123298 x);
N_NIMCALL(tany123298, skiprange_131414)(tany123298 x);
N_NIMCALL(NI, getenumordinal_131612)(tany123298 x, NimStringDesc* name);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, getenumfield_131846)(tany123298 x, NI ordinalvalue);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, getenumfield_132053)(tany123298 x);
N_NIMCALL(NF, getfloat_132060)(tany123298 x);
N_NIMCALL(NF32, getfloat32_132214)(tany123298 x);
N_NIMCALL(NF, getfloat64_132414)(tany123298 x);
N_NIMCALL(NF, getbiggestfloat_132614)(tany123298 x);
N_NIMCALL(void, setbiggestfloat_132809)(tany123298 x, NF y);
N_NIMCALL(NimStringDesc*, getstring_133007)(tany123298 x);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, setstring_133216)(tany123298 x, NimStringDesc* y);
N_NIMCALL(NCSTRING, getcstring_133414)(tany123298 x);
N_NIMCALL(void, assign_133614)(tany123298 x, tany123298 y);
N_NIMCALL(void, inclsetelement_134060)(tany123298 x, NI elem);
STRING_LITERAL(TMP303, "n.kind == nkCase ", 17);
STRING_LITERAL(TMP304, "false ", 6);
STRING_LITERAL(TMP305, "x.rawType.kind == tyRef ", 24);
STRING_LITERAL(TMP306, "x.rawType.kind == tySequence ", 29);
STRING_LITERAL(TMP307, "x.rawType.kind == tyObject ", 27);
STRING_LITERAL(TMP309, "index out of bounds", 19);
STRING_LITERAL(TMP312, "sequence is nil", 15);
STRING_LITERAL(TMP317, "y.rawType == x.rawType.base ", 28);
STRING_LITERAL(TMP324, "x.rawType.kind in\015\012    {tyString, tyCString, tyRef, tyPtr, tyPo"
"inter, tySequence, tyProc} ", 90);
STRING_LITERAL(TMP327, "ret[ret.len() - 1][0] != nil ", 29);
STRING_LITERAL(TMP333, "x.rawType.kind in {tyTuple, tyObject} ", 38);
STRING_LITERAL(TMP334, "n.typ == value.rawType ", 23);
STRING_LITERAL(TMP336, "invalid field name: ", 20);
STRING_LITERAL(TMP338, "x.rawtype.kind in {tyRef, tyPtr} ", 33);
STRING_LITERAL(TMP339, "skipRange(x.rawtype).kind == tyInt ", 35);
STRING_LITERAL(TMP340, "skipRange(x.rawtype).kind == tyInt8 ", 36);
STRING_LITERAL(TMP341, "skipRange(x.rawtype).kind == tyInt16 ", 37);
STRING_LITERAL(TMP342, "skipRange(x.rawtype).kind == tyInt32 ", 37);
STRING_LITERAL(TMP343, "skipRange(x.rawtype).kind == tyInt64 ", 37);
STRING_LITERAL(TMP344, "t.kind == tyChar ", 17);
STRING_LITERAL(TMP345, "t.kind == tyBool ", 17);
STRING_LITERAL(TMP346, "x.rawType.kind == tyRange ", 26);
STRING_LITERAL(TMP347, "typ.kind == tyEnum ", 19);
STRING_LITERAL(TMP350, "skipRange(x.rawtype).kind == tyFloat ", 37);
STRING_LITERAL(TMP351, "skipRange(x.rawtype).kind == tyFloat32 ", 39);
STRING_LITERAL(TMP352, "skipRange(x.rawtype).kind == tyFloat64 ", 39);
STRING_LITERAL(TMP353, "x.rawtype.kind == tyString ", 27);
STRING_LITERAL(TMP354, "x.rawtype.kind == tyCString ", 28);
STRING_LITERAL(TMP355, "y.rawType == x.rawType ", 23);
STRING_LITERAL(TMP356, "x.rawType.kind == tySet ", 24);
extern TFrame* frameptr_13038;
extern TNimType NTI17201; /* ref EInvalidIndex */
extern TNimType NTI2459; /* EInvalidIndex */
extern tgcheap43016 gch_43044;
extern TNimType NTI18001; /* ref EInvalidValue */
extern TNimType NTI2453; /* EInvalidValue */

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

N_NIMCALL(NI, getdiscriminant_123406)(void* aa, tnimnode123207* n) {
	NI result;
	NI d;
	NI a;
	nimfr("getDiscriminant", "typeinfo.nim")
	result = 0;
	nimln(82, "typeinfo.nim");
	{
		nimln(82, "typeinfo.nim");
		nimln(82, "typeinfo.nim");
		if (!!(((*n).Kind == ((NU8) 3)))) goto LA3;
		nimln(82, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP303));
	}
	LA3: ;
	d = 0;
	nimln(84, "typeinfo.nim");
	a = ((NI) (aa));
	nimln(85, "typeinfo.nim");
	switch ((*(*n).Typ).Size) {
	case 1:
	{
		nimln(86, "typeinfo.nim");
		nimln(86, "typeinfo.nim");
		nimln(86, "typeinfo.nim");
		d = ((NI)(NU)(NU8)((*((NI8*) ((NI)((NU64)(a) + (NU64)((*n).Offset)))))));
	}
	break;
	case 2:
	{
		nimln(87, "typeinfo.nim");
		nimln(87, "typeinfo.nim");
		nimln(87, "typeinfo.nim");
		d = ((NI)(NU)(NU16)((*((NI16*) ((NI)((NU64)(a) + (NU64)((*n).Offset)))))));
	}
	break;
	case 4:
	{
		nimln(88, "typeinfo.nim");
		nimln(88, "typeinfo.nim");
		d = ((NI) ((*((NI32*) ((NI)((NU64)(a) + (NU64)((*n).Offset)))))));
	}
	break;
	default:
	{
		nimln(89, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA11;
			nimln(89, "typeinfo.nim");
			failedassertimpl_81021(((NimStringDesc*) &TMP304));
		}
		LA11: ;
	}
	break;
	}
	nimln(90, "typeinfo.nim");
	nimln(90, "typeinfo.nim");
	result = d;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(tnimnode123207*, selectbranch_123809)(void* aa, tnimnode123207* n) {
	tnimnode123207* result;
	NI discr;
	nimfr("selectBranch", "typeinfo.nim")
	result = 0;
	nimln(93, "typeinfo.nim");
	discr = getdiscriminant_123406(aa, n);
	nimln(94, "typeinfo.nim");
	{
		nimln(94, "typeinfo.nim");
		if (!((NU64)(discr) < (NU64)((*n).Len))) goto LA3;
		nimln(95, "typeinfo.nim");
		if ((NU)(discr) > (NU)(32767)) raiseIndexError();
		result = (*n).Sons[(discr)- 0];
		nimln(96, "typeinfo.nim");
		{
			nimln(96, "typeinfo.nim");
			if (!(result == NIM_NIL)) goto LA7;
			nimln(96, "typeinfo.nim");
			if ((NU)((*n).Len) > (NU)(32767)) raiseIndexError();
			result = (*n).Sons[((*n).Len)- 0];
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		nimln(99, "typeinfo.nim");
		if ((NU)((*n).Len) > (NU)(32767)) raiseIndexError();
		result = (*n).Sons[((*n).Len)- 0];
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(tany123298, newany_123845)(void* value, tnimtype123211* rawtype) {
	tany123298 result;
	nimfr("newAny", "typeinfo.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(102, "typeinfo.nim");
	result.Value = value;
	nimln(103, "typeinfo.nim");
	result.Rawtype = rawtype;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

static N_INLINE(NU8, kind_124010)(tany123298 x) {
	NU8 result;
	nimfr("kind", "typeinfo.nim")
	result = 0;
	nimln(124, "typeinfo.nim");
	nimln(124, "typeinfo.nim");
	result = ((NU8)chckRange((*x.Rawtype).Kind, ((NU8) 0), ((NU8) 44)));
	popFrame();
	return result;
}

static N_INLINE(NI, size_124024)(tany123298 x) {
	NI result;
	nimfr("size", "typeinfo.nim")
	result = 0;
	nimln(128, "typeinfo.nim");
	result = (*x.Rawtype).Size;
	popFrame();
	return result;
}

static N_INLINE(NU8, basetypekind_124030)(tany123298 x) {
	NU8 result;
	nimfr("baseTypeKind", "typeinfo.nim")
	result = 0;
	nimln(132, "typeinfo.nim");
	{
		nimln(132, "typeinfo.nim");
		nimln(132, "typeinfo.nim");
		if (!!(((*x.Rawtype).Base == NIM_NIL))) goto LA3;
		nimln(133, "typeinfo.nim");
		nimln(133, "typeinfo.nim");
		result = ((NU8)chckRange((*(*x.Rawtype).Base).Kind, ((NU8) 0), ((NU8) 44)));
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(NI, basetypesize_124061)(tany123298 x) {
	NI result;
	nimfr("baseTypeSize", "typeinfo.nim")
	result = 0;
	nimln(137, "typeinfo.nim");
	{
		nimln(137, "typeinfo.nim");
		nimln(137, "typeinfo.nim");
		if (!!(((*x.Rawtype).Base == NIM_NIL))) goto LA3;
		nimln(138, "typeinfo.nim");
		result = (*(*x.Rawtype).Base).Size;
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void, invokenew_124084)(tany123298 x) {
	void* z;
	nimfr("invokeNew", "typeinfo.nim")
	nimln(142, "typeinfo.nim");
	{
		nimln(142, "typeinfo.nim");
		nimln(142, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 22)))) goto LA3;
		nimln(142, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP305));
	}
	LA3: ;
	nimln(143, "typeinfo.nim");
	z = newObj(x.Rawtype, (*(*x.Rawtype).Base).Size);
	nimln(144, "typeinfo.nim");
	genericAssign(x.Value, ((void*) (&z)), x.Rawtype);
	popFrame();
}

N_NIMCALL(void, invokenewseq_124214)(tany123298 x, NI len) {
	void* z;
	nimfr("invokeNewSeq", "typeinfo.nim")
	nimln(148, "typeinfo.nim");
	{
		nimln(148, "typeinfo.nim");
		nimln(148, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 24)))) goto LA3;
		nimln(148, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP306));
	}
	LA3: ;
	nimln(149, "typeinfo.nim");
	z = newSeq(x.Rawtype, len);
	nimln(150, "typeinfo.nim");
	genericShallowAssign(x.Value, ((void*) (&z)), x.Rawtype);
	popFrame();
}

N_NIMCALL(void, extendseq_124414)(tany123298 x) {
	tgenseq123304* y;
	tgenseq123304* z;
	nimfr("extendSeq", "typeinfo.nim")
	nimln(154, "typeinfo.nim");
	{
		nimln(154, "typeinfo.nim");
		nimln(154, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 24)))) goto LA3;
		nimln(154, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP306));
	}
	LA3: ;
	nimln(155, "typeinfo.nim");
	y = (*((tgenseq123304**) (x.Value)));
	nimln(156, "typeinfo.nim");
	z = incrSeq(y, (*(*x.Rawtype).Base).Size);
	nimln(159, "typeinfo.nim");
	(*((void**) (x.Value))) = ((void*) (z));
	popFrame();
}

N_NIMCALL(void, setobjectruntimetype_124617)(tany123298 x) {
	nimfr("setObjectRuntimeType", "typeinfo.nim")
	nimln(164, "typeinfo.nim");
	{
		nimln(164, "typeinfo.nim");
		nimln(164, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 17)))) goto LA3;
		nimln(164, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP307));
	}
	LA3: ;
	nimln(165, "typeinfo.nim");
	objectInit(x.Value, x.Rawtype);
	popFrame();
}

static N_INLINE(tnimtype123211*, skiprange_124812)(tnimtype123211* x) {
	tnimtype123211* result;
	nimfr("skipRange", "typeinfo.nim")
	result = 0;
	nimln(168, "typeinfo.nim");
	result = x;
	nimln(169, "typeinfo.nim");
	{
		nimln(169, "typeinfo.nim");
		if (!((*result).Kind == ((NU8) 20))) goto LA3;
		nimln(169, "typeinfo.nim");
		result = (*result).Base;
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI64)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(tcell41088*, usrtocell_44443)(void* usr) {
	tcell41088* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell41088*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell41088))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_46002)(tcell41088* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_44418(&gch_43044.Zct, c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell41088* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_44443(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_46002(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(tany123298, HEX5BHEX5D_124827)(tany123298 x, NI i) {
	tany123298 result;
	nimfr("[]", "typeinfo.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(173, "typeinfo.nim");
	switch ((*x.Rawtype).Kind) {
	case ((NU8) 16):
	{
		NI bs;
		NI TMP310;
		NI TMP311;
		nimln(175, "typeinfo.nim");
		bs = (*(*x.Rawtype).Base).Size;
		nimln(176, "typeinfo.nim");
		{
			NI TMP308;
			einvalidindex2459* e_124844;
			NimStringDesc* LOC6;
			nimln(176, "typeinfo.nim");
			nimln(176, "typeinfo.nim");
			TMP308 = divInt((*x.Rawtype).Size, bs);
			if (!((NU64)((NI64)(TMP308)) <= (NU64)(i))) goto LA4;
			e_124844 = 0;
			nimln(1991, "system.nim");
			e_124844 = (einvalidindex2459*) newObj((&NTI17201), sizeof(einvalidindex2459));
			(*e_124844).Sup.Sup.Sup.m_type = (&NTI2459);
			nimln(1992, "system.nim");
			LOC6 = 0;
			LOC6 = (*e_124844).Sup.Sup.message; (*e_124844).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP309));
			if (LOC6) nimGCunrefNoCycle(LOC6);
			nimln(177, "typeinfo.nim");
			raiseException((E_Base*)e_124844, "EInvalidIndex");
		}
		LA4: ;
		nimln(178, "typeinfo.nim");
		nimln(178, "typeinfo.nim");
		nimln(178, "typeinfo.nim");
		nimln(178, "typeinfo.nim");
		TMP310 = mulInt(i, bs);
		TMP311 = addInt(((NI) (x.Value)), (NI64)(TMP310));
		result = newany_123845(((void*) ((NI64)(TMP311))), (*x.Rawtype).Base);
		goto BeforeRet;
	}
	break;
	case ((NU8) 24):
	{
		void* s;
		NI bs;
		NI TMP313;
		NI TMP314;
		NI TMP315;
		nimln(180, "typeinfo.nim");
		s = (*((void**) (x.Value)));
		nimln(181, "typeinfo.nim");
		{
			einvalidvalue2453* e_124865;
			NimStringDesc* LOC12;
			nimln(181, "typeinfo.nim");
			if (!(s == NIM_NIL)) goto LA10;
			e_124865 = 0;
			nimln(1991, "system.nim");
			e_124865 = (einvalidvalue2453*) newObj((&NTI18001), sizeof(einvalidvalue2453));
			(*e_124865).Sup.Sup.Sup.m_type = (&NTI2453);
			nimln(1992, "system.nim");
			LOC12 = 0;
			LOC12 = (*e_124865).Sup.Sup.message; (*e_124865).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP312));
			if (LOC12) nimGCunrefNoCycle(LOC12);
			nimln(181, "typeinfo.nim");
			raiseException((E_Base*)e_124865, "EInvalidValue");
		}
		LA10: ;
		nimln(182, "typeinfo.nim");
		bs = (*(*x.Rawtype).Base).Size;
		nimln(183, "typeinfo.nim");
		{
			einvalidindex2459* e_124895;
			NimStringDesc* LOC17;
			nimln(183, "typeinfo.nim");
			if (!((NU64)((*((tgenseq123304*) (s))).Len) <= (NU64)(i))) goto LA15;
			e_124895 = 0;
			nimln(1991, "system.nim");
			e_124895 = (einvalidindex2459*) newObj((&NTI17201), sizeof(einvalidindex2459));
			(*e_124895).Sup.Sup.Sup.m_type = (&NTI2459);
			nimln(1992, "system.nim");
			LOC17 = 0;
			LOC17 = (*e_124895).Sup.Sup.message; (*e_124895).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP309));
			if (LOC17) nimGCunrefNoCycle(LOC17);
			nimln(184, "typeinfo.nim");
			raiseException((E_Base*)e_124895, "EInvalidIndex");
		}
		LA15: ;
		nimln(185, "typeinfo.nim");
		nimln(185, "typeinfo.nim");
		nimln(185, "typeinfo.nim");
		nimln(185, "typeinfo.nim");
		nimln(185, "typeinfo.nim");
		TMP313 = mulInt(i, bs);
		TMP314 = addInt(16, (NI64)(TMP313));
		TMP315 = addInt(((NI) (s)), (NI64)(TMP314));
		result = newany_123845(((void*) ((NI64)(TMP315))), (*x.Rawtype).Base);
		goto BeforeRet;
	}
	break;
	default:
	{
		nimln(186, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA21;
			nimln(186, "typeinfo.nim");
			failedassertimpl_81021(((NimStringDesc*) &TMP304));
		}
		LA21: ;
	}
	break;
	}
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_125012)(tany123298 x, NI i, tany123298 y) {
	nimfr("[]=", "typeinfo.nim")
	nimln(190, "typeinfo.nim");
	switch ((*x.Rawtype).Kind) {
	case ((NU8) 16):
	{
		NI bs;
		NI TMP318;
		NI TMP319;
		nimln(192, "typeinfo.nim");
		bs = (*(*x.Rawtype).Base).Size;
		nimln(193, "typeinfo.nim");
		{
			NI TMP316;
			einvalidindex2459* e_125029;
			NimStringDesc* LOC6;
			nimln(193, "typeinfo.nim");
			nimln(193, "typeinfo.nim");
			TMP316 = divInt((*x.Rawtype).Size, bs);
			if (!((NU64)((NI64)(TMP316)) <= (NU64)(i))) goto LA4;
			e_125029 = 0;
			nimln(1991, "system.nim");
			e_125029 = (einvalidindex2459*) newObj((&NTI17201), sizeof(einvalidindex2459));
			(*e_125029).Sup.Sup.Sup.m_type = (&NTI2459);
			nimln(1992, "system.nim");
			LOC6 = 0;
			LOC6 = (*e_125029).Sup.Sup.message; (*e_125029).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP309));
			if (LOC6) nimGCunrefNoCycle(LOC6);
			nimln(194, "typeinfo.nim");
			raiseException((E_Base*)e_125029, "EInvalidIndex");
		}
		LA4: ;
		nimln(195, "typeinfo.nim");
		{
			nimln(195, "typeinfo.nim");
			nimln(195, "typeinfo.nim");
			if (!!((y.Rawtype == (*x.Rawtype).Base))) goto LA9;
			nimln(195, "typeinfo.nim");
			failedassertimpl_81021(((NimStringDesc*) &TMP317));
		}
		LA9: ;
		nimln(196, "typeinfo.nim");
		nimln(196, "typeinfo.nim");
		nimln(196, "typeinfo.nim");
		TMP318 = mulInt(i, bs);
		TMP319 = addInt(((NI) (x.Value)), (NI64)(TMP318));
		genericAssign(((void*) ((NI64)(TMP319))), y.Value, y.Rawtype);
	}
	break;
	case ((NU8) 24):
	{
		void* s;
		NI bs;
		NI TMP320;
		NI TMP321;
		NI TMP322;
		nimln(198, "typeinfo.nim");
		s = (*((void**) (x.Value)));
		nimln(199, "typeinfo.nim");
		{
			einvalidvalue2453* e_125220;
			NimStringDesc* LOC16;
			nimln(199, "typeinfo.nim");
			if (!(s == NIM_NIL)) goto LA14;
			e_125220 = 0;
			nimln(1991, "system.nim");
			e_125220 = (einvalidvalue2453*) newObj((&NTI18001), sizeof(einvalidvalue2453));
			(*e_125220).Sup.Sup.Sup.m_type = (&NTI2453);
			nimln(1992, "system.nim");
			LOC16 = 0;
			LOC16 = (*e_125220).Sup.Sup.message; (*e_125220).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP312));
			if (LOC16) nimGCunrefNoCycle(LOC16);
			nimln(199, "typeinfo.nim");
			raiseException((E_Base*)e_125220, "EInvalidValue");
		}
		LA14: ;
		nimln(200, "typeinfo.nim");
		bs = (*(*x.Rawtype).Base).Size;
		nimln(201, "typeinfo.nim");
		{
			einvalidindex2459* e_125250;
			NimStringDesc* LOC21;
			nimln(201, "typeinfo.nim");
			if (!((NU64)((*((tgenseq123304*) (s))).Len) <= (NU64)(i))) goto LA19;
			e_125250 = 0;
			nimln(1991, "system.nim");
			e_125250 = (einvalidindex2459*) newObj((&NTI17201), sizeof(einvalidindex2459));
			(*e_125250).Sup.Sup.Sup.m_type = (&NTI2459);
			nimln(1992, "system.nim");
			LOC21 = 0;
			LOC21 = (*e_125250).Sup.Sup.message; (*e_125250).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP309));
			if (LOC21) nimGCunrefNoCycle(LOC21);
			nimln(202, "typeinfo.nim");
			raiseException((E_Base*)e_125250, "EInvalidIndex");
		}
		LA19: ;
		nimln(203, "typeinfo.nim");
		{
			nimln(203, "typeinfo.nim");
			nimln(203, "typeinfo.nim");
			if (!!((y.Rawtype == (*x.Rawtype).Base))) goto LA24;
			nimln(203, "typeinfo.nim");
			failedassertimpl_81021(((NimStringDesc*) &TMP317));
		}
		LA24: ;
		nimln(204, "typeinfo.nim");
		nimln(204, "typeinfo.nim");
		nimln(204, "typeinfo.nim");
		nimln(204, "typeinfo.nim");
		TMP320 = mulInt(i, bs);
		TMP321 = addInt(16, (NI64)(TMP320));
		TMP322 = addInt(((NI) (s)), (NI64)(TMP321));
		genericAssign(((void*) ((NI64)(TMP322))), y.Value, y.Rawtype);
	}
	break;
	default:
	{
		nimln(205, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA29;
			nimln(205, "typeinfo.nim");
			failedassertimpl_81021(((NimStringDesc*) &TMP304));
		}
		LA29: ;
	}
	break;
	}
	popFrame();
}

N_NIMCALL(NI, len_125612)(tany123298 x) {
	NI result;
	nimfr("len", "typeinfo.nim")
	result = 0;
	nimln(209, "typeinfo.nim");
	switch ((*x.Rawtype).Kind) {
	case ((NU8) 16):
	{
		NI TMP323;
		nimln(210, "typeinfo.nim");
		nimln(210, "typeinfo.nim");
		TMP323 = divInt((*x.Rawtype).Size, (*(*x.Rawtype).Base).Size);
		result = (NI64)(TMP323);
	}
	break;
	case ((NU8) 24):
	{
		nimln(211, "typeinfo.nim");
		result = (*((tgenseq123304*) ((*((void**) (x.Value)))))).Len;
	}
	break;
	default:
	{
		nimln(212, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA6;
			nimln(212, "typeinfo.nim");
			failedassertimpl_81021(((NimStringDesc*) &TMP304));
		}
		LA6: ;
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(tany123298, base_125805)(tany123298 x) {
	tany123298 result;
	nimfr("base", "typeinfo.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(217, "typeinfo.nim");
	result.Rawtype = (*x.Rawtype).Base;
	nimln(218, "typeinfo.nim");
	result.Value = x.Value;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isnil_125811)(tany123298 x) {
	NIM_BOOL result;
	nimfr("isNil", "typeinfo.nim")
	result = 0;
	nimln(224, "typeinfo.nim");
	{
		nimln(224, "typeinfo.nim");
		nimln(224, "typeinfo.nim");
		if (!!(((929038336 &(IL64(1)<<(((*x.Rawtype).Kind)&IL64(63))))!=0))) goto LA3;
		nimln(224, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP324));
	}
	LA3: ;
	nimln(226, "typeinfo.nim");
	nimln(226, "typeinfo.nim");
	result = (*((void**) (x.Value))) == 0;
	popFrame();
	return result;
}

N_NIMCALL(void*, getpointer_126018)(tany123298 x) {
	void* result;
	nimfr("getPointer", "typeinfo.nim")
	result = 0;
	nimln(232, "typeinfo.nim");
	{
		nimln(232, "typeinfo.nim");
		nimln(232, "typeinfo.nim");
		if (!!(((929038336 &(IL64(1)<<(((*x.Rawtype).Kind)&IL64(63))))!=0))) goto LA3;
		nimln(232, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP324));
	}
	LA3: ;
	nimln(234, "typeinfo.nim");
	result = (*((void**) (x.Value)));
	popFrame();
	return result;
}

N_NIMCALL(void, setpointer_126218)(tany123298 x, void* y) {
	nimfr("setPointer", "typeinfo.nim")
	nimln(240, "typeinfo.nim");
	{
		nimln(240, "typeinfo.nim");
		nimln(240, "typeinfo.nim");
		if (!!(((929038336 &(IL64(1)<<(((*x.Rawtype).Kind)&IL64(63))))!=0))) goto LA3;
		nimln(240, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP324));
	}
	LA3: ;
	nimln(242, "typeinfo.nim");
	(*((void**) (x.Value))) = y;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, fieldsaux_126418)(void* p, tnimnode123207* n, TY126424** ret) {
	nimfr("fieldsAux", "typeinfo.nim")
	nimln(246, "typeinfo.nim");
	switch ((*n).Kind) {
	case ((NU8) 0):
	{
		nimln(247, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA4;
			nimln(247, "typeinfo.nim");
			failedassertimpl_81021(((NimStringDesc*) &TMP304));
		}
		LA4: ;
	}
	break;
	case ((NU8) 1):
	{
		TY126603 LOC7;
		NI TMP325;
		nimln(249, "typeinfo.nim");
		LOC7.Field0 = (*n).Name;
		nimln(249, "typeinfo.nim");
		nimln(249, "typeinfo.nim");
		TMP325 = addInt(((NI) (p)), (*n).Offset);
		LOC7.Field1 = newany_123845(((void*) ((NI64)(TMP325))), (*n).Typ);
		(*ret) = (TY126424*) incrSeq(&((*ret))->Sup, sizeof(TY126603));
		(*ret)->data[(*ret)->Sup.len-1] = LOC7;
		nimln(250, "typeinfo.nim");
		{
			NI TMP326;
			nimln(250, "typeinfo.nim");
			nimln(250, "typeinfo.nim");
			nimln(250, "typeinfo.nim");
			nimln(250, "typeinfo.nim");
			nimln(250, "typeinfo.nim");
			TMP326 = subInt((*ret)->Sup.len, 1);
			if ((NU)((NI64)(TMP326)) >= (NU)((*ret)->Sup.len)) raiseIndexError();
			if (!!(!(((*ret)->data[(NI64)(TMP326)].Field0 == NIM_NIL)))) goto LA10;
			nimln(250, "typeinfo.nim");
			failedassertimpl_81021(((NimStringDesc*) &TMP327));
		}
		LA10: ;
	}
	break;
	case ((NU8) 2):
	{
		NI i_126822;
		NI HEX3Atmp_126862;
		NI TMP328;
		NI res_126864;
		i_126822 = 0;
		HEX3Atmp_126862 = 0;
		nimln(252, "typeinfo.nim");
		nimln(252, "typeinfo.nim");
		TMP328 = subInt((*n).Len, 1);
		HEX3Atmp_126862 = (NI64)(TMP328);
		nimln(1457, "system.nim");
		res_126864 = 0;
		nimln(1458, "system.nim");
		while (1) {
			nimln(1458, "system.nim");
			if (!(res_126864 <= HEX3Atmp_126862)) goto LA13;
			nimln(1457, "system.nim");
			i_126822 = res_126864;
			nimln(252, "typeinfo.nim");
			if ((NU)(i_126822) > (NU)(32767)) raiseIndexError();
			fieldsaux_126418(p, (*n).Sons[(i_126822)- 0], ret);
			nimln(1460, "system.nim");
			res_126864 = addInt(res_126864, 1);
		} LA13: ;
	}
	break;
	case ((NU8) 3):
	{
		tnimnode123207* m;
		TY126603 LOC15;
		NI TMP329;
		nimln(254, "typeinfo.nim");
		m = selectbranch_123809(p, n);
		nimln(255, "typeinfo.nim");
		LOC15.Field0 = (*n).Name;
		nimln(255, "typeinfo.nim");
		nimln(255, "typeinfo.nim");
		TMP329 = addInt(((NI) (p)), (*n).Offset);
		LOC15.Field1 = newany_123845(((void*) ((NI64)(TMP329))), (*n).Typ);
		(*ret) = (TY126424*) incrSeq(&((*ret))->Sup, sizeof(TY126603));
		(*ret)->data[(*ret)->Sup.len-1] = LOC15;
		nimln(256, "typeinfo.nim");
		{
			nimln(256, "typeinfo.nim");
			nimln(256, "typeinfo.nim");
			if (!!((m == NIM_NIL))) goto LA18;
			nimln(256, "typeinfo.nim");
			fieldsaux_126418(p, m, ret);
		}
		LA18: ;
	}
	break;
	}
	popFrame();
}

static N_INLINE(NIM_CHAR, tolower_127430)(NIM_CHAR c) {
	NIM_CHAR result;
	nimfr("toLower", "typeinfo.nim")
	result = 0;
	nimln(275, "typeinfo.nim");
	{
		NI TMP330;
		nimln(275, "typeinfo.nim");
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3;
		nimln(275, "typeinfo.nim");
		nimln(275, "typeinfo.nim");
		nimln(275, "typeinfo.nim");
		nimln(275, "typeinfo.nim");
		TMP330 = addInt(((NI) (((NU8)(c)))), 32);
		result = ((NIM_CHAR) (((NI)chckRange((NI64)(TMP330), 0, 255))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(276, "typeinfo.nim");
		result = c;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, cmpignorestyle_127425)(NCSTRING a, NCSTRING b) {
	NI result;
	NI i;
	NI j;
	nimfr("cmpIgnoreStyle", "typeinfo.nim")
	result = 0;
	nimln(277, "typeinfo.nim");
	i = 0;
	nimln(278, "typeinfo.nim");
	j = 0;
	nimln(279, "typeinfo.nim");
	while (1) {
		NIM_CHAR aa;
		NIM_CHAR bb;
		NI TMP331;
		nimln(280, "typeinfo.nim");
		while (1) {
			nimln(280, "typeinfo.nim");
			if (!((NU8)(a[i]) == (NU8)(95))) goto LA2;
			nimln(280, "typeinfo.nim");
			i = addInt(i, 1);
		} LA2: ;
		nimln(281, "typeinfo.nim");
		while (1) {
			nimln(281, "typeinfo.nim");
			if (!((NU8)(b[j]) == (NU8)(95))) goto LA3;
			nimln(281, "typeinfo.nim");
			j = addInt(j, 1);
		} LA3: ;
		nimln(282, "typeinfo.nim");
		aa = tolower_127430(a[i]);
		nimln(283, "typeinfo.nim");
		bb = tolower_127430(b[j]);
		nimln(284, "typeinfo.nim");
		nimln(284, "typeinfo.nim");
		nimln(284, "typeinfo.nim");
		nimln(284, "typeinfo.nim");
		TMP331 = subInt(((NI) (((NU8)(aa)))), ((NI) (((NU8)(bb)))));
		result = (NI64)(TMP331);
		nimln(285, "typeinfo.nim");
		{
			NIM_BOOL LOC6;
			nimln(285, "typeinfo.nim");
			LOC6 = 0;
			nimln(285, "typeinfo.nim");
			nimln(285, "typeinfo.nim");
			LOC6 = !((result == 0));
			if (LOC6) goto LA7;
			nimln(285, "typeinfo.nim");
			LOC6 = ((NU8)(aa) == (NU8)(0));
			LA7: ;
			if (!LOC6) goto LA8;
			nimln(285, "typeinfo.nim");
			goto LA1;
		}
		LA8: ;
		nimln(286, "typeinfo.nim");
		i = addInt(i, 1);
		nimln(287, "typeinfo.nim");
		j = addInt(j, 1);
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(tnimnode123207*, getfieldnode_127565)(void* p, tnimnode123207* n, NCSTRING name) {
	tnimnode123207* result;
	nimfr("getFieldNode", "typeinfo.nim")
	result = 0;
	nimln(291, "typeinfo.nim");
	switch ((*n).Kind) {
	case ((NU8) 0):
	{
		nimln(292, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA4;
			nimln(292, "typeinfo.nim");
			failedassertimpl_81021(((NimStringDesc*) &TMP304));
		}
		LA4: ;
	}
	break;
	case ((NU8) 1):
	{
		nimln(294, "typeinfo.nim");
		{
			NI LOC9;
			nimln(294, "typeinfo.nim");
			nimln(294, "typeinfo.nim");
			LOC9 = 0;
			LOC9 = cmpignorestyle_127425((*n).Name, name);
			if (!(LOC9 == 0)) goto LA10;
			nimln(295, "typeinfo.nim");
			result = n;
		}
		LA10: ;
	}
	break;
	case ((NU8) 2):
	{
		NI i_127611;
		NI HEX3Atmp_127647;
		NI TMP332;
		NI res_127649;
		i_127611 = 0;
		HEX3Atmp_127647 = 0;
		nimln(297, "typeinfo.nim");
		nimln(297, "typeinfo.nim");
		TMP332 = subInt((*n).Len, 1);
		HEX3Atmp_127647 = (NI64)(TMP332);
		nimln(1457, "system.nim");
		res_127649 = 0;
		nimln(1458, "system.nim");
		while (1) {
			nimln(1458, "system.nim");
			if (!(res_127649 <= HEX3Atmp_127647)) goto LA13;
			nimln(1457, "system.nim");
			i_127611 = res_127649;
			nimln(298, "typeinfo.nim");
			if ((NU)(i_127611) > (NU)(32767)) raiseIndexError();
			result = getfieldnode_127565(p, (*n).Sons[(i_127611)- 0], name);
			nimln(299, "typeinfo.nim");
			{
				nimln(299, "typeinfo.nim");
				nimln(299, "typeinfo.nim");
				if (!!((result == NIM_NIL))) goto LA16;
				nimln(299, "typeinfo.nim");
				goto LA13;
			}
			LA16: ;
			nimln(1460, "system.nim");
			res_127649 = addInt(res_127649, 1);
		} LA13: ;
	}
	break;
	case ((NU8) 3):
	{
		nimln(301, "typeinfo.nim");
		{
			NI LOC21;
			nimln(301, "typeinfo.nim");
			nimln(301, "typeinfo.nim");
			LOC21 = 0;
			LOC21 = cmpignorestyle_127425((*n).Name, name);
			if (!(LOC21 == 0)) goto LA22;
			nimln(302, "typeinfo.nim");
			result = n;
		}
		goto LA19;
		LA22: ;
		{
			tnimnode123207* m;
			nimln(304, "typeinfo.nim");
			m = selectbranch_123809(p, n);
			nimln(305, "typeinfo.nim");
			{
				nimln(305, "typeinfo.nim");
				nimln(305, "typeinfo.nim");
				if (!!((m == NIM_NIL))) goto LA27;
				nimln(305, "typeinfo.nim");
				result = getfieldnode_127565(p, m, name);
			}
			LA27: ;
		}
		LA19: ;
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell41088* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_44443(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell41088* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_44443((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_46002(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_127654)(tany123298 x, NimStringDesc* fieldname, tany123298 value) {
	tnimtype123211* t;
	tnimnode123207* n;
	nimfr("[]=", "typeinfo.nim")
	nimln(309, "typeinfo.nim");
	t = x.Rawtype;
	nimln(313, "typeinfo.nim");
	{
		nimln(313, "typeinfo.nim");
		nimln(313, "typeinfo.nim");
		if (!!(((393216 &(IL64(1)<<(((*x.Rawtype).Kind)&IL64(63))))!=0))) goto LA3;
		nimln(313, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP333));
	}
	LA3: ;
	nimln(314, "typeinfo.nim");
	n = getfieldnode_127565(x.Value, (*t).Node, fieldname->data);
	nimln(315, "typeinfo.nim");
	{
		NI TMP335;
		nimln(315, "typeinfo.nim");
		nimln(315, "typeinfo.nim");
		if (!!((n == NIM_NIL))) goto LA7;
		nimln(316, "typeinfo.nim");
		{
			nimln(316, "typeinfo.nim");
			nimln(316, "typeinfo.nim");
			if (!!(((*n).Typ == value.Rawtype))) goto LA11;
			nimln(316, "typeinfo.nim");
			failedassertimpl_81021(((NimStringDesc*) &TMP334));
		}
		LA11: ;
		nimln(317, "typeinfo.nim");
		nimln(317, "typeinfo.nim");
		TMP335 = addInt(((NI) (x.Value)), (*n).Offset);
		genericAssign(((void*) ((NI64)(TMP335))), value.Value, value.Rawtype);
	}
	goto LA5;
	LA7: ;
	{
		einvalidvalue2453* e_128219;
		NimStringDesc* LOC14;
		e_128219 = 0;
		nimln(1991, "system.nim");
		e_128219 = (einvalidvalue2453*) newObj((&NTI18001), sizeof(einvalidvalue2453));
		(*e_128219).Sup.Sup.Sup.m_type = (&NTI2453);
		nimln(1992, "system.nim");
		nimln(319, "typeinfo.nim");
		LOC14 = 0;
		LOC14 = rawNewString(fieldname->Sup.len + 20);
appendString(LOC14, ((NimStringDesc*) &TMP336));
appendString(LOC14, fieldname);
		asgnRefNoCycle((void**) &(*e_128219).Sup.Sup.message, LOC14);
		nimln(319, "typeinfo.nim");
		raiseException((E_Base*)e_128219, "EInvalidValue");
	}
	LA5: ;
	popFrame();
}

N_NIMCALL(tany123298, HEX5BHEX5D_128242)(tany123298 x, NimStringDesc* fieldname) {
	tany123298 result;
	tnimtype123211* t;
	tnimnode123207* n;
	nimfr("[]", "typeinfo.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(323, "typeinfo.nim");
	t = x.Rawtype;
	nimln(327, "typeinfo.nim");
	{
		nimln(327, "typeinfo.nim");
		nimln(327, "typeinfo.nim");
		if (!!(((393216 &(IL64(1)<<(((*x.Rawtype).Kind)&IL64(63))))!=0))) goto LA3;
		nimln(327, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP333));
	}
	LA3: ;
	nimln(328, "typeinfo.nim");
	n = getfieldnode_127565(x.Value, (*t).Node, fieldname->data);
	nimln(329, "typeinfo.nim");
	{
		NI TMP337;
		nimln(329, "typeinfo.nim");
		nimln(329, "typeinfo.nim");
		if (!!((n == NIM_NIL))) goto LA7;
		nimln(330, "typeinfo.nim");
		nimln(330, "typeinfo.nim");
		TMP337 = addInt(((NI) (x.Value)), (*n).Offset);
		result.Value = ((void*) ((NI64)(TMP337)));
		nimln(331, "typeinfo.nim");
		result.Rawtype = (*n).Typ;
	}
	goto LA5;
	LA7: ;
	{
		einvalidvalue2453* e_128635;
		NimStringDesc* LOC10;
		e_128635 = 0;
		nimln(1991, "system.nim");
		e_128635 = (einvalidvalue2453*) newObj((&NTI18001), sizeof(einvalidvalue2453));
		(*e_128635).Sup.Sup.Sup.m_type = (&NTI2453);
		nimln(1992, "system.nim");
		nimln(333, "typeinfo.nim");
		LOC10 = 0;
		LOC10 = rawNewString(fieldname->Sup.len + 20);
appendString(LOC10, ((NimStringDesc*) &TMP336));
appendString(LOC10, fieldname);
		asgnRefNoCycle((void**) &(*e_128635).Sup.Sup.message, LOC10);
		nimln(333, "typeinfo.nim");
		raiseException((E_Base*)e_128635, "EInvalidValue");
	}
	LA5: ;
	popFrame();
	return result;
}

N_NIMCALL(tany123298, HEX5BHEX5D_128658)(tany123298 x) {
	tany123298 result;
	nimfr("[]", "typeinfo.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(337, "typeinfo.nim");
	{
		nimln(337, "typeinfo.nim");
		nimln(337, "typeinfo.nim");
		if (!!(((6291456 &(IL64(1)<<(((*x.Rawtype).Kind)&IL64(63))))!=0))) goto LA3;
		nimln(337, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP338));
	}
	LA3: ;
	nimln(338, "typeinfo.nim");
	result.Value = (*((void**) (x.Value)));
	nimln(339, "typeinfo.nim");
	result.Rawtype = (*x.Rawtype).Base;
	popFrame();
	return result;
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_128818)(tany123298 x, tany123298 y) {
	nimfr("[]=", "typeinfo.nim")
	nimln(343, "typeinfo.nim");
	{
		nimln(343, "typeinfo.nim");
		nimln(343, "typeinfo.nim");
		if (!!(((6291456 &(IL64(1)<<(((*x.Rawtype).Kind)&IL64(63))))!=0))) goto LA3;
		nimln(343, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP338));
	}
	LA3: ;
	nimln(344, "typeinfo.nim");
	{
		nimln(344, "typeinfo.nim");
		nimln(344, "typeinfo.nim");
		if (!!((y.Rawtype == (*x.Rawtype).Base))) goto LA7;
		nimln(344, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP317));
	}
	LA7: ;
	nimln(345, "typeinfo.nim");
	genericAssign((*((void**) (x.Value))), y.Value, y.Rawtype);
	popFrame();
}

N_NIMCALL(NI, getint_129220)(tany123298 x) {
	NI result;
	nimfr("getInt", "typeinfo.nim")
	result = 0;
	nimln(349, "typeinfo.nim");
	{
		tnimtype123211* LOC3;
		nimln(349, "typeinfo.nim");
		nimln(349, "typeinfo.nim");
		nimln(349, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_124812(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 31)))) goto LA4;
		nimln(349, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP339));
	}
	LA4: ;
	nimln(350, "typeinfo.nim");
	result = (*((NI*) (x.Value)));
	popFrame();
	return result;
}

N_NIMCALL(NI8, getint8_129414)(tany123298 x) {
	NI8 result;
	nimfr("getInt8", "typeinfo.nim")
	result = 0;
	nimln(354, "typeinfo.nim");
	{
		tnimtype123211* LOC3;
		nimln(354, "typeinfo.nim");
		nimln(354, "typeinfo.nim");
		nimln(354, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_124812(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 32)))) goto LA4;
		nimln(354, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP340));
	}
	LA4: ;
	nimln(355, "typeinfo.nim");
	result = (*((NI8*) (x.Value)));
	popFrame();
	return result;
}

N_NIMCALL(NI16, getint16_129614)(tany123298 x) {
	NI16 result;
	nimfr("getInt16", "typeinfo.nim")
	result = 0;
	nimln(359, "typeinfo.nim");
	{
		tnimtype123211* LOC3;
		nimln(359, "typeinfo.nim");
		nimln(359, "typeinfo.nim");
		nimln(359, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_124812(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 33)))) goto LA4;
		nimln(359, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP341));
	}
	LA4: ;
	nimln(360, "typeinfo.nim");
	result = (*((NI16*) (x.Value)));
	popFrame();
	return result;
}

N_NIMCALL(NI32, getint32_129814)(tany123298 x) {
	NI32 result;
	nimfr("getInt32", "typeinfo.nim")
	result = 0;
	nimln(364, "typeinfo.nim");
	{
		tnimtype123211* LOC3;
		nimln(364, "typeinfo.nim");
		nimln(364, "typeinfo.nim");
		nimln(364, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_124812(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 34)))) goto LA4;
		nimln(364, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP342));
	}
	LA4: ;
	nimln(365, "typeinfo.nim");
	result = (*((NI32*) (x.Value)));
	popFrame();
	return result;
}

N_NIMCALL(NI64, getint64_130014)(tany123298 x) {
	NI64 result;
	nimfr("getInt64", "typeinfo.nim")
	result = 0;
	nimln(369, "typeinfo.nim");
	{
		tnimtype123211* LOC3;
		nimln(369, "typeinfo.nim");
		nimln(369, "typeinfo.nim");
		nimln(369, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_124812(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 35)))) goto LA4;
		nimln(369, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP343));
	}
	LA4: ;
	nimln(370, "typeinfo.nim");
	result = (*((NI64*) (x.Value)));
	popFrame();
	return result;
}

N_NIMCALL(NI64, getbiggestint_130214)(tany123298 x) {
	NI64 result;
	tnimtype123211* t;
	nimfr("getBiggestInt", "typeinfo.nim")
	result = 0;
	nimln(376, "typeinfo.nim");
	t = skiprange_124812(x.Rawtype);
	nimln(377, "typeinfo.nim");
	switch ((*t).Kind) {
	case ((NU8) 31):
	{
		nimln(378, "typeinfo.nim");
		result = ((NI64) ((*((NI*) (x.Value)))));
	}
	break;
	case ((NU8) 32):
	{
		nimln(379, "typeinfo.nim");
		result = ((NI64) ((*((NI8*) (x.Value)))));
	}
	break;
	case ((NU8) 33):
	{
		nimln(380, "typeinfo.nim");
		result = ((NI64) ((*((NI16*) (x.Value)))));
	}
	break;
	case ((NU8) 34):
	{
		nimln(381, "typeinfo.nim");
		result = ((NI64) ((*((NI32*) (x.Value)))));
	}
	break;
	case ((NU8) 35):
	case ((NU8) 44):
	{
		nimln(382, "typeinfo.nim");
		result = (*((NI64*) (x.Value)));
	}
	break;
	case ((NU8) 1):
	{
		nimln(383, "typeinfo.nim");
		result = ((NI64) ((*((NIM_BOOL*) (x.Value)))));
	}
	break;
	case ((NU8) 2):
	{
		nimln(384, "typeinfo.nim");
		result = ((NI64) (((NU8)((*((NIM_CHAR*) (x.Value)))))));
	}
	break;
	case ((NU8) 14):
	case ((NU8) 19):
	{
		nimln(386, "typeinfo.nim");
		switch ((*t).Size) {
		case 1:
		{
			nimln(387, "typeinfo.nim");
			nimln(387, "typeinfo.nim");
			result = ((NI64)(NU64)(NU8)((*((NI8*) (x.Value)))));
		}
		break;
		case 2:
		{
			nimln(388, "typeinfo.nim");
			nimln(388, "typeinfo.nim");
			result = ((NI64)(NU64)(NU16)((*((NI16*) (x.Value)))));
		}
		break;
		case 4:
		{
			nimln(389, "typeinfo.nim");
			result = ((NI64) ((*((NI32*) (x.Value)))));
		}
		break;
		case 8:
		{
			nimln(390, "typeinfo.nim");
			result = (*((NI64*) (x.Value)));
		}
		break;
		default:
		{
			nimln(391, "typeinfo.nim");
			{
				if (!NIM_TRUE) goto LA16;
				nimln(391, "typeinfo.nim");
				failedassertimpl_81021(((NimStringDesc*) &TMP304));
			}
			LA16: ;
		}
		break;
		}
	}
	break;
	case ((NU8) 40):
	{
		nimln(392, "typeinfo.nim");
		result = ((NI64) ((*((NU*) (x.Value)))));
	}
	break;
	case ((NU8) 41):
	{
		nimln(393, "typeinfo.nim");
		result = ((NI64) ((*((NU8*) (x.Value)))));
	}
	break;
	case ((NU8) 42):
	{
		nimln(394, "typeinfo.nim");
		result = ((NI64) ((*((NU16*) (x.Value)))));
	}
	break;
	case ((NU8) 43):
	{
		nimln(395, "typeinfo.nim");
		result = ((NI64) ((*((int*) (x.Value)))));
	}
	break;
	default:
	{
		nimln(396, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA25;
			nimln(396, "typeinfo.nim");
			failedassertimpl_81021(((NimStringDesc*) &TMP304));
		}
		LA25: ;
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(void, setbiggestint_130631)(tany123298 x, NI64 y) {
	tnimtype123211* t;
	nimfr("setBiggestInt", "typeinfo.nim")
	nimln(401, "typeinfo.nim");
	t = skiprange_124812(x.Rawtype);
	nimln(402, "typeinfo.nim");
	switch ((*t).Kind) {
	case ((NU8) 31):
	{
		nimln(403, "typeinfo.nim");
		(*((NI*) (x.Value))) = ((NI) (y));
	}
	break;
	case ((NU8) 32):
	{
		nimln(404, "typeinfo.nim");
		(*((NI8*) (x.Value))) = ((NI8)chckRange64(y, ((NI8) -128), ((NI8) 127)));
	}
	break;
	case ((NU8) 33):
	{
		nimln(405, "typeinfo.nim");
		(*((NI16*) (x.Value))) = ((NI16)chckRange64(y, ((NI16) -32768), ((NI16) 32767)));
	}
	break;
	case ((NU8) 34):
	{
		nimln(406, "typeinfo.nim");
		(*((NI32*) (x.Value))) = ((NI32)chckRange64(y, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
	}
	break;
	case ((NU8) 35):
	case ((NU8) 44):
	{
		nimln(407, "typeinfo.nim");
		(*((NI64*) (x.Value))) = y;
	}
	break;
	case ((NU8) 1):
	{
		nimln(408, "typeinfo.nim");
		nimln(408, "typeinfo.nim");
		nimln(408, "typeinfo.nim");
		(*((NIM_BOOL*) (x.Value))) = !((y == 0));
	}
	break;
	case ((NU8) 2):
	{
		nimln(409, "typeinfo.nim");
		nimln(409, "typeinfo.nim");
		(*((NIM_CHAR*) (x.Value))) = ((NIM_CHAR) (((NI)chckRange(((NI) (y)), 0, 255))));
	}
	break;
	case ((NU8) 14):
	case ((NU8) 19):
	{
		nimln(411, "typeinfo.nim");
		switch ((*t).Size) {
		case 1:
		{
			nimln(412, "typeinfo.nim");
			nimln(412, "typeinfo.nim");
			(*((NI8*) (x.Value))) = ((NI8)(NU8)(NU)(((NI) (y))));
		}
		break;
		case 2:
		{
			nimln(413, "typeinfo.nim");
			nimln(413, "typeinfo.nim");
			(*((NI16*) (x.Value))) = ((NI16)(NU16)(NU)(((NI) (y))));
		}
		break;
		case 4:
		{
			nimln(414, "typeinfo.nim");
			(*((NI32*) (x.Value))) = ((NI32)chckRange64(y, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
		}
		break;
		case 8:
		{
			nimln(415, "typeinfo.nim");
			(*((NI64*) (x.Value))) = y;
		}
		break;
		default:
		{
			nimln(416, "typeinfo.nim");
			{
				if (!NIM_TRUE) goto LA16;
				nimln(416, "typeinfo.nim");
				failedassertimpl_81021(((NimStringDesc*) &TMP304));
			}
			LA16: ;
		}
		break;
		}
	}
	break;
	case ((NU8) 40):
	{
		nimln(417, "typeinfo.nim");
		(*((NU*) (x.Value))) = ((NU) (y));
	}
	break;
	case ((NU8) 41):
	{
		nimln(418, "typeinfo.nim");
		(*((NU8*) (x.Value))) = ((NU8) (y));
	}
	break;
	case ((NU8) 42):
	{
		nimln(419, "typeinfo.nim");
		(*((NU16*) (x.Value))) = ((NU16) (y));
	}
	break;
	case ((NU8) 43):
	{
		nimln(420, "typeinfo.nim");
		(*((int*) (x.Value))) = ((NU32) (y));
	}
	break;
	default:
	{
		nimln(421, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA25;
			nimln(421, "typeinfo.nim");
			failedassertimpl_81021(((NimStringDesc*) &TMP304));
		}
		LA25: ;
	}
	break;
	}
	popFrame();
}

N_NIMCALL(NIM_CHAR, getchar_131024)(tany123298 x) {
	NIM_CHAR result;
	tnimtype123211* t;
	nimfr("getChar", "typeinfo.nim")
	result = 0;
	nimln(425, "typeinfo.nim");
	t = skiprange_124812(x.Rawtype);
	nimln(426, "typeinfo.nim");
	{
		nimln(426, "typeinfo.nim");
		nimln(426, "typeinfo.nim");
		if (!!(((*t).Kind == ((NU8) 2)))) goto LA3;
		nimln(426, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP344));
	}
	LA3: ;
	nimln(427, "typeinfo.nim");
	result = (*((NIM_CHAR*) (x.Value)));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, getbool_131214)(tany123298 x) {
	NIM_BOOL result;
	tnimtype123211* t;
	nimfr("getBool", "typeinfo.nim")
	result = 0;
	nimln(431, "typeinfo.nim");
	t = skiprange_124812(x.Rawtype);
	nimln(432, "typeinfo.nim");
	{
		nimln(432, "typeinfo.nim");
		nimln(432, "typeinfo.nim");
		if (!!(((*t).Kind == ((NU8) 1)))) goto LA3;
		nimln(432, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP345));
	}
	LA3: ;
	nimln(433, "typeinfo.nim");
	result = (*((NIM_BOOL*) (x.Value)));
	popFrame();
	return result;
}

N_NIMCALL(tany123298, skiprange_131414)(tany123298 x) {
	tany123298 result;
	nimfr("skipRange", "typeinfo.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(437, "typeinfo.nim");
	{
		nimln(437, "typeinfo.nim");
		nimln(437, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 20)))) goto LA3;
		nimln(437, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP346));
	}
	LA3: ;
	nimln(438, "typeinfo.nim");
	result.Rawtype = (*x.Rawtype).Base;
	nimln(439, "typeinfo.nim");
	result.Value = x.Value;
	popFrame();
	return result;
}

N_NIMCALL(NI, getenumordinal_131612)(tany123298 x, NimStringDesc* name) {
	NI result;
	tnimtype123211* typ;
	tnimnode123207* n;
	tnimnode123207** s;
	NI i_131822;
	NI HEX3Atmp_131837;
	NI TMP348;
	NI res_131839;
	nimfr("getEnumOrdinal", "typeinfo.nim")
	result = 0;
	nimln(445, "typeinfo.nim");
	typ = skiprange_124812(x.Rawtype);
	nimln(446, "typeinfo.nim");
	{
		nimln(446, "typeinfo.nim");
		nimln(446, "typeinfo.nim");
		if (!!(((*typ).Kind == ((NU8) 14)))) goto LA3;
		nimln(446, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP347));
	}
	LA3: ;
	nimln(447, "typeinfo.nim");
	n = (*typ).Node;
	nimln(448, "typeinfo.nim");
	s = (*n).Sons;
	i_131822 = 0;
	HEX3Atmp_131837 = 0;
	nimln(449, "typeinfo.nim");
	nimln(449, "typeinfo.nim");
	TMP348 = subInt((*n).Len, 1);
	HEX3Atmp_131837 = (NI64)(TMP348);
	nimln(1457, "system.nim");
	res_131839 = 0;
	nimln(1458, "system.nim");
	while (1) {
		nimln(1458, "system.nim");
		if (!(res_131839 <= HEX3Atmp_131837)) goto LA5;
		nimln(1457, "system.nim");
		i_131822 = res_131839;
		nimln(450, "typeinfo.nim");
		{
			NimStringDesc* LOC8;
			NI LOC9;
			nimln(450, "typeinfo.nim");
			nimln(450, "typeinfo.nim");
			nimln(450, "typeinfo.nim");
			if ((NU)(i_131822) > (NU)(32767)) raiseIndexError();
			LOC8 = 0;
			LOC8 = cstrToNimstr((*s[(i_131822)- 0]).Name);
			LOC9 = 0;
			LOC9 = cmpignorestyle_127425(LOC8->data, name->data);
			if (!(LOC9 == 0)) goto LA10;
			nimln(451, "typeinfo.nim");
			{
				nimln(451, "typeinfo.nim");
				nimln(451, "typeinfo.nim");
				if (!!((((*typ).Flags &(1<<((((NU8) 2))&7)))!=0))) goto LA14;
				nimln(452, "typeinfo.nim");
				nimln(452, "typeinfo.nim");
				result = i_131822;
				goto BeforeRet;
			}
			goto LA12;
			LA14: ;
			{
				nimln(454, "typeinfo.nim");
				nimln(454, "typeinfo.nim");
				if ((NU)(i_131822) > (NU)(32767)) raiseIndexError();
				result = (*s[(i_131822)- 0]).Offset;
				goto BeforeRet;
			}
			LA12: ;
		}
		LA10: ;
		nimln(1460, "system.nim");
		res_131839 = addInt(res_131839, 1);
	} LA5: ;
	nimln(455, "typeinfo.nim");
	result = (IL64(-9223372036854775807) - IL64(1));
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getenumfield_131846)(tany123298 x, NI ordinalvalue) {
	NimStringDesc* result;
	tnimtype123211* typ;
	NI e;
	nimfr("getEnumField", "typeinfo.nim")
	result = 0;
	nimln(461, "typeinfo.nim");
	typ = skiprange_124812(x.Rawtype);
	nimln(462, "typeinfo.nim");
	{
		nimln(462, "typeinfo.nim");
		nimln(462, "typeinfo.nim");
		if (!!(((*typ).Kind == ((NU8) 14)))) goto LA3;
		nimln(462, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP347));
	}
	LA3: ;
	nimln(463, "typeinfo.nim");
	e = ordinalvalue;
	nimln(464, "typeinfo.nim");
	{
		nimln(464, "typeinfo.nim");
		nimln(464, "typeinfo.nim");
		if (!!((((*typ).Flags &(1<<((((NU8) 2))&7)))!=0))) goto LA7;
		nimln(465, "typeinfo.nim");
		{
			nimln(465, "typeinfo.nim");
			if (!((NU64)(e) < (NU64)((*(*typ).Node).Len))) goto LA11;
			nimln(466, "typeinfo.nim");
			nimln(466, "typeinfo.nim");
			nimln(466, "typeinfo.nim");
			if ((NU)(e) > (NU)(32767)) raiseIndexError();
			result = cstrToNimstr((*(*(*typ).Node).Sons[(e)- 0]).Name);
			goto BeforeRet;
		}
		LA11: ;
	}
	goto LA5;
	LA7: ;
	{
		tnimnode123207* n;
		tnimnode123207** s;
		NI i_132045;
		NI HEX3Atmp_132046;
		NI TMP349;
		NI res_132048;
		nimln(469, "typeinfo.nim");
		n = (*typ).Node;
		nimln(470, "typeinfo.nim");
		s = (*n).Sons;
		i_132045 = 0;
		HEX3Atmp_132046 = 0;
		nimln(471, "typeinfo.nim");
		nimln(471, "typeinfo.nim");
		TMP349 = subInt((*n).Len, 1);
		HEX3Atmp_132046 = (NI64)(TMP349);
		nimln(1457, "system.nim");
		res_132048 = 0;
		nimln(1458, "system.nim");
		while (1) {
			nimln(1458, "system.nim");
			if (!(res_132048 <= HEX3Atmp_132046)) goto LA14;
			nimln(1457, "system.nim");
			i_132045 = res_132048;
			nimln(472, "typeinfo.nim");
			{
				nimln(472, "typeinfo.nim");
				if ((NU)(i_132045) > (NU)(32767)) raiseIndexError();
				if (!((*s[(i_132045)- 0]).Offset == e)) goto LA17;
				nimln(472, "typeinfo.nim");
				nimln(472, "typeinfo.nim");
				nimln(472, "typeinfo.nim");
				if ((NU)(i_132045) > (NU)(32767)) raiseIndexError();
				result = cstrToNimstr((*s[(i_132045)- 0]).Name);
				goto BeforeRet;
			}
			LA17: ;
			nimln(1460, "system.nim");
			res_132048 = addInt(res_132048, 1);
		} LA14: ;
	}
	LA5: ;
	nimln(473, "typeinfo.nim");
	nimln(473, "typeinfo.nim");
	result = nimIntToStr(e);
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getenumfield_132053)(tany123298 x) {
	NimStringDesc* result;
	NI64 LOC1;
	nimfr("getEnumField", "typeinfo.nim")
	result = 0;
	nimln(477, "typeinfo.nim");
	nimln(477, "typeinfo.nim");
	LOC1 = 0;
	LOC1 = getbiggestint_130214(x);
	result = getenumfield_131846(x, ((NI) (LOC1)));
	popFrame();
	return result;
}

N_NIMCALL(NF, getfloat_132060)(tany123298 x) {
	NF result;
	nimfr("getFloat", "typeinfo.nim")
	result = 0;
	nimln(481, "typeinfo.nim");
	{
		tnimtype123211* LOC3;
		nimln(481, "typeinfo.nim");
		nimln(481, "typeinfo.nim");
		nimln(481, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_124812(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 36)))) goto LA4;
		nimln(481, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP350));
	}
	LA4: ;
	nimln(482, "typeinfo.nim");
	result = (*((NF*) (x.Value)));
	popFrame();
	return result;
}

N_NIMCALL(NF32, getfloat32_132214)(tany123298 x) {
	NF32 result;
	nimfr("getFloat32", "typeinfo.nim")
	result = 0;
	nimln(486, "typeinfo.nim");
	{
		tnimtype123211* LOC3;
		nimln(486, "typeinfo.nim");
		nimln(486, "typeinfo.nim");
		nimln(486, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_124812(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 37)))) goto LA4;
		nimln(486, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP351));
	}
	LA4: ;
	nimln(487, "typeinfo.nim");
	result = (*((NF32*) (x.Value)));
	popFrame();
	return result;
}

N_NIMCALL(NF, getfloat64_132414)(tany123298 x) {
	NF result;
	nimfr("getFloat64", "typeinfo.nim")
	result = 0;
	nimln(491, "typeinfo.nim");
	{
		tnimtype123211* LOC3;
		nimln(491, "typeinfo.nim");
		nimln(491, "typeinfo.nim");
		nimln(491, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_124812(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 38)))) goto LA4;
		nimln(491, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP352));
	}
	LA4: ;
	nimln(492, "typeinfo.nim");
	result = (*((NF*) (x.Value)));
	popFrame();
	return result;
}

N_NIMCALL(NF, getbiggestfloat_132614)(tany123298 x) {
	NF result;
	tnimtype123211* LOC1;
	nimfr("getBiggestFloat", "typeinfo.nim")
	result = 0;
	nimln(497, "typeinfo.nim");
	nimln(497, "typeinfo.nim");
	LOC1 = 0;
	LOC1 = skiprange_124812(x.Rawtype);
	switch ((*LOC1).Kind) {
	case ((NU8) 36):
	{
		nimln(498, "typeinfo.nim");
		result = (*((NF*) (x.Value)));
	}
	break;
	case ((NU8) 37):
	{
		nimln(499, "typeinfo.nim");
		result = ((NF) ((*((NF32*) (x.Value)))));
	}
	break;
	case ((NU8) 38):
	{
		nimln(500, "typeinfo.nim");
		result = (*((NF*) (x.Value)));
	}
	break;
	default:
	{
		nimln(501, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA8;
			nimln(501, "typeinfo.nim");
			failedassertimpl_81021(((NimStringDesc*) &TMP304));
		}
		LA8: ;
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(void, setbiggestfloat_132809)(tany123298 x, NF y) {
	tnimtype123211* LOC1;
	nimfr("setBiggestFloat", "typeinfo.nim")
	nimln(506, "typeinfo.nim");
	nimln(506, "typeinfo.nim");
	LOC1 = 0;
	LOC1 = skiprange_124812(x.Rawtype);
	switch ((*LOC1).Kind) {
	case ((NU8) 36):
	{
		nimln(507, "typeinfo.nim");
		(*((NF*) (x.Value))) = y;
	}
	break;
	case ((NU8) 37):
	{
		nimln(508, "typeinfo.nim");
		(*((NF32*) (x.Value))) = ((NF32) (y));
	}
	break;
	case ((NU8) 38):
	{
		nimln(509, "typeinfo.nim");
		(*((NF*) (x.Value))) = y;
	}
	break;
	default:
	{
		nimln(510, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA8;
			nimln(510, "typeinfo.nim");
			failedassertimpl_81021(((NimStringDesc*) &TMP304));
		}
		LA8: ;
	}
	break;
	}
	popFrame();
}

N_NIMCALL(NimStringDesc*, getstring_133007)(tany123298 x) {
	NimStringDesc* result;
	nimfr("getString", "typeinfo.nim")
	result = 0;
	nimln(514, "typeinfo.nim");
	{
		nimln(514, "typeinfo.nim");
		nimln(514, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 28)))) goto LA3;
		nimln(514, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP353));
	}
	LA3: ;
	nimln(515, "typeinfo.nim");
	{
		nimln(515, "typeinfo.nim");
		nimln(515, "typeinfo.nim");
		if (!!((*((void**) (x.Value))) == 0)) goto LA7;
		nimln(516, "typeinfo.nim");
		unsureAsgnRef((void**) &result, copyString((*((NimStringDesc**) (x.Value)))));
	}
	LA7: ;
	popFrame();
	return result;
}

N_NIMCALL(void, setstring_133216)(tany123298 x, NimStringDesc* y) {
	nimfr("setString", "typeinfo.nim")
	nimln(520, "typeinfo.nim");
	{
		nimln(520, "typeinfo.nim");
		nimln(520, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 28)))) goto LA3;
		nimln(520, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP353));
	}
	LA3: ;
	nimln(521, "typeinfo.nim");
	unsureAsgnRef((void**) &(*((NimStringDesc**) (x.Value))), copyString(y));
	popFrame();
}

N_NIMCALL(NCSTRING, getcstring_133414)(tany123298 x) {
	NCSTRING result;
	nimfr("getCString", "typeinfo.nim")
	result = 0;
	nimln(525, "typeinfo.nim");
	{
		nimln(525, "typeinfo.nim");
		nimln(525, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 29)))) goto LA3;
		nimln(525, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP354));
	}
	LA3: ;
	nimln(526, "typeinfo.nim");
	result = (*((NCSTRING*) (x.Value)));
	popFrame();
	return result;
}

N_NIMCALL(void, assign_133614)(tany123298 x, tany123298 y) {
	nimfr("assign", "typeinfo.nim")
	nimln(531, "typeinfo.nim");
	{
		nimln(531, "typeinfo.nim");
		nimln(531, "typeinfo.nim");
		if (!!((y.Rawtype == x.Rawtype))) goto LA3;
		nimln(531, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP355));
	}
	LA3: ;
	nimln(532, "typeinfo.nim");
	genericAssign(x.Value, y.Value, y.Rawtype);
	popFrame();
}

N_NIMCALL(void, inclsetelement_134060)(tany123298 x, NI elem) {
	tnimtype123211* typ;
	void* p;
	NI e;
	NI TMP357;
	nimfr("inclSetElement", "typeinfo.nim")
	nimln(558, "typeinfo.nim");
	{
		nimln(558, "typeinfo.nim");
		nimln(558, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 19)))) goto LA3;
		nimln(558, "typeinfo.nim");
		failedassertimpl_81021(((NimStringDesc*) &TMP356));
	}
	LA3: ;
	nimln(559, "typeinfo.nim");
	typ = x.Rawtype;
	nimln(560, "typeinfo.nim");
	p = x.Value;
	nimln(562, "typeinfo.nim");
	nimln(562, "typeinfo.nim");
	TMP357 = subInt(elem, (*(*typ).Node).Len);
	e = (NI64)(TMP357);
	nimln(563, "typeinfo.nim");
	switch ((*typ).Size) {
	case 1:
	{
		NI8* a;
		nimln(565, "typeinfo.nim");
		a = ((NI8*) (p));
		nimln(566, "typeinfo.nim");
		nimln(566, "typeinfo.nim");
		nimln(566, "typeinfo.nim");
		(*a) = (NI8)((*a) | (NI8)((NU8)(((NI8) 1)) << (NU8)(((NI8)chckRange(e, ((NI8) -128), ((NI8) 127))))));
	}
	break;
	case 2:
	{
		NI16* a;
		nimln(568, "typeinfo.nim");
		a = ((NI16*) (p));
		nimln(569, "typeinfo.nim");
		nimln(569, "typeinfo.nim");
		nimln(569, "typeinfo.nim");
		(*a) = (NI16)((*a) | (NI16)((NU16)(((NI16) 1)) << (NU16)(((NI16)chckRange(e, ((NI16) -32768), ((NI16) 32767))))));
	}
	break;
	case 4:
	{
		NI32* a;
		nimln(571, "typeinfo.nim");
		a = ((NI32*) (p));
		nimln(572, "typeinfo.nim");
		nimln(572, "typeinfo.nim");
		nimln(572, "typeinfo.nim");
		(*a) = (NI32)((*a) | (NI32)((NU32)(((NI32) 1)) << (NU32)(((NI32)chckRange(e, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))))));
	}
	break;
	case 8:
	{
		NI64* a;
		nimln(574, "typeinfo.nim");
		a = ((NI64*) (p));
		nimln(575, "typeinfo.nim");
		nimln(575, "typeinfo.nim");
		nimln(575, "typeinfo.nim");
		(*a) = (NI64)((*a) | (NI64)((NU64)(1) << (NU64)(((NI64) (e)))));
	}
	break;
	default:
	{
		NI8* a;
		nimln(577, "typeinfo.nim");
		a = ((NI8*) (p));
		nimln(578, "typeinfo.nim");
		nimln(578, "typeinfo.nim");
		if ((NU)((NI)((NU64)(e) >> (NU64)(3))) > (NU)(65535)) raiseIndexError();
		nimln(578, "typeinfo.nim");
		nimln(578, "typeinfo.nim");
		nimln(578, "typeinfo.nim");
		if ((NU)((NI)((NU64)(e) >> (NU64)(3))) > (NU)(65535)) raiseIndexError();
		nimln(578, "typeinfo.nim");
		nimln(578, "typeinfo.nim");
		a[((NI)((NU64)(e) >> (NU64)(3)))- 0] = ((NI8)(NU8)(NU)((NI)(((NI) (a[((NI)((NU64)(e) >> (NU64)(3)))- 0])) | (NI)((NU64)(1) << (NU64)(((NI) ((NI)(e & 7))))))));
	}
	break;
	}
	popFrame();
}
N_NOINLINE(void, typeinfoInit)(void) {
	nimfr("typeinfo", "typeinfo.nim")
	popFrame();
}

N_NOINLINE(void, typeinfoDatInit)(void) {
}

